### ISSUE TITLE
Unexpected trait change notification for nested Dict trait

### ISSUE THREAD

**Issue by mdsmarte** [enthought/traits#1002]
When setting up an extended trait change listener to a nested `Dict`, the notification fires unexpectedly.  Example code:

```python
from traits.api import *


class HasDict(HasTraits):

    dct = Dict({"foo": "bar"})

    @on_trait_change("dct")
    def _update(self):
        print("HasDict handler fired")


class HasNestedDict(HasTraits):

    has_dict = Instance(HasDict, ())

    @on_trait_change("has_dict.dct")
    def _update(self):
        print("HasNestedDict handler fired")


if __name__ == "__main__":
    has_dict = HasDict()
    has_nested_dict = HasNestedDict()

    # Handler does not fire here (expected)
    print("Changing dictionary...")
    del has_dict.dct["foo"]
    print()

    # Handler fires here (unexpected)
    print("Changing nested dictionary...")
    del has_nested_dict.has_dict.dct["foo"]
    print()
```

The handler in `HasDict` _does not_ fire (expected) while the handler in `HasNestedDict` _does_ fire (unexpected).  Based on how I interpret the table in the documentation here:

https://docs.enthought.com/traits/traits_user_manual/notification.html#semantics

I would have expected neither handler to fire since the trait names do not contain `[]` at the end.  If `[]` only applies to `List` traits and not `Dict` traits, I would have expected the behavior of the handlers to be the same (either both fire or neither fire).

**Comment by corranwebster** [comment]
This is a known bug, see #537 and #538 (reported for List traits, but the mechanism is the same). It is a very small fix, but it can't be fixed without substantial breakage of existing code. Much of the recent work on ETS is to create an alternative system that behaves as expected.

I am going to close this as a duplicate.
