### ISSUE TITLE
Stop trying to cache default editor factories

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1030]
This has been a constant source of issues where the attempt to cache editor factories just leads to hidden shared global state as other code assumes that it can modify editor factories in place with no consequences.

See https://github.com/enthought/traitsui/issues/790 for the most recent example of this.

At most, this is going to save a few hundred objects at run time, so any purported benefits of this seem to be far outweighed by the maintenance costs and mental overhead.

**Comment by mdickinson** [comment]
Strong :+1: from me.

**Comment by mdickinson** [comment]
Putting into 6.2.0, but if it accidentally sneaks into 6.1.0 I'm not going to complain too much.
