### ISSUE TITLE
Resolve name-related UserWarnings before release

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1037]
After #1008, anyone on Traits master and the latest releases of TraitsUI/Pyface will see many warnings not related to their own code. #1029 goes some way towards mitigating this, but TraitsUI will still be a source of warnings.

As things stand, if we release Traits 6.1.0 as-is, even after #1029, users on the latest set of ETS releases will see a lot of new warnings that aren't their responsibility. It's not reasonable to expect each ETS-using project to filter out those warnings.

We need to figure out how to resolve this for the 6.1.0 release. The nuclear option would be to revert #1008 and #1029 entirely.

**Comment by kitchoi** [comment]
If the amount of warnings is the main concern, another option may be to use `PendingDeprecationWarning` instead of `UserWarning`, and slowly walk its way up to `DeprecationWarning`.

**Comment by mdickinson** [comment]
Note: much of the discussion is going on in #1029.

**Comment by mdickinson** [comment]
Note that even if we do end up reverting #1008 and #1029, I wouldn't consider those two PRs to be wasted work: they've helped a lot in fleshing out exactly how we want to handle this, and would make implementing this for 6.2 much more straightforward.

**Comment by kitchoi** [comment]
#1029 added advice to the documentation, that advice still stand and may be worth keeping in the doc.

**Comment by mdickinson** [comment]
Agreed: we'd want to revert just the code and keep the documentation.

**Comment by kitchoi** [comment]
Vote :+1: for removing the warning for 6.1 at least.

**Comment by kitchoi** [comment]
On traitsui front, I think these cover all of the warnings:
https://github.com/enthought/traitsui/pull/794
https://github.com/enthought/traitsui/pull/796
https://github.com/enthought/traitsui/pull/797

**Comment by kitchoi** [comment]
For pyface, I think there is only one renaming needed:
https://github.com/enthought/pyface/pull/509
