### ISSUE TITLE
Traits-stubs Instance argument variants not all covered

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1062]
The `Instance` trait type does a lot of argument mangling.  Currently common signatures like:
```
x = Instance(Foo, (positional,), {'keyword': 4})
y = Instance(Foo, {'keyword': 4})
z = Instance(Foo, foo_factory, {'keyword': 4})
```
get flagged as incorrect.  We need to either ~override~ overload or adjust documentation to promote the use of keyword arguments.

**Comment by mdickinson** [comment]
> We need to either override or adjust documentation to promote the use of keyword arguments.

+1 for fixing the traits stubs (I'm not sure whether that's what you mean by "override"). We can definitely promote the use of keyword arguments, but that's not going to help in the short term.

**Comment by corranwebster** [comment]
Being a bit telegraphic.  I was thinking of using the `@overload` decorator to allow multiple signatures, but a but of experimentation is telling me that it's probably sufficient to just have `*args, **kwargs` for everything except the first argument.
