### ISSUE TITLE
_default method doesn't set the default value of a mapped trait

### ISSUE THREAD

**Issue by ievacerny** [enthought/traits#1081]
Current behaviour:
``` python
class Person(HasTraits):

    married = Map({'yes': 1, 'no': 0})

    def _married_default(self):
        return 'no'


bob = Person()
print(bob.married)  # prints 'no'
print(bob.married_)  # prints <undefined>, but should print 0
```

The problem seems to lie in the way `_default` methods are attached to traits. This happens after all trait definitions have been processed and definitions for mapped traits have been created.
https://github.com/enthought/traits/blob/c3af7affed2d69b1e0239bc9e836f220fa6606ad/traits/has_traits.py#L621-L633
The code iterates over all traits and checks for their default methods. In the case of the example, it checks and finds `_married_default` which is then set as the default value of `married` trait. However, because there is no ` _married__default`, no default value is set for `married_` trait.

One solution I can think of is that if the trait name ends in `_`, which indicates a mapped trait, the code also looks for a default method using `name[:-1]` and sets the default value of the mapped trait to be a mapped version of the default method it found.

A sidenote: default value assignment through trait definition sets the default value of the mapped trait as expected via https://github.com/enthought/traits/blob/c3af7affed2d69b1e0239bc9e836f220fa6606ad/traits/trait_converters.py#L112-L125

**Comment by mdickinson** [comment]
We should check other mapped trait types (like `PrefixMap` and `PrefixList`) as well to see if they have the same issue.

**Comment by kitchoi** [comment]
Well spotted.
I tried to write a test with the example provided above, and I was able to fix the test by
either:
(1) Setting `is_mapped` to False in `Map`, OR
(2) Removing this check in ctraits.c:
https://github.com/enthought/traits/blob/c3af7affed2d69b1e0239bc9e836f220fa6606ad/traits/ctraits.c#L1893

This change breaks another test, which can be easily fixed by changing `mapped_value` from:
```
    def mapped_value(self, value):
        """ Get the mapped value for a value. """
        return self.map[value]     # raise KeyError for another test
```
to 
```
    def mapped_value(self, value):
        """ Get the mapped value for a value. """
        return self.map.get(value, Undefined)
```

Not saying this is necessarily how this should be fixed. Just wanted to report what I have found (which could also be unhelpful).

**Comment by ievacerny** [comment]
> We should check other mapped trait types (like `PrefixMap` and `PrefixList`) as well to see if they have the same issue.

I'm pretty sure this applies to all trait types that use mapped traits and to traits that have mapped handlers (e.g. `Trait('yes', {'yes': 1, 'no': 0})`)

This bug seems to be the cause for this issue as well: https://github.com/enthought/traitsui/issues/763

**Comment by ievacerny** [comment]
I checked and more specifically, this affects `Map`, `PrefixMap` and `Expression` traits defined in Traits. It also affects other traits defined using `Trait` which end up with a `TraitMap` handler (as the example in the previous comment). `RGBColor` and `Color` traits defined in TraitsUI are currently defined that way and are therefore affected by this bug as well.
___
I investigated the three potential solutions suggested above and here's what I found:

> (0) One solution I can think of is that if the trait name ends in _, which indicates a mapped trait, the code also looks for a default method using name[:-1] and sets the default value of the mapped trait to be a mapped version of the default method it found.

This approach seems to work fine but it's not very elegant - it's adding additional code branches to an already overloaded `update_traits_class_dict` function. The benefit of this approach is that the mapped trait can get its default value independently from the key trait. This approach assumes that a mapped handler will have a `mapped_value` method but I think this is a reasonable assumption to make.

> (1) Setting is_mapped to False in Map

This doesn't really work because based on the value of `is_mapped` the mapped trait is created with additional metadata. It does work with this example because that metadata isn't used anywhere, but problems would likely arise with pickling and integration with TraitsUI

> (2) Removing this check in ctraits.c:
https://github.com/enthought/traits/blob/c3af7affed2d69b1e0239bc9e836f220fa6606ad/traits/ctraits.c#L1893

This line was added as part of a commit that was solving a problem with the default value initialization (https://github.com/enthought/traits/commit/a5081d5c45b9fb43325aab4ffbab9975de7947e7). It's not clear what the problem was and if it still exists.
The line is in a `getattr_trait` function so the approach has a side effect of updating the mapped trait every time a key trait is accessed. This ends up raising `KeyError` when a key trait without a default value is being read, but that can be fixed by the simple change in `mapped_value`. Another caveat of this would be that the value of the mapped trait is only assigned *after* a key trait has been accessed leading to this result:
``` python
class Person(HasTraits):

    married = Map({'yes': 1, 'no': 0})

    def _married_default(self):
        return 'no'


bob = Person()
print(bob.married_)  # would still print <undefined>
print(bob.married)  # prints 'no'
print(bob.married_)  # prints 0
```
____
Personally I would favour approach (0), but I'm open to other potential solutions and advice on which approach would be best.

**Comment by kitchoi** [comment]
> the approach has a side effect of updating the mapped trait every time a key trait is accessed.

I think this `getattr_trait` assigns the default value to the object `__dict__` so that the next time the attribute is accessed, the value in `__dict__` is obtained and the `getattr_trait` is not called again.

**Comment by kitchoi** [comment]
Maybe we should also be looking into this method:
https://github.com/enthought/traits/blob/fc43595ad961652424075be94754659b447babe3/traits/trait_converters.py#L112-L125

I believe this is how the mapped CTrait is created. 
The `default_value()` method returns a tuple, the first item indicates how the default is obtained. The meaning of the remaining item(s?) depends on the first.
In the case of a dynamic default, the second item is the *unbound* `_name_default` method there. Currently this `mapped_trait_for` tries to map this method to a value, and then ignore if its fails. Maybe it could be extended to handle dynamic default.

**Comment by ievacerny** [comment]
> I believe this is how the mapped CTrait is created.

Yes, this is how the mapped trait is created, but it is done *before* the dynamic default method is attached to the original trait, which I assume is meant to ensure that dynamic default method always overwrites the default value specified in the trait definition.

**Comment by ievacerny** [comment]
> > the approach has a side effect of updating the mapped trait every time a key trait is accessed.
> 
> I think this `getattr_trait` assigns the default value to the object `__dict__` so that the next time the attribute is accessed, the value in `__dict__` is obtained and the `getattr_trait` is not called again.

Yes, you're right! I missed the assignment to `__dict__`. Updated the long message to correct this.

**Comment by mdickinson** [comment]
The `ctraits.c` code @kitchoi pointed to is quite odd: why is a trait `get` operation calling `post_setattr`? It looks to me as though most of the Trait types that implement `post_setattr` are mapped trait types (the exception seems to be the `Supports` trait type), so the block would rarely be executed. And indeed, it's not exercised by the test suite: if I remove that block (and the similar one a few lines later) then disturbingly, no tests fail. I suspect that we _should_ just ditch those blocks (after investigating the effect on `Supports`), but I think that's a separate cleanup issue.

I think solution 0 is the right one in principle: set up the default for the shadow trait at the same time as for the main trait. Yes, it's going to make `update_traits_class_dict` even more hairy, but it's not as if it was the cleanest function in the first place. (Believe it or not, it's much better than it was: @jvkersch did some refactoring on this a while ago.)

**Comment by mdickinson** [comment]
> I think solution 0 is the right one in principle

Hmm; not sure this is quite right, either, and now I think I'm beginning to understand why that `post_setattr` call is there.

@ievacerny What was your plan for creating the default for the mapped trait? Do you already have code you could share? I have a guess as to what it was you intended, but I think I may be guessing wrong.

The thing that's worrying me is that I think we want to ensure that any `_mytrait_default` method is only called once. If we create a new callable wrapping `_mytrait_default` that's going to act as the method providing the default for the shadow trait, then I'm not sure how we make sure that `_mytrait_default` only gets called once.

**Comment by mdickinson** [comment]
BTW, I don't want to think about what happens if there's a `_mytrait__default` method in addition to, or perhaps instead of, a `_mytrait_default` method. I think we can file any resulting surprises from that in the "well, don't do that then" bin.

**Comment by mdickinson** [comment]
So now solution (2) is looking like the only reasonably feasible one that doesn't involve a lot of restructuring. Though rather than doing
```
return self.map.get(value, Undefined)
```
I think we want an explicit `if value is Undefined` check (returning `Undefined` in that case).

**Comment by ievacerny** [comment]
> @ievacerny What was your plan for creating the default for the mapped trait? Do you already have code you could share? I have a guess as to what it was you intended, but I think I may be guessing wrong.
> 
> The thing that's worrying me is that I think we want to ensure that any `_mytrait_default` method is only called once. If we create a new callable wrapping `_mytrait_default` that's going to act as the method providing the default for the shadow trait, then I'm not sure how we make sure that `_mytrait_default` only gets called once.

That was exactly my plan - wrap the `_mytrait_default()` and assign this new method as the default value of the mapped trait.

Maybe this sort of default would work for the mapped trait: 
``` python
default = (
    lambda object:
    key_trait.handler.mapped_value(
        getattr(object, key_trait_name, Undefined)
    )
)
```
I think this would have the side effect of setting the default value of the key trait if the mapped trait is accessed, but maybe that is a reasonable thing to do? And I think this would work with the requirement to only call the default method once. (I haven't tested this yet because of some implementation difficulties).

I like the simplicity of (2) but it worries me slightly that in order to get the value of the mapped trait, the key trait needs to be accessed first. I can imagine a use case where the code would only read from the mapped trait -- the default method would still not work properly in that case. Although the workaround of reading the key trait first, even if it's not used, is not that bad.

**Comment by mdickinson** [comment]
> I think this would have the side effect of setting the default value of the key trait if the mapped trait is accessed, but maybe that is a reasonable thing to do?

I think this is more than reasonable - I think it's the right thing to do.

> I like the simplicity of (2) but it worries me slightly that in order to get the value of the mapped trait, the key trait needs to be accessed first.

Agreed; that seems like a potential bug magnet.

My one remaining worry is around pickling: the proposed `lambda` isn't going to be pickleable, which may cause issues with persisting a `HasTraits` object with a mapped trait. But I haven't thought it through, and there may be no issues there. If there _are_ issues, I think we can solve them by replacing the `lambda` with a method call.

**Comment by kitchoi** [comment]
> Yes, this is how the mapped trait is created, but it is done before the dynamic default method is attached to the original trait, which I assume is meant to ensure that dynamic default method always overwrites the default value specified in the trait definition.

Yes you are right. I tried running this function with an instance of `HasTraits` which is after everything is hooked up, so I was wrong about the returned value of `trait.default_value()` when it is run in `update_traits_class_dict`.

Maybe you are already thinking doing the same, though I am not sure from the conversation above:  Would it be possible put your default function in  https://github.com/enthought/traits/issues/1081#issuecomment-628825080 in this `mapped_trait_for`?  It will need the trait name, but it seems that all uses of `mapped_trait_for` are in the context where the trait name is available already, so the function `mapped_trait_for` can be expanded to accept `name` as an argument.

If this works, it might not need much changes in `update_traits_class_dict` afterall.

**Comment by kitchoi** [comment]
> Would it be possible put your default function in #1081 (comment) in this mapped_trait_for? It will need the trait name

Another piece for this is the `CTrait.set_default_value` method

**Comment by ievacerny** [comment]
Opened a draft PR, we can continue discussion there: https://github.com/enthought/traits/pull/1091
