### ISSUE TITLE
NoneTrait and Union use a different metadata name for static default

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1104]
On Traits 6.0, `Either` is the only trait type where static default is defined via the metadata named `"default"`, all other trait types have their static default provided via the metadata named `"default_value"`, which is the name assumed by the base `TraitType`.

On master, `NoneTrait` and `Union` expect the static default to be provided via the `"default"` metadata, while it is consistent with `Either`, it is inconsistent with the base class and other trait types.

If one tries to define `Union` with `default_value` as the metadata, an error occurs:
```
>>> Union(Str(), List(), default_value="123")

~/Work/ETS/traits/traits/trait_types.py in __init__(self, *traits, **metadata)
   3864 
   3865         self.default_value_type = _infer_default_value_type(default_value)
-> 3866         super().__init__(default_value, **metadata)
   3867 
   3868     def validate(self, obj, name, value):

TypeError: __init__() got multiple values for argument 'default_value'
```

Since these two trait types have not been released yet, we can still fix these.

**Comment by mdickinson** [comment]
+1 for fixing for 6.1.

**Comment by mdickinson** [comment]
I think it's not unreasonable to classify this as a (design) bug.

**Comment by kitchoi** [comment]
If someone does a find-all-and-replace to convert `Either` to `Union` and neglect to rename `default` to `default_value`. Nothing would fail but then the `default` originally defined for `Either` becomes an ordinary piece of metadata.  So the release documentation will need to highlight that difference.

It is tempting to make `Union` do a "guess-what-you-mean" and raise if there is a metadata named `"default"`. In practice this might not be so bad to forbid a metadata named "default" to be used, at least for sometime. It is easy to forbid something at the start and relax it later, when migrations from `Either` settle.

**Comment by mdickinson** [comment]
Raising for a `default` keyword argument sounds reasonable to me. I agree that there's a transition risk here for people moving code from `Either` to `Union`.
