### ISSUE TITLE
Doc: Union is missing from the table of predefined traits

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1113]
In the traits user manual, there is a section on "Other Predefined Traits" where trait types such as `Either` is mentioned.  The new `Union` trait type is not included there.

**Comment by mdickinson** [comment]
Nice catch. Let's fix this for 6.1

**Comment by mdickinson** [comment]
We're also missing index entries for `Map`, `PrefixMap` and `PrefixList`.

**Comment by kitchoi** [comment]
Unicode is not there either, will fix that together with Union.

**Comment by kitchoi** [comment]
> Unicode is not there either, will fix that together with Union.

Oh no `Unicode` is supposed to die, taking that back.
