### ISSUE TITLE
Migration to identity comparison mode for container traits

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1122]
https://github.com/enthought/traits/pull/1117 adds a warning if container mutations are observed and the trait comparison mode is set to equality (the default). To fix the warning, one needs to manually set the comparison mode to identity, which may be tedious.

We need a way to migrate code to minimize the impact of these warnings.

Ideas:
- Provide an easy way for projects to set comparison mode to identity, preferably one that can be done with find-all-and-replace, such as an alias
- Eventually make comparison_mode=ComparisonMode.identity the default for List/Dict/Set, possibly with advanced warnings through a number of releases

Excerpt from https://github.com/enthought/traits/pull/1117#pullrequestreview-415057518:
> One possible plan is to eventually make comparison_mode=ComparisonMode.identity the default for these trait types; we'd have to do that after most code had transitioned to using observe, and with suitable warnings (probably over several releases).
> Another possibility (orthogonal to the first) would be to provide convenience aliases: e.g., IList(...) = List(..., comparison_mode=ComparisonMode.identity). (Thinking "I" for "Identity", but we'd have to figure out the right name.)

Excerpt from https://github.com/enthought/traits/pull/1117#issuecomment-631338604
> In some future release, pull comparison_mode out of the keyword arguments of List.__init__ (and friends), with the default None in the signature. If it is None, use ComparisonMode.equality for backward compatibility but put up a deprecation warning. The deprecation warnings are going to be very noisy if code has not done the switch early on.
> ...
> Note there is also a scenario where Union is used with a container type as its inner trait, and the identity comparison mode needs to be defined on the Union, not on the container type (see test in this PR).

**Comment by mdickinson** [comment]
Putting this into 6.2.0 so that it's on our radar. We likely can't complete this in 6.2.0, but we can aim to have a plan by the 6.2.0 release.

**Comment by kitchoi** [comment]
Did #1165 make this issue obsolete such that this issue can be closed? Or does the proposal still stand in its own right?

**Comment by kitchoi** [comment]
Since I opened the issue, I should say what I think: I think this can be closed.

**Comment by mdickinson** [comment]
Yes, I think we can call this obsolete.

**Comment by kitchoi** [comment]
Excellent. Racing to the close button...

**Comment by mdickinson** [comment]
Darn. Too slow. Again.
