### ISSUE TITLE
Restrict PrefixList to accept only a list of values

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1137]
`PrefixList` has not been released yet and it currently accepts both of these signatures:
```
PrefixList("one", "two", "three")
```
and
```
PrefixList(["one", "two", "three"])
```

Overloading signatures adds maintenance cost.
It is not clear why both signatures need to be supported. 
Proposal: Restrict the signature to accept only a list of values (i.e. the second signature). This is also consistent with `PrefixMap`.  If it is necessary to accept the first signature, that can be added back in the future.

**Comment by mdickinson** [comment]
+1 for just supporting the second signature for now. I don't see a need to support both.
