### ISSUE TITLE
test_trait_event_notifier mutates global state

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1154]
The `test_trait_event_notifier` test module modifies `logging._handlerList`, repeatedly appending new `StreamHandler` objects but not removing them again.

**Comment by mdickinson** [comment]
Hmm. This looks like a problem with the business logic, not just with the tests. `ObserverExceptionHandler` does an `addHandler`, but there's no corresponding `removeHandler` anywhere. 

@kitchoi Ideas?

**Comment by mdickinson** [comment]
Actually, we really shouldn't be doing `addHandler` at all in the business logic. That violates the fundamental rule of logging best practices: libraries emit log messages; applications configure logging.

**Comment by kitchoi** [comment]
There I was replicating the handler in `traits.trait_notifiers`, I think the current behaviour for `on_trait_change` is to always log to the console. This behaviour helps capturing programming errors when one runs the tests. I hardly see a project that tries to set logging for the traits logger.

**Comment by mdickinson** [comment]
Right, `trait_notifiers` is wrong to be configuring logging, too, but that's a separate issue. We need to get rid of the logging configuration here.

**Comment by kitchoi** [comment]
OK

**Comment by mdickinson** [comment]
For the tests, specifically, it's fine to be configuring logging, so long as that configuration is undone in the tearDown.
