### ISSUE TITLE
Explicitly document the role of  of Instance args

### ISSUE THREAD

**Issue by jdmarch** [enthought/traits#1180]
@mdickinson wrote elsewhere:

> There's good API documentation for Instance, and there may also be Traits tutorial examples that work well. What there isn't is a useful section in the user manual.

> Ideally I think we want something here: https://docs.enthought.com/traits/traits_user_manual/defining.html#predefined-traits

> The distinction between `Instance(SomeClass)` and `Instance(SomeClass, args=())` is that the former has a default value of `None`. (So in this case there's no lazy instantiation.) The latter will compute the default lazily at first access.

Also explicitly document (or disparage) the equivalent form `Instance(SomeClass, ())`

**Comment by jdmarch** [comment]
Further from @mdickinson 

> FWIW, I'd recommend always passing `args` and `kw` by name, so `Instance(SomeClass, args=())` rather than `Instance(SomeClass, ())`.

**Comment by mdickinson** [comment]
I already opened #1179 for this. :-)
