### ISSUE TITLE
Don't use "Undefined" for "Map" and "PrefixMap" defaults

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1187]
I think we should change the default of "Map", if not explicitly given, from `Undefined` to `None` (and document that). `Undefined` has special meaning to the Traits internals.

EDIT: This also applies to `PrefixMap`, of course.

**Comment by corranwebster** [comment]
Yes, I think this is fair.  `Undefined` should only be seen as a "the old value couldn't be provided" value in trait handlers, I think.

**Comment by mdickinson** [comment]
We also abuse `Undefined` as a general-purpose sentinel in various places (for example in the `cached_property` implementation), but I think that's a separate issue.

**Comment by kitchoi** [comment]
Then how do we differentiate a default value that is undefined, and a default value that is defined to be `None`? `Map({1: "1", 2: "2", None: "None"}, default_value=None)`.

**Comment by mdickinson** [comment]
Second option: do something similar to what we do for `Enum` and take the first element of the map as the default if no default is given. I'd be wary about doing this if dictionaries weren't now ordered, but now that they are at least the behaviour would be reasonably well defined. (Well, not on Python 3.5, but I don't care very much there. :-)

**Comment by mdickinson** [comment]
> do something similar to what we do for `Enum` and take the first element of the map as the default if no default is given

From discussion in another forum, this seems like the way to go. It's also consistent with the `PrefixList`, and @corranwebster pointed out that conversion from `Enum` to `Map` is a fairly natural thing to want to do (e.g., model has an `Enum` trait; UI has a corresponding view using `Map`).

**Comment by mdickinson** [comment]
Updated the issue title for accuracy.

**Comment by kitchoi** [comment]
> From discussion in another forum, this seems like the way to go. It's also consistent with the PrefixList, and @corranwebster pointed out that conversion from Enum to Map is a fairly natural thing to want to do (e.g., model has an Enum trait; UI has a corresponding view using Map).

Another benefit of this is that the default-default value is definitely going to be a valid value too (the static default may not be for `Map`, but that is a separate issue).
