### ISSUE TITLE
PrefixList default-default value is None?

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1191]
`PrefixList` only supports strings. If the given list of strings is empty, and a static default is not given, then the default default value is `None`.

To be consistent with the default default value for `Str`, I think PrefixList default default value should be an empty string.

**Comment by mdickinson** [comment]
I'd make this an error, instead. Using `PrefixList` with an empty list makes little sense.

**Comment by kitchoi** [comment]
Yep. Agreed an error is better.

**Comment by mdickinson** [comment]
Let's do this cleanup for 6.2; we might also add explicit errors for `Map` and `PrefixMap` with empty mappings at the same time.

**Comment by kitchoi** [comment]
OK, I suppose it is fair to assume that no one is going to instantiate a `PrefixList` with an empty list and therefore making this an error will unlikely break code depending on 6.1?

**Comment by mdickinson** [comment]
Yes, I think that's a safe assumption.
