### ISSUE TITLE
Deprecated traits in traits.traits stub

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1202]
The `Color`, `RGBColor` and `Font` traits were deprecated and moved to `traitsui` in version 6.1.0 of traits. They are included in the traits stub though - 

https://github.com/enthought/traits/blob/21e2a99efd22aa4fbbe0028c7b531d6bce4bac23/traits-stubs/traits-stubs/traits.pyi#L64-L70

**Comment by mdickinson** [comment]
This is expected. They should be removed from the stubs when they're removed from the corresponding version of Traits.
