### ISSUE TITLE
Document that the `Dict`, `List` and `Set` trait types copy on assignment

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1226]
After:

```
from traits.api import Dict, HasTraits

class A(HasTraits):
    x = Dict()
class B(HasTraits):
    y = Dict()
a = A(x={})
b = B(y=a.x)
```
one might expect `a.x` and `b.y` to refer to the same dictionary.

Similarly, one might expect `a.x` to be mutated in the following:
```
>>> from traits.api import *
>>> class A(HasTraits):
...     x = List()
... 
>>> options = [1, 2, 3]
>>> a = A(x = options)
>>> a.x
[1, 2, 3]
>>> options.append(4)
>>> a.x
[1, 2, 3]
```

We should expand the docstrings of `Dict`, `List` and `Set` to explain that the values are copied on trait assignment. The information should probably go into the user guide, too (though we currently don't have good sections on collection types).

**Comment by kitchoi** [comment]
👍 
This has bitten me a number of times.

It would have been nice if `TraitDictObject` (and friends') `__repr__` did not pretend to be `dict` (and friends). I bet that's not going to change since it is likely to break a lot of code otherwise.

**Comment by mdickinson** [comment]
Code that's depending on a particular form of `__repr__` is a little bit suspect anyway. That's not to say that we should break such code gratuitously: only if we have a good reason to change.

But I think I _would_ like to see the `__repr__` of these objects changed; I think it would turn a bunch of late surprises into earlier surprises, and make debugging easier. We can keep the `__str__` matching the upstream base class, for the benefit of `print` ed objects.
