### ISSUE TITLE
Add some content of optional_dependencies to traits.testing.api

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1236]
Pyface needed `requires_numpy` and `numpy` from `traits.testing.optional_dependencies` (see [discussion](https://github.com/enthought/pyface/pull/543#discussion_r449054400)). So this issue is for moving these objects (maybe along others too) to `traits.testing.api` so that `pyface` can import from it safely (related to #1213)

**Comment by mdickinson** [comment]
I'd rather have Pyface re-implement than import from Traits here. The functionality has nothing particularly to do with Traits, and Traits is not the right place for common non-Trait-related utilities.

**Comment by rahulporuri** [comment]
i think it's still useful to make `optional_dependencies` accessible from the `api` module.

**Comment by kitchoi** [comment]
For the record, I am in favour of pyface reimplementing those objects.

**Comment by mdickinson** [comment]
I disagree. Everything we put in an `api` module is something we're guaranteeing to support. Traits already has a bunch of utilities that have nothing to do with Traits in particular; I don't want to add to those.

Utilities that _are_ directly Traits-related are a different matter, of course.

**Comment by kitchoi** [comment]
I am happy for this issue to be closed as a wont-fix...

**Comment by kitchoi** [comment]
Closing... If anyone wants to advocate further for this, please feel free to reopen.
