### ISSUE TITLE
Trait documenter fails on regular Python `property` s

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1238]
In traits-futures, we have an `Interface` subclass that contains a method decorated with both `property` and `abstractmethod`.  The trait documenter causes Sphinx to fail when building documentation for that class.

The class in question is `I_Future`: https://github.com/enthought/traits-futures/blob/da69dcc788c8ded85fd50dc0d8a06ce3748e4a39/traits_futures/i_future.py#L60-L81

The trait documenter tries to document `exception` as a trait, and then fails when it can't find the definition.

The build output looks like this:
```
mirzakhani:traits-futures mdickinson$ ci doc
Running Sphinx v2.3.1
making output directory... done
loading intersphinx inventory from https://docs.enthought.com/pyface/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.enthought.com/traits/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 19 source files that are out of date
updating environment: [new config] 19 added, 0 changed, 0 removed
reading sources... [ 47%] api/traits_futures.i_future                                                                                                                                                                              
Exception occurred:
  File "/Users/mdickinson/.edm/envs/traits-futures-py36-pyqt5/lib/python3.6/site-packages/traits/util/trait_documenter.py", line 142, in _get_trait_definition
    item = next(tokens)
StopIteration
The full traceback has been saved in /var/folders/07/jbbjv8b53bs5y9xyjdyn1zgw0000gn/T/sphinx-err-426ysh8q.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by mdickinson** [comment]
@rahulporuri I'd like to nominate this for the next sprint, if possible. The failure mode right now is pretty bad, in that it halts the Sphinx run. A minimal fix would allow the Sphinx run to continue (but still possibly give malformatted output for the problematic class variables). A full fix would of course be better.

**Comment by mdickinson** [comment]
The ABC complications are irrelevant here. The proximate cause is having a documented property in a `HasTraits` subclass. Here's a minimal example that reproduces the issue:
```
class HasTraitsWithProperties(HasTraits):
    @property
    def my_property(self):
        "A documented property."
```

**Comment by rahulporuri** [comment]
I'm not even sure what the minimal fix or the right fix look like. But we should definitely be able to squeeze this into the next sprint (and try making a traits bug fix release once this fix is in?)

**Comment by mdickinson** [comment]
> and try making a traits bug fix release once this fix is in?

Yes, there are some other candidates for backport to a bugfix release. I think they're all already labelled appropriately, so should be easy to find.

**Comment by mdickinson** [comment]
> I'm not even sure what the minimal fix or the right fix look like.

The test for a minimal fix is that a Sphinx build can complete as normal, but maybe the formatting isn't correct.
Test for the right fix: the Sphinx build completes as normal, and the rendering of the output is exactly the same as it would be for a documented `property` in a regular (non-`HasTraits`) Python class.

**Comment by mdickinson** [comment]
This is linked to #947: the property becomes an element of `__class_traits__`.
