### ISSUE TITLE
Array doesn't have `coerce` option

### ISSUE THREAD

**Issue by coreysharris** [enthought/traits#1244]
`AbstractArray` has a `coerce` kwarg, but it's set to `False` by the `Array` constructor. I think this might be because the `coerce` argument currently doesn't actually function correctly: https://github.com/enthought/traits/blob/master/traits/trait_numeric.py#L149-L155

I propose that if `coerce=False`, the validation should raise a `TraitError` if the conversion would result in data loss (e.g., float -> int). Otherwise, the conversion should be allowed to proceed. With that change in place, I think `Array` should surface the `coerce` option.

I'm happy to submit a PR if this change sounds desirable.

**Comment by mdickinson** [comment]
The meaning of `coerce` in this particular case is analogous to the meaning in `Int` versus `CInt`. Here it's used to distinguish `Array` from `CArray`: `Array` is hard-coded to use`coerce=False`, while `CArray` is hard-coded to use `coerce=True`: if you want coercion, you're supposed to use `CArray`, not `Array`. So the particular choice to enforce `coerce=False` in `Array` is deliberate.

I think you're looking for something more like what PR #547 proposes. More generally, there are a number of outstanding issues with respect to the `Array` trait types. It would be good to make the `Array` and `CArray` infrastructure a target of one of the sprints at some point.

**Comment by mdickinson** [comment]
@coreysharris Could you review PR #547 and see if it would meet your needs? If so, we can try to prioritise it.

**Comment by rahulporuri** [comment]
now that #547 has been merged, can this issue be closed?

**Comment by mdickinson** [comment]
Yes, I think so.
