### ISSUE TITLE
Traits 6.1.1 release

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1252]
I'm making a placeholder issue for the Traits 6.1.1 release, so that it can be added to the appropriate sprint.

There are currently 10 closed and one open PR labelled as needing backport to 6.1. The 10 closed PRs are backported in #1251. The open PR is #1246, currently awaiting review.

I'm not making a checklist as an issue this time around; instead, see the [wiki](https://github.com/enthought/traits/wiki/How-to-make-a-bugfix-release) for the process for bugfix releases.

**Comment by rahulporuri** [comment]
the release is complete so we should be able to close this now.

**Comment by mdickinson** [comment]
> the release is complete so we should be able to close this now.

Almost! Announcements are still on my to-do list.

**Comment by mdickinson** [comment]
Announcements have been sent. All done. Closing.
