### ISSUE TITLE
Traits emits its own deprecation warning on TraitMap

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1258]
From running test suite of TraitsUI (with `-W default` switched on), I got the following deprecation warning coming from traits itself:
```
/Users/kchoi/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traits/traits.py:330: DeprecationWarning: 'TraitMap' trait handler has been deprecated. Use Map instead.
  other.append(TraitMap(map))
```
That is here: https://github.com/enthought/traits/blob/1af120c7d68356105d66ec6458967b5660e37e3f/traits/traits.py#L330

**Comment by mdickinson** [comment]
I'm not sure whether we should silence that instance or not; ideally, users shouldn't be using the code path that leads to this, so the `DeprecationWarning` may still be useful.

And silencing is a bit awkward if you don't want to mutate global state - we may actually want to add a hidden "dont_warn" argument to the `TraitMap` constructor.

**Comment by kitchoi** [comment]
> I'm not sure whether we should silence that instance or not; ideally, users shouldn't be using the code path that leads to this, so the DeprecationWarning may still be useful.

Yep I have not looked hard into how TraitsUI code path got to this. It could well be that the code path is already using something else that is also deprecated.

**Comment by kitchoi** [comment]
I was able to find where the warning was coming from, it is coming from this:
https://github.com/enthought/traitsui/blob/79e51389c2b64c2b50e51ad277f7617011ba4170/traitsui/qt4/color_trait.py#L99-L115

**Comment by mdickinson** [comment]
Thanks. That looks like a useful warning - that's code that we'll definitely want to update in TraitsUI. For silencing here, I guess the question is how much the warning is going to bother projects built on _top_ of the ETS stack.

**Comment by kitchoi** [comment]
> that's code that we'll definitely want to update in TraitsUI. For silencing here, I guess the question is how much the warning is going to bother projects built on top of the ETS stack.

Is the `Trait` [factory function with uses the `_TraitMaker` that emits this warning](https://github.com/enthought/traits/blob/91cd08cc60db942557be45eb1663578d66f8ce73/traits/traits.py#L148) deprecated?

Any project could be calling `Trait` not via ETS stack. When I saw the warning coming from `Trait` itself, and I did check if `Trait` is deprecated, and it isn't obvious that it is, and therefore I opened the issue.

**Comment by mdickinson** [comment]
> Is the `Trait` factory function with uses the `_TraitMaker` that emits this warning deprecated?

Not yet, no - it's something we're trying hard to move away from (which was most of the reason for introducing `Union` to replace `Either`), but we're not yet at a place where we have replacements for all the paths that are using it. We're getting closer, though.

My guess would be that the vast majority of `Trait` uses are in ETS, or in ancient code that's no longer used - I wouldn't expect to find too many uses in new code.

**Comment by mdickinson** [comment]
> it's something we're trying hard to move away from

... which I guess means that it _is_ deprecated, in the sense that we don't want people to use it in new code. So the fact that it's not recommended for use in new code should definitely be documented. I'd reluctant to actually make uses of `Trait` emit a `DeprecationWarning`: I fear that would cause a lot of noise for ETS-using projects. (I don't care so much about noise generated within ETS.)

**Comment by kitchoi** [comment]
Could we consider this?: https://github.com/enthought/ets/issues/37
I am not saying this would definitely work - just thinking maybe it is worth a try.
In practice it is very hard to track down components that are nominally deprecated by documentation or by word of month, some warnings would help.

**Comment by kitchoi** [comment]
On https://github.com/enthought/traits/issues/1258#issuecomment-667066649
See https://github.com/enthought/traitsui/issues/883

Just to report: I did try to resolve the deprecation warning on TraitsUI but it is not as trivial as one might think.
Because one of the values given to `Trait` is a mapping, that turns `Trait` into a mapped trait, and downstream code is using the `trait_name_` attribute. Attempt to convert `Trait` to `Union` obviously did not work very well. Attempt to just change the mapping to `Map` without touching `Trait` causes a lot of tests to fail:
```
    return Trait(
        default,
        Map(standard_colors),
        convert_to_color,
        editor=get_color_editor,
        **metadata
    )
```

**Comment by kitchoi** [comment]
See https://github.com/enthought/traits/pull/1336 which demonstrates the difficult situation in the form of tests.

**Comment by mdickinson** [comment]
I see a couple of options here (for Traits):

- find a way to silence the `DeprecationWarning` when it's triggered by Traits itself. The cleanest way to do that is probably a private parameter used to prevent the `DeprecationWarning` from being issued at all
- undeprecate `TraitMap`, or at least make it a documentation-only deprecation

**Comment by mdickinson** [comment]
Let's do the simple thing for the next Traits release and remove the `DeprecationWarning` for `TraitMap` entirely. In effect, it's too soon to deprecate it, because there isn't an obvious replacement.

**Comment by kitchoi** [comment]
> Let's do the simple thing for the next Traits release and remove the DeprecationWarning for TraitMap entirely. In effect, it's too soon to deprecate it, because there isn't an obvious replacement.

SGTM
