### ISSUE TITLE
Update EDM version

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1260]
We should update the EDM version used in `etstool.py` to EDM 3.0.x.

The key feature is that EDM 3.0 enables use of rh7 by default on Linux, and some parts of EDM 2.x don't allow specification of the RH platform. The various optional dependencies of Traits (NumPy, Sphinx, etc.) are no longer being built for rh6.

See also: enthought/traitsui#1025 and enthought/pyface#607.

Note that this isn't as critical for Traits as for TraitsUI and Pyface, since in Traits, `etstool.py` is only a helper tool for the developer (though it's also what we use to build docs), and Travis CI and Appveyor don't use `etstool.py`.

**Comment by rahulporuri** [comment]
I'm not a 100% sure what needs to be done in traits etstool.py to make it work with EDM 3.0.1. The only thing I can think of is the ability to set linux platform tag as rh6 vs rh7. Is that the change this issue is referring to?

**Comment by mdickinson** [comment]
Good point. I'd forgotten that we were specifying the EDM version in the Travis CI and Appveyor scripts (which no longer use EDM), and not in etstool.py. And we don't use the `--platform` argument anywhere in `etstool.py`. So I think there's nothing to do here.
