### ISSUE TITLE
Deprecate the `edit` argument to `configure_traits`

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1271]
With the `filename` argument to `configure_traits` deprecated, there's little value in allowing `edit=False` in a `configure_traits` call. We should deprecate the `edit` argument, too.

This is another small issue that could be done for the 6.2.0 milestone.

**Comment by avats-dev** [comment]
hey @mdickinson , I want to contribute. Can you guide me how to resolve this?

**Comment by mdickinson** [comment]
Hi @avats-dev. A contribution would be welcome! The simplest thing to do would be to look at the previous PR that deprecated the `filename` argument to `configure_traits`. You'll need to do something fairly similar here - issue a deprecation warning if `edit=False` is passed, and add a unit test that checks that that deprecation warning is raised.

The previous PR is here: https://github.com/enthought/traits/pull/792

**Comment by avats-dev** [comment]
Hey @mdickinson , what would be the warning message here?
In the `filename` argument, it was `'Restoring from pickle will not be supported starting with traits 7.0.0'`. So would it be same?

**Comment by mdickinson** [comment]
I'd go with something direct like `"The edit argument to configure_traits is deprecated, and will be removed in Traits 7.0.0."`. The docstring should also be updated with the appropriate Sphinx directive: `.. deprecated:: 6.2.0`.  For a usage example of that Sphinx directive, see [here](https://github.com/enthought/traits/blob/master/traits/traits.py#L658).

**Comment by avats-dev** [comment]
Thanks @mdickinson , I will update it like so. I'm done almost with this.

And also as most of the tests are for `filename` argument, I'm adding a single test just for testing if `edit=False`.

**Comment by mdickinson** [comment]
Great. Just a note: you may have to be a little bit patient waiting for review: I'm going to be away for the next couple of weeks. (One of the other ETS maintainers may pick this up, but they may also be busy with other things.)

**Comment by avats-dev** [comment]
Sure, no problem. :+1:
