### ISSUE TITLE
 traits/ctraits.c:24:10: fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by teld2016** [enthought/traits#1284]
Hi Experts,

I tried to install the traits in SUSE Linux Enterprise Server 15 SP1  (x86_64) via the command of : 
 `sudo pip3 install traits==5.2.0`
failed with the information like following:
```
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from traits==5.2.0) (1.11.0)
Building wheels for collected packages: traits
  Building wheel for traits (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2d7dibzh/traits/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2d7dibzh/traits/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-kumhgw7f
       cwd: /tmp/pip-install-2d7dibzh/traits/

....

 Running setup.py clean for traits
Failed to build traits
DEPRECATION: Could not build wheels for traits which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reportedsion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: traits
    Running setup.py install for traits ... error
...
traits/ctraits.c:24:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

I also tried higher version and it does not work, I searched with stackoverflow and tried the way like:
sudo pip3 install libpython3.8-dev  (also 3.5,3.6,3.7 not work)

but seems this also not work, could you help to provide suggestion? Thanks!

Kind Regards,
Radar

**Comment by rahulporuri** [comment]
@teld2016 i updated the issue description to add code formatting. I hope that's okay.

**Comment by rahulporuri** [comment]
@teld2016 I think you need to install python-devel in your SUSE system (using your system package manager, not pip)

**Comment by mdickinson** [comment]
The real solution here is that we should be providing wheels for Traits. But that's quite a big task and so far it's been hard to justify it as a priority given the limited time available for ETS development (and also given the fact that Enthought itself has no need of those wheels). See https://github.com/enthought/traits/issues/357.

**Comment by mdickinson** [comment]
@teld2016 Did installing the `python-devel` package solve your issue?

**Comment by mdickinson** [comment]
> Did installing the `python-devel` package solve your issue?

(Note that it may be called something else, like `python3-dev` or `python3-devel`. The names seem to vary from distribution to distribution.)

**Comment by mdickinson** [comment]
I'm going to close this issue: I don't think it's an issue with Traits itself, so unless more information is forthcoming there's no action to be taken here.
