### ISSUE TITLE
Docstring of trait_get is incomplete

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1297]
The `HasTraits.trait_get` method has four ways it can be used:

1. One argument is passed which is a list or tuple of strings that specifies the names of the traits to get.
2. The *args contain strings that specify the names of the traits to get.
3. The **kwargs contains metadata information used to find the traits to use provided no positional args are passed.
4. If no arguments are passed, all trait values are returned.

Only case 2 and 4 are documented in the docstring.

**Comment by rahulporuri** [comment]
@mdickinson i think this can be closed as #1465 got merged over #1453

**Comment by mdickinson** [comment]
Thanks, yes.
