### ISSUE TITLE
Update Python versions in Appveyor and Travis CI configurations

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1304]
We need to update the Python versions in our continuous integration configurations:

For Appveyor: add Python 3.9 when available
For Travis CI: change 3.9-dev to 3.9 when Python 3.9 is available

See also #1303, which updates the Python versions used for GitHub Actions.

**Comment by mdickinson** [comment]
Related upstream issue about supporting Python 3.9 on Appveyor: https://github.com/appveyor/ci/issues/3541

I was unable to find anything equivalent for Travis CI.

**Comment by mdickinson** [comment]
I edited the description to only mention the 3.9 changes; #1303 should fix the rest (dropping Python 3.5, adding Python 3.8 for Appveyor).

**Comment by hugovk** [comment]
This can be closed now?

**Comment by mdickinson** [comment]
Yes it can; thanks for the reminder!

Closing because we no longer make use of Travis CI or Appveyor; all continuous integration is run on GitHub Actions, and tests are run on versions up to and including 3.10-dev.
