### ISSUE TITLE
Properties slow down initialization significantly

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1316]
This may be more generally true of dynamic Trait listeners, but it is properties where I ran into it.  Consider a stripped down version of the new `Color` class from Pyface:
```
import colorsys
from random import uniform

from traits.api import (
    HasStrictTraits, Property, Range, Tuple, cached_property
)

#: A trait holding a single channel value.
Channel = Range(0.0, 1.0, value=1.0, channel=True)

#: A trait holding four channel values.
AlphaChannelTuple = Tuple(Channel, Channel, Channel, Channel)


class Color(HasStrictTraits):

    #: A tuple holding the red, green, blue, and alpha channels.
    rgba = AlphaChannelTuple()

    #: A tuple holding the hue, saturation, value, and alpha channels.
    hsva = Property(AlphaChannelTuple, depends_on='rgba')

    @cached_property
    def _get_hsva(self):
        r, g, b, a = self.rgba
        h, s, v = colorsys.rgb_to_hsv(r, g, b)
        return (h, s, v, a)
```

Creating these objects is very slow.  For example,
```
data = [Color() for i in range(100000)]
```
takes about 20 seconds to run, where if I remove the property trait (or the `depends_on`) it is effectively instantaneous.

Looking at basic profiling of the code

- significant amounts of time are spent parsing the trait name: despite it being effectively static and not using any complex features, the parsing algorithm is called twice for each instance (this appears to be deliberate, see https://github.com/enthought/traits/blob/c2018dc91f71ba1ed153f2dd7a26a6427c7e4c10/traits/has_traits.py#L701-L704)
- the fact that parts of the listener infrastructure are themselves `HasTraits` subclasses and, it appears, do themselves have (simple) listeners which in turn need to be connected also seems to be significant.
- there are some off places where unusual amounts of time seem to be being spent, such as `WeakIDDict` methods.

**Comment by mdickinson** [comment]
Tentatively assigning to the 6.2 milestone - from discussion, it looks as though there are some smallish changes that could be make that would potentially have a big impact.

**Comment by mdickinson** [comment]
@corranwebster Do you have more information on the `WeakIDDict` part? Which methods are taking the time?

**Comment by corranwebster** [comment]
I was seeing a lot of time in the `__init__` and `__setitem__` (cumulative time, rather than total time).  It may be that it is intrinsic and we can't do much about it.

It's also about 10% of the time, so possibly not worth bothering with if we aren't going to do anything about the parsing time.  Reducing from 20s to 18s isn't much of a win.

**Comment by kitchoi** [comment]
For anyone reading this and tempted to remove `depends_on` deemed redundant:

I personally find it useful to always define `depends_on` in Property. If I omit them, and later on if I need to build a GUI application that needs to react to changes (note that it could be chained!), it is often much harder to track down the missing "depends_on" to add them back. Those Property may not even be defined in a code base that I have control over to change.

**Comment by aaronayres35** [comment]
FWIW replacing `depends_on=` with `observe=` should provide a significant speed up.  Especially when the change made in #1344 is included.  For reference here is a subset of the output of the benchmarking script run on the branch for that PR with `n=100000`:

<details>

Given a subclass of HasTraits with a trait that is defined as Property
that depends on a simple trait, compare having the Property be defined
as `Property()`, `Property(depends_on="name")`, `Property(observe="name")`,
and `Property(observe=trait('name'))`. (Note that this is a feature
currently available on master only).

The timing we are interested in:
(1) Time to import the module, i.e. the class construction.
(2) Time to instantiate the HasTraits object.
(3) Time for changing the trait being depended-on / observed.

Times are reported as:
(#): absolute_time  relative_time_to_control
        
control -
(1): 14.50994   1.00 (2): 0.13294   1.00 (3): 0.00452   1.00
`depends_on='name'` -
(1): 14.42461   0.99 **(2): 6.18670  46.54** (3): 0.00623   1.38
`observe='name'` -
(1): 15.31489   1.06 **(2): 2.93529  22.08** (3): 0.00556   1.23
`observe=trait('name')` -
(1): 15.02808   1.04 (2): 2.90651  21.86 (3): 0.00618   1.37

--------------------------------------------------------------------------------

Identical to the simple property case only using the `@cached_property`
decorator on the property's getter method.

The timing we are interested in:
(1) Time to import the module, i.e. the class construction.
(2) Time to instantiate the HasTraits object.
(3) Time for changing the trait being depended-on / observed.

Times are reported as:
(#): absolute_time  relative_time_to_control
        
control -
(1): 14.41725   1.00 (2): 0.12930   1.00 (3): 0.00509   1.00
`depends_on='name'` -
(1): 14.60439   1.01 **(2): 12.38442  95.78** (3): 0.00686   1.35
`observe='name'` -
(1): 15.16266   1.05 **(2): 2.93375  22.69** (3): 0.00617   1.21
`observe=trait('name')` -
(1): 15.26573   1.06 (2): 2.85343  22.07 (3): 0.00622   1.22

--------------------------------------------------------------------------------

</details>

The times in bold are the times to instantiate the object when the property is defined with `depends_on='name'` vs `observe='name'`

**Comment by aaronayres35** [comment]
> FWIW replacing `depends_on=` with `observe=` should provide a significant speed up. Especially when the change made in #1344 is included. 

#1344 has been merged so I ran the example given in this issue description with both `depends_on=` and `observe=`.  When using `depends_on=` running `data = [Color() for i in range(100000)]` took 20.346 seconds, whereas with `observe=` the same code only took 5.321 seconds

**Comment by mdickinson** [comment]
Closing; this is largely solved.
