### ISSUE TITLE
Recursion support for observe?

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1339]
Currently `observe` does not support the recursive pattern `*` that is supported in `on_trait_change`.

This issue is open for discussion whether there are enough use cases to extend the recursion support to `observe`.

I found one potential use case, that would be for solving https://github.com/enthought/apptools/issues/194 where the notification machinery is reacting to changes to any traits on a subclass and the structure of the traits is not known by the base class.

An experimental implementation for the support can be found here: https://github.com/enthought/traits/pull/1242

**Comment by mdickinson** [comment]
Closing; we don't have good enough use-cases for now, and the recursion adds sufficient complexity that we don't want to do it without a really good reason.
