### ISSUE TITLE
Doc: Error in API docs for AdaptationManager adapt method

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traits#1354]
I noticed this on the `adapt` method of `AdaptationManager` but it is very possible there are similar issues scattered accross the api docs.  Basically what happens is comments in the docstring are getting recorded as parameters for the `adapt` method.  See screenshot below:
<img width="869" alt="Screen Shot 2020-11-16 at 3 06 25 PM" src="https://user-images.githubusercontent.com/36972686/99308445-95f5ab00-281d-11eb-8acc-aa44c0f2211a.png">
https://docs.enthought.com/traits/traits_api_reference/traits.adaptation.html#traits.adaptation.adaptation_manager.AdaptationManager

Code is here: https://github.com/enthought/traits/blob/3e7da1f2125ba9291bce747311f1220ef53e6ed6/traits/adaptation/adaptation_manager.py#L96-L117

We could probably just add a "Notes" section to the docstring to avoid this, although I am not certain.

**Comment by mdickinson** [comment]
Yep, we've seen and fixed this in a number of places, but there are likely a good few left. The usual fix is simply to move things around so that the `Parameters` section (and other templated sections, like `Results`) follow the rest of the comments.
