### ISSUE TITLE
Consider adding and exposing util functions for string removeprefix and removesuffix

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1368]
https://www.python.org/dev/peps/pep-0616/ introduces two new string methods `removeprefix` and `removesuffix`, which are available in python 3.9. These two methods make code of the form `trait_name = trait_name[:-6] if trait_name.endswith('_items') else trait_name` slightly more readable.

For example, if the `removesuffix` util function is defined as follows,

```
def removesuffix(string_, suffix):
    if sys.version_info[:2] >= (3, 9):
        return string_.removesuffix(suffix)
    else:
        if suffix and strring_.endswith(suffix):
            return string_[:-len(suffix)]
        else:
            return string_[:]
```

code of the form

```
 elif name[:-6] == "_fired": 
     short_name = name[n:-6] 
```

can be rewritten as 

```
elif name.endswith("_fired"):
    name = removesuffix(name, "_fired")
```

It might be useful if we added two utility functions `removeprefix` and `removesuffix` and exposed them to users of traits.

A few motivating examples : 

- [preferences_helper in apptools](https://github.com/enthought/apptools/blob/aed40a046ff668882d733283dcf1a7682a147e14/apptools/preferences/preferences_helper.py#L78-L81)
- https://github.com/enthought/traits/blob/82016ac085fa91af31fdb03d429a651bea5c1c80/traits/has_traits.py#L3181-L3182
- https://github.com/enthought/traits/blob/82016ac085fa91af31fdb03d429a651bea5c1c80/traits/has_traits.py#L2748

**Comment by mdickinson** [comment]
I'm a strong -1 on this: these functions have nothing particularly to do with Traits, and there's no good reason that users would think to look in Traits for this functionality. I'd really rather that Traits stay focused on things that are relevant to Traits.

If we _really_ care about this, we could create a `pep616` package and upload it to PyPI.

**Comment by mdickinson** [comment]
Related discussions:
- https://github.com/enthought/ets/issues/51
- https://github.com/enthought/traits/issues/1239
- https://github.com/enthought/traits/issues/1236

**Comment by rahulporuri** [comment]
makes sense. closing.
