### ISSUE TITLE
Errors on front page of user manual

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1373]
From an internal report:

> I noticed two errors on [this page](https://docs.enthought.com/traits/traits_user_manual/intro.html):
> - The two blue buttons at the top both say "user manual" but only the second links to the user manual.
> - At the end of the second paragraph, only the middle of the three bullet points is hyperlinked, and it points to the user manual for traitsui, not traits. It seems like that link should just be removed since linking to the user manual as an additional resource within the user manual itself is odd.

**Comment by mdickinson** [comment]
We already have a link to the TraitsUI manual in the section below (on visualization), so I agree that the second bullet point should be removed.

The cause of the first error may take some digging into the Sphinx theme.

**Comment by mdickinson** [comment]
@rahulporuri Could we add this issue (or at least the fixing the links part) to the next sprint? 

For the first issue (the blue buttons), if there's an easy fix we should apply it, but if the fix involves going into the Sphinx Theme, then let's open a separate issue for that and defer the fix.

**Comment by rahulporuri** [comment]
> @rahulporuri Could we add this issue (or at least the fixing the links part) to the next sprint?

SGTM. Note that the "next sprint" is essentially an extension of this sprint given christmas vacation.
