### ISSUE TITLE
Fiddling with HasStrictTraits member function makes it vanish

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traits#1375]
Assigning to a method on a HasStrictTraits class initially fails with TraitError. After the assignment fails, the method vanishes and raises AttributeError whenever it is accessed. Example:

```python
from traits.api import *

class Foo(HasStrictTraits):
    def func(self):
        print('hello')

foo = Foo()
foo.func()
# => 'hello'

try:
    foo.func = 'something different'
except TraitError:
    # TraitError: Cannot set the undefined 'func' attribute of a 'Foo' object.
    pass

# func has now vanished!
foo.func
# => AttributeError: 'Foo' object has no attribute 'func'
```

This situation arose more naturally when attempting to do run-time decoration of the method, e.g., doing `foo.func = some_decorator(foo.func)`.

**Comment by mdickinson** [comment]
Thanks for the report; this indeed looks like something that shouldn't be happening, but it may also be nontrivial to fix - we may have to rely on "don't do that" documentation. (I'm half remembering that there was a similar report somewhere about peculiar behaviour after a failed Traits assignment; I'll look for it.)

**Comment by mdickinson** [comment]
> I'm half remembering that there was a similar report somewhere about peculiar behaviour after a failed Traits assignment

Not just similar: it's the same issue: https://github.com/enthought/traits/issues/58

I'll close this one as a duplicate.

@notmatthancock Do you have a usable workaround for this for now?

**Comment by notmatthancock** [comment]
> @notmatthancock Do you have a usable workaround for this for now?

Usable? Yes. Something I would admit to doing without feeling a bit of shame? Not as much :grimacing:

**Comment by mdickinson** [comment]
> Something I would admit to doing without feeling a bit of shame? Not as much 😬

Understood; thanks.
