### ISSUE TITLE
Documentation build is failing

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1377]
The documentation build is currently failing, probably due to a change in upstream Sphinx.

If this turns out to be a bug in Sphinx, it wouldn't be the first time that Sphinx issues have caused problems with other PRs. I think we should pin the Sphinx version used for PR builds (though we may also want a cron job that builds with the latest Sphinx, so that we get alerted to potential failures early).

We should also investigate the cause (as far as we're able) and report a bug upstream if necessary.

Setting priority to blocking, since this is currently blocking all other PRs.

**Comment by mdickinson** [comment]
This is not a bug in Sphinx; it's a bug in our doc, specifically this line:
```
./source/traits_api_reference/trait_type.rst:
   10 : .. autoclass:: NoDefaultSpecified
```

`NoDefaultSpecified` is not a class, so naturally the class documenter has difficulty finding its name.

**Comment by kitchoi** [comment]
Agreed this does not seem like a bug in Sphinx.
