### ISSUE TITLE
Either fix up Method trait type or deprecate it

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traits#1398]
Issue is motivated by this https://github.com/enthought/traits/issues/1215#issuecomment-645967493

In #1397 the `Function` trait type was deprecated.  We may want to deprecate `Method` along with it, or as the above comment mentions, rework it to be more duck-typed

**Comment by mdickinson** [comment]
I found zero uses of the `Method` trait type in a fairly extensive code search of the code available to me. I think we should deprecate, and since we've already deprecated `Function`, it would make sense to deprecate `Method` for the 6.2.0 release.

**Comment by aaronayres35** [comment]
> I found zero uses of the `Method` trait type in a fairly extensive code search of the code available to me. I think we should deprecate, and since we've already deprecated `Function`, it would make sense to deprecate `Method` for the 6.2.0 release.

SGTM, I will open a PR
