### ISSUE TITLE
What should be the type of a shallow copy of a TraitsDictObject?

### ISSUE THREAD

**Issue by jdmarch** [enthought/traits#14]
See Issue #10, PR #11

(@corranwebster wrote: "should shallow copying a TraitsDictObject return a dict or a TraitsDictObject? I can see arguments both ways, and I have no idea what it might break to modify the behaviour.")

**Comment by mdickinson** [comment]
This is a very old issue, but it's worth noting that we have a consistent answer these days: copying a `TraitListObject`, or a `TraitDictObject`, or a `TraitSetObject` via `copy.copy()` gives back another object of the same type.

However, invoking the `copy` method on any one of these objects gives back a plain old Python `list`, `dict` or `set`.

It's been this way for a while, and seems to be working okay. Closing this issue.

Related: #97, #98.
