### ISSUE TITLE
Add cron job tests for PyPI wheel-based installs

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1407]
PR #1406 adds a workflow to regularly test PyPI installs from sdist.

As soon as 6.2.0 is released and we have wheels on PyPI, we should augment that workflow to also test PyPI installs from wheels. The simplest way to do that is likely to duplicate the existing job from #1406 and then ensure that the `pip install` step only allows binary installs.

See also enthought/ibm2ieee#23, where this is already implemented.

**Comment by mdickinson** [comment]
This was done in #1417.

**Comment by rahulporuri** [comment]
ha. i was just about to.
