### ISSUE TITLE
Introductory Tutorial CSS not copied

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1418]
The introductory tutorial at one point had CSS supplied for it to make the appearance better.  It looks like this was not moved across when it was moved to the examples directory (and/or not configured correctly once there).  This means that the default Docutils style is used.

As a result code snippets are oddly styled:

![image](https://user-images.githubusercontent.com/600761/105372670-bff09280-5bfd-11eb-9ab1-1981f7635854.png)

It's possible that there may be some part of this which is an issue with TraitsUI etsdemo code, but at a minimum it looks like the CSS is missing from the examples directory.

**Comment by mdickinson** [comment]
@corranwebster: Just to be clear, this is an issue only with the appearance in the etsdemo app, right? Not with the version of the tutorial in the docs at docs.enthought.com/traits?

**Comment by mdickinson** [comment]
Related: https://github.com/enthought/traits/pull/1374#pullrequestreview-560951496
