### ISSUE TITLE
Warn if "observe" decorator applied to method with only "self"

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1428]
With the new 'observe' decorator, there's a potentially late-discovered bug that I've seen now in multiple different projects, and that's to forget to add the "event" argument on a previously argument-less `on_trait_change` target.

It may be worth warning if the target of the "observe" decorator does not have exactly one positional argument in addition to "self".

**Comment by kitchoi** [comment]
One thing to watch out is that the inspection on callable arguments adds limitations on what kind of callables can be used.
The fact that `on_trait_change` does signature inspection means a whole bunch of callables cannot be used:
```
>>> from traits.api import *
>>> class Foo(HasStrictTraits):
...     name = Str()
... 
>>> foo = Foo()
>>> events = []
>>> foo.on_trait_change(events.append, "name")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/traits/has_traits.py", line 2557, in on_trait_change
    self._on_trait_change(
  File "/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/traits/has_traits.py", line 2249, in _on_trait_change
    wrapper = self.wrappers[dispatch](handler, notifiers, target)
  File "/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/traits/trait_notifiers.py", line 412, in __init__
    self.init(handler, owner, target)
  File "/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/traits/trait_notifiers.py", line 447, in init
    arg_count = handler.__code__.co_argcount
AttributeError: 'builtin_function_or_method' object has no attribute '__code__'
```

Currently this works:
```
>>> foo.observe(events.append, "name")
>>> foo.observe(print, "name")
```

Calling `inspect.signature` on certain built-in functions will also fail. If one detects if a function is an instance method first then subsequent signature inspection should be okay.

**Comment by mdickinson** [comment]
Yes: I think it would be a warning, not an error, and we'd only issue the warning in the case that we could inspect the code - if we couldn't inspect the code we'd just let it pass.

**Comment by mdickinson** [comment]
Having implemented a solution, I'm having second thoughts about this; it's a bit inefficient to be doing runtime type-checking for this. A static type-check may be a better solution. If we get the signature of `observe` right, presumably mypy could do such a static check for us.

**Comment by mdickinson** [comment]
Third thoughts: I think this is fine for the `observe` decorator factory, which is where I've seen the issue most often, but would hesitate to extend the check to uses of the `observe` method. PR #1529 only solves this for the decorator.
