### ISSUE TITLE
The validation error message for a non-existing file doesn't mention that the file does not exist

### ISSUE THREAD

**Issue by nicolasap-dm** [enthought/traits#1439]
Running:
```python
from traits.api import HasTraits, File

class Foo(HasTraits):
    file_trait = File(exists=True)

Foo(file_trait="~/tmp/does_not_exist.txt")
```

raises the following:
```
traits.trait_errors.TraitError: The 'file_trait' trait of a Foo instance must be a filename
or object implementing the os.PathLike interface, but a value of '~/tmp/does_not_exist.txt'
<class 'str'> was specified.
```

while one would argue that "~/tmp/does_not_exist.txt" is indeed path-like, even if it's not existing.

A failed existence check should probably raise with a different error message, one with a "does not exist" kind of wording.

**Comment by mdickinson** [comment]
The error message is mostly automatically constructed by the Traits machinery, so the only bit we can _easily_ change is the "a filename
or object implementing the os.PathLike interface" phrase. Code link: https://github.com/enthought/traits/blob/8ec7fb793278c4706fe34d9096baa56e106f7dc2/traits/trait_types.py#L1364

In the case `exists=True`, we could modify that phrase to "a string or os.PathLike object giving the path to an existing file", or some such. Thoughts?

**Comment by mdickinson** [comment]
"a string or os.PathLike object pointing to an existing file"? And just "a string or os.PathLike object" for the case `exists=False`?

**Comment by mdickinson** [comment]
We'd want to update the text for the `Directory` trait at the same time: https://github.com/enthought/traits/blob/8ec7fb793278c4706fe34d9096baa56e106f7dc2/traits/trait_types.py#L1502-L1503

**Comment by nicolasap-dm** [comment]
The solution you propose sounds good to me.
