### ISSUE TITLE
Document Date, Datetime and Time traits in the "Predefined traits" section of the user manual

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1445]
These are commonly-used traits, which should be documented. The `allow_datetime` flag to `Date`, and the `allow_none` flags to all three trait types, are worthy of mention.

**Comment by rahulporuri** [comment]
@mdickinson was anything else needed to close this issue?

**Comment by mdickinson** [comment]
@rahulporuri When I wrote the issue, I was thinking that it would be nice to have a more detailed explanation of `allow_none`, `allow_datetime`, etc., in the user manual. But it may be that the existing docstrings for the trait types are enough here.
