### ISSUE TITLE
Consider deprecating and removing clean_filename

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1447]
The python package https://github.com/un33k/python-slugify provides almost the same functionality - except for the default return value.

https://github.com/enthought/traits/blob/6e924d2189d2c2f22b0e8b8b961ce2597f586671/traits/util/clean_strings.py#L23-L62

**Comment by corranwebster** [comment]
I'd be curious where this is used in the ETS codebase (I have a sneaking suspicion it may be in Pyface/TraitsUI state serialization code).

**Comment by mdickinson** [comment]
See also #589

**Comment by mdickinson** [comment]
> I have a sneaking suspicion it may be in Pyface/TraitsUI state serialization code

Hmm; without having looked at details, that doesn't sound like a good thing. You'd want serialization code to provide some kind of guarantee of round-tripping, while `clean_filename` is explicitly _not_ faithful, so can convert different inputs into the same output.

**Comment by mdickinson** [comment]
> I'd be curious where this is used in the ETS codebase

After a quick check: it's not used anywhere. It used to be used in Envisage, but that was fixed in enthought/envisage#252.
