### ISSUE TITLE
Directory Trait should have different error when failing because exists=True

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traits#1448]
motivated by issue: https://github.com/enthought/traitsui/issues/1154

~This default does not create an error when `exists!=True`, so ideally the resulting error would be more specific about the directory not existing.~
EDIT: this seems to already bee fixed... 🤦 
When I run the example locally I get a more detailed error message than the one shown in the issue thanks to:
https://github.com/enthought/traits/blob/5f2effc0254570dfa7736d8bf53eb224c9877c57/traits/trait_types.py#L1538-L1539
closing this issue now

**Comment by aaronayres35** [comment]
@mdickinson what are your thoughts on this / the corresponding traitsUI issue?

The traitsUI issue also reminds me of https://github.com/enthought/traitsui/issues/1502 in that we have a case where we want to add some new object, but the defaults for that object don't work right.  My thought was that it may be useful to add a means to specify a callable that will return the new item you want in the list (if your prefer/need something different than what ever the default would be).  This was done in https://github.com/enthought/traitsui/pull/1527 for 1502

This traits issue feels separate to that in that adding a new Directory to the list shouldn't fail as it currently does because it is potentially misleading.

Perhaps traitsUI should catch such a TraitError coming from traits as well and do something else besides crashing the app entirely, eg issue a warning dialog saying you cant do that or something

**Comment by mdickinson** [comment]
Thanks, @aaronayres35. Yes, this looks like a duplicate of #1439, which was fixed in #1440.
