### ISSUE TITLE
Rename the default branch to "main"

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1466]
Around the time of the next major release of Traits (Traits 7.0), I'd like to rename the default development branch from "master" to "main". GitHub takes care of all the details here (re-targeting PRs and branch protections, for example). This change should be invisible to users of Traits, and minimally disruptive to developers; the only likely change needed on the developer side will be to check out the "main" branch locally, and adjust the tracking of upstream branches. We can give detailed instructions when the time comes.

**Comment by rahulporuri** [comment]
I'd like this to happen across ETS at the same time - and I'm not sure when Traits 7.0.0 is planned but I was hoping this switch could happen EoY 2021. It's not necessary that all of the projects make this switch at the same time though - it would reduce the cognitive overhead slightly though.

**Comment by mdickinson** [comment]
> I'd like this to happen across ETS at the same time

Makes sense; I don't think there's any particular advantage or disadvantage to doing it sooner rather than later (for Traits in particular). We'll need to notify IT of the changes, and more generally notify ETS users, and it'll be easier to do both those things if we transition all the repositories at the same time.

**Comment by mdickinson** [comment]
@rahulporuri Should we open an issue in the enthought/ets repo for this, and close this one?

**Comment by rahulporuri** [comment]
Sorry for the extremely delayed response.

> We'll need to notify IT of the changes, and more generally notify ETS users, and it'll be easier to do both those things if we transition all the repositories at the same time.

I'll ask IT regarding the process of changing the default branch from `master` to `main` and once we have an answer, we can confirm the timeline for the change and notify ETS users.

> @rahulporuri Should we open an issue in the enthought/ets repo for this, and close this one?

We can just transfer the issue instead.

**Comment by mdickinson** [comment]
This is done.
