### ISSUE TITLE
Can we remove the "Migration Guide" in the Traits Adaptation docs section?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1482]
Ref https://docs.enthought.com/traits/traits_user_manual/advanced.html#migration-guide

> The adaptation features of Traits have been rewritten in v. 4.4.0 . See the migration guide below for details regarding changes in API.

It's been a while and `traits.protocols` that Traits Adaptation used to rely on doesn't exist anymore. Should we remove the "Migration Guide" now or is it still relevant/important?

**Comment by mdickinson** [comment]
There's still a lot of old Traits code out there; unless what's presented in the guide is no longer accurate, I think we should leave it in.

**Comment by rahulporuri** [comment]
closing as the guide still looks accurate
