### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [enthought/traits#1484]
Problem
---------
On aarch64, pip install traits builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install traits should download the wheels from pypi

@mdickinson , Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by mdickinson** [comment]
Thanks for the issue and the PR! We'll need to think about this a bit - none of the ETS maintenance team currently has easy access to aarch64 for testing or debugging purposes, so it's going to be difficult to commit to supporting aarch64. I guess we could add a disclaimer in the documentation that these wheels are built without any guarantees, and that if there are problems then you're on your own.

**Comment by mdickinson** [comment]
Related: The GitHub Actions setup-python action also unfortunately doesn't support ARM, and apparently has no plans to do so (https://github.com/actions/setup-python/issues/108). So even automated testing looks awkward.

**Comment by mdickinson** [comment]
@odidev Do you have any thoughts about how we might do automated testing (preferably using GitHub Actions) of Traits on Linux/aarch64?

**Comment by mdickinson** [comment]
#1567 included aarch64 builds.
