### ISSUE TITLE
Advanced property documentation references traits.adaptation.api.Property

### ISSUE THREAD

**Issue by sjagoe** [enthought/traits#149]
See [Property Factory Function](http://docs.enthought.com/traits/traits_user_manual/advanced.html#property-factory-function) in the documentation.

The `Adaptation` section before this sets `.. currentmodule:: traits.adaptation.api` ([L666](https://github.com/enthought/traits/blame/master/docs/source/traits_user_manual/advanced.rst#L666)) and does not reset it to `traits.has_traits`, as it was before ([L438](https://github.com/enthought/traits/blame/master/docs/source/traits_user_manual/advanced.rst#L438)).

**Comment by mdickinson** [comment]
Random bug of the day; this should be either an easy fix, or out of date.

**Comment by mdickinson** [comment]
Still an issue. Here's a permalink (the links in the original post are out of date): https://github.com/enthought/traits/blame/24c4d76d688f8a86f83dd80b6ffd7a1226b27ebc/docs/source/traits_user_manual/advanced.rst#L715
