### ISSUE TITLE
"AttributeError" when accessing a "view" trait defined on a "HasTraits" class

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1584]
```
from traits.api import HasTraits, Int
from traitsui.api import View


class A(HasTraits):
    b = Int(1)
    view = View("b")
```

For the simple `HasTraits` class seen above, doing `A.view` or  `A().view` raises an `AttributeError` - 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute 'view'
```

It's not exactly clear to us why accessing the `view` trait raises an `AttributeError`.

**Comment by mdickinson** [comment]
Here's the relevant line of code: https://github.com/enthought/traits/blob/bc366e87105866682ef63715ee0faf2d3014cfec/traits/has_traits.py#L574

**Comment by mdickinson** [comment]
Thanks, @rkern. That kills the rationale for killing this issue.

Does anyone have a strong opinion on fixing this, one way or the other? I personally don't: both the benefits and the risks of making the change seem small.

**Comment by rkern** [comment]
The use-case that was communicated off-line (listening to modifications of `View` instances) isn't something that I think we want to support, so I would probably leave it alone.
