### ISSUE TITLE
Nitpicky issue : Code in documentation refers to SVN

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1639]
For example, in https://docs.enthought.com/traits/traits_user_manual/custom.html#traitprefixlist, the exception contains mention of svn. It would be nice to update the examples to show the latest exception information. Additionally, the code isn't highlighted like other pieces of Python code.

**Comment by mdickinson** [comment]
Hmm. No-one should be using `TraitPrefixList` or `TraitPrefixMap` by this point; we'll be removing these docs for Traits 7.0 anyway. It may not be worth doing too much with them before then.

I've opened #1702 to make it clear in the 6.4 documentation that `TraitPrefixList` and `TraitPrefixMap` are deprecated, and #1703 to remove them from the main branch.
