### ISSUE TITLE
"Time" trait type doesn't allow "datetime.timedelta" values

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1642]
`datetime.time` and `datetime.timedelta` are two distinct objects in Python so it's understandable that the `Time` trait type doesn't allow `datetime.timedelta` values. It would be nice to have a trait that allows `datetime.timedelta` values.

**Comment by mdickinson** [comment]
Yes, we definitely don't want `Time` to accept timedeltas.

What would a timedelta trait bring that isn't already possible with `Instance(datetime.timedelta)`?

**Comment by rahulporuri** [comment]
> What would a timedelta trait bring that isn't already possible with `Instance(datetime.timedelta)`?

Not sure.

Looking at the `Time` and `Datetime` traits, they enable easy access to the respective TraitsUI editors. I don't know how useful a `Timedelta` trait would be with a corresponding TraitsUI editor.

**Comment by mdickinson** [comment]
Right; I'm not keen on adding new trait types for built-in types just because - I think `Instance` is good enough here. If we have a real need for a custom timedelta editor, that would be different. (Though I suspect that a `TextEditor` would likely be good enough for most needs.)

**Comment by rahulporuri** [comment]
@mdickinson I think we can close this issue given the discussion.
