### ISSUE TITLE
Default value overrides in subclasses broken for non-constant values

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1644]
Consider the following example:
``` python
In [24]: from traits.api import HasTraits, List
In [25]: class A(HasTraits):
    ...:     l = List([1, 2, 3])
    ...: 
In [26]: class B(A):
    ...:     l = [4, 5, 6]
    ...: 
In [27]: b = B()
In [29]: b.l
Out[29]: [4, 5, 6]
In [30]: b2 = B()
In [31]: b2.l
Out[31]: [4, 5, 6]
In [32]: b2.l.append(7)
In [33]: b2.l
Out[33]: [4, 5, 6, 7]
In [34]: b.l
Out[34]: [4, 5, 6, 7]
In [35]: type(b.l)
Out[35]: list
```
Things which are wrong:
- the new default value in the subclass is shared between instances of the class
- it is not a traits list object, so observers probably won't work properly

You get similar issues with any trait which has a non-standard default value type (this was first observed with the new `KivaFont` trait: https://github.com/enthought/enable/issues/945).

The code which is at fault looks to be this: https://github.com/enthought/traits/blob/576b6b04a828080f034d191e2cf9e6d0ed8498e1/traits/has_traits.py#L593-L599

This is not correctly allowing for other trait default value types (there seems no reason that it couldn't work by simply leaving things alone except in the case of `setattr_original_value`).

**Comment by mdickinson** [comment]
I think this is mostly a duplicate of #1630.

**Comment by corranwebster** [comment]
Yes, https://github.com/enthought/enable/issues/945 is a slightly different twist on it, but it's the same root cause.

**Comment by corranwebster** [comment]
Closing in favour of #1630
