### ISSUE TITLE
"Array" is missing from "traits-stubs"

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1657]
`traits.api.Array` is missing from `traits-stubs`. Ref https://github.com/enthought/traits/blob/0b64767e157d811bd23c2fc2ba7adfc2e8bc4c69/traits-stubs/traits-stubs/api.pyi

**Comment by mdickinson** [comment]
I'm not sure how to manage the NumPy dependency in the stubs file; this will likely require some investigation.
