### ISSUE TITLE
Should we remove documentation about "Trait" function from user manual?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1664]
Ref https://docs.enthought.com/traits/traits_user_manual/custom.html#the-trait-factory-function

The "Custom Traits" page of the Traits User Manual currently contains documentation around how to use the `Trait` factory function to define custom traits. Given that we are quietly recommending people against using the `Trait` factory function, should this section of the documentation be removed?

There are additional parts of the page that we might also want to remove but that's a separate issue.

**Comment by mdickinson** [comment]
I think we should keep the documentation while `Trait` is still in use. What we can do is add a prominent warning at the top of the documentation advising that `Trait` should not be used in new code.

See also #1610: `Either` should get similar treatment.
