### ISSUE TITLE
"traits.etsconfig" API documentation can be improved

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#1667]
At the moment, there is a lot of meaningful information on the object that isn't available in the API documentation for https://docs.enthought.com/traits/traits_api_reference/traits.etsconfig.html

Note: It took me a minute to remember that we're manually curating the API documentation so this is where we need to make changes - https://github.com/enthought/traits/blob/66b57b7c1f2127fc070fa943773c840f5f44a9ca/docs/source/traits_api_reference/traits.etsconfig.rst

**Comment by mdickinson** [comment]
Fixed in #1688.
