### ISSUE TITLE
Envisage and Apptools cron jobs failing to build traits

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1721]
In both cases we are getting the following error:
```
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O2 -fPIC -I/home/vagrant/workspace/Buildsystem/python/runtime/core/include/python3.8 -c traits/ctraits.c -o build/temp.linux-x86_64-cpython-38/traits/ctraits.o
  traits/ctraits.c:15:10: fatal error: Python.h: No such file or directory
     15 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for traits
ERROR: Could not build wheels for traits, which is required to install pyproject.toml-based projects
Command '['/home/runner/edm/bin/edm', 'run', '-e', 'envisage-test-3.8-null', '--', 'python', '-m', 'pip', 'install', '--force-reinstall', 'git+http://github.com/enthought/traits.git#egg=traits']' returned non-zero exit status 1.
```

Failures [here](https://github.com/enthought/apptools/actions/runs/2930500430) and [here](https://github.com/enthought/envisage/actions/runs/2930457586).

**Comment by mdickinson** [comment]
This looks like an issue with the latest EDM runtimes: note that rather odd include path (`-I/home/vagrant/workspace/Buildsystem/python/runtime/core/include/python3.8`). It's affecting other packages with a C extension, too.

I can also reproduce the issue locally on macOS.

**Comment by mdickinson** [comment]
Issues confirmed with `ibm2ieee` and (just for good measure) with `pyrsistent`. I'll close here and open a buildsystem issue.
