### ISSUE TITLE
Unexpected failure mode for `dispatch="ui"` when there is no UI

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1732]
When using `dispatch="ui"` and there is no UI (in particular, Pyface has not done toolkit selection), the dispatcher fails with an attempt to call `None` as the handler:
``` python console
>>> from traits.api import HasTraits, Int, observe
>>> class Test(HasTraits):
...    x = Int()
... 
>>> t = Test()
>>> def handler(event):
...     print(event)
... 
>>> t.observe(handler, 'x', dispatch='ui')
>>> t.x = 1 
Exception occurred in traits notification handler for event object: TraitChangeEvent(object=<__main__.Test object at 0x10de8a270>, name='x', old=0, new=1)
Traceback (most recent call last):
  File "/Users/cwebster/.edm/envs/enclosure-38/lib/python3.8/site-packages/traits/observation/_trait_event_notifier.py", line 122, in __call__
    self.dispatcher(handler, event)
  File "/Users/cwebster/.edm/envs/enclosure-38/lib/python3.8/site-packages/traits/trait_notifiers.py", line 50, in ui_dispatch
    ui_handler(handler, *args, **kw)
TypeError: 'NoneType' object is not callable
```

This also happens when the Pyface toolkit is `null` (which may be a Pyface bug):
``` python console
>>> from traits.etsconfig.api import ETSConfig
>>> ETSConfig.toolkit = 'null'
>>> import pyface.api
>>> t.x = 2     
Exception occurred in traits notification handler for event object: TraitChangeEvent(object=<__main__.Test object at 0x10de8a270>, name='x', old=1, new=2)
Traceback (most recent call last):
  File "/Users/cwebster/.edm/envs/enclosure-38/lib/python3.8/site-packages/traits/observation/_trait_event_notifier.py", line 122, in __call__
    self.dispatcher(handler, event)
  File "/Users/cwebster/.edm/envs/enclosure-38/lib/python3.8/site-packages/traits/trait_notifiers.py", line 50, in ui_dispatch
    ui_handler(handler, *args, **kw)
TypeError: 'NoneType' object is not callable
```

I'm not entirely sure what the correct behaviour is here.

I think I would expect dispatch to work if the current thread is the main thread, given the short-circuit in the code here: https://github.com/enthought/traits/blob/92ecd7e85ca399f8d4bc798d5d7071804fa5c0fb/traits/trait_notifiers.py#L46-L50

But given there is no way to dispatch something back to the main thread if there is no event loop around, I'd expect at least a better failure message if the dispatch is not on the main thread.

**Comment by corranwebster** [comment]
Presumably there is a similar issue with `on_trait_change`-based dispatch: https://github.com/enthought/traits/blob/92ecd7e85ca399f8d4bc798d5d7071804fa5c0fb/traits/trait_notifiers.py#L617-L621

**Comment by mdickinson** [comment]
Drive-by note: `threading.current_thread() == threading.main_thread()` would be a better test here.

Agreed that there should be a clear failure message if we're not on the main thread and there's no ui. And yes, I _suppose_ we should just ignore `dispatch="ui"` and execute the handler directly if we're on the main thread. I'm not sure that that's what I'd choose if we were implementing this for the first time, but we're not. (Having an observer that _sometimes_ executes synchronously and sometimes asynchronously sounds a bit like a recipe for confusion.)

**Comment by homosapien-lcy** [comment]
Hi, I think the second exception may have already been solved by the latest pyface:

(py311) (base) cyliu@aus552cyliu traits % python3.11
Python 3.11.2 (main, Feb 16 2023, 03:15:23) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from traits.api import HasTraits, Int, observe
>>> class Test(HasTraits):
...     x = Int()
... 
>>> t = Test()
>>> from traits.etsconfig.api import ETSConfig
>>> ETSConfig.toolkit = 'null'
>>> import pyface.api
>>> t.x = 2     
>>> 
>>> 

But the first error remains:
Python 3.11.2 (main, Feb 16 2023, 03:15:23) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from traits.api import HasTraits, Int, observe
>>> class Test(HasTraits):
...     x = Int()
... 
>>> t = Test()
>>> from traits.etsconfig.api import ETSConfig
>>> ETSConfig.toolkit = 'null'
>>> import pyface.api
>>> t.x = 2     
>>> 
>>> def handler(event):
...     print(event)
... 
>>> t.observe(handler, 'x', dispatch='ui')
>>> t.x = 1 
Exception occurred in traits notification handler for event object: TraitChangeEvent(object=<__main__.Test object at 0x1015a8590>, name='x', old=2, new=1)
Traceback (most recent call last):
  File "/Users/cyliu/Documents/3.11_test/traits/traits/observation/_trait_event_notifier.py", line 122, in __call__
    self.dispatcher(handler, event)
  File "/Users/cyliu/Documents/3.11_test/traits/traits/trait_notifiers.py", line 50, in ui_dispatch
    ui_handler(handler, *args, **kw)
TypeError: 'NoneType' object is not callable

Environment: Python3.11, MacOS
Packages:
Package            Version       Editable project location
------------------ ------------- ---------------------------------------
attrdict           2.0.1
attrdict3          2.0.2
chaco              5.1.0         /Users/cyliu/Documents/3.11_test/chaco
configobj          5.0.8
enable             5.4.0.dev28   /Users/cyliu/Documents/3.11_test/enable
fonttools          4.39.2
joblib             1.2.0
numpy              1.24.2
pandas             1.5.3
Pillow             9.4.0
pip                22.3.1
PyAudio            0.2.13
pyface             8.0.0
pygarrayimage      1.0
pyglet             2.0.5         /Users/cyliu/Documents/3.11_test/pyglet
Pygments           2.14.0
pyparsing          3.0.9
PySide6            6.4.3
PySide6-Addons     6.4.3
PySide6-Essentials 6.4.3
python-dateutil    2.8.2
pytz               2023.2
reportlab          3.6.12
scikit-learn       1.2.2
scipy              1.10.1
setuptools         65.6.3
shiboken6          6.4.3
six                1.16.0
threadpoolctl      3.1.0
traits             7.0.0.dev1840 /Users/cyliu/Documents/3.11_test/traits
traitsui           7.4.3
wxPython           4.2.0

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: pip install --upgrade pip

**Comment by homosapien-lcy** [comment]
After some testing, I found the first error from Corran will resolve if the main thread check in the ui_dispatch is changed to the following:

```
def ui_dispatch(handler, *args, **kw):
    if threading.current_thread().ident == threading.main_thread().ident:
        handler(*args, **kw)
    else:
        ui_handler(handler, *args, **kw)
```

Then the code will run successfully:

```
Python 3.11.2 (main, Feb 16 2023, 03:15:23) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from traits.api import HasTraits, Int, observe
^[[A
>>> 
>>> 
>>> class Test(HasTraits):
...     x = Int()
... 
>>> t = Test()
>>> def handler(event):
...     print(event)
... 
>>> t.observe(handler, 'x', dispatch='ui')
>>> t.x = 1 
TraitChangeEvent(object=<__main__.Test object at 0x104ec0720>, name='x', old=0, new=1)
```

So is the dispatch supposed to run when there is no ui but on the main thread?

**Comment by mdickinson** [comment]
> So is the dispatch supposed to run when there is no ui but on the main thread?

Yes, I think that's probably the right behaviour here.

**Comment by homosapien-lcy** [comment]
> > So is the dispatch supposed to run when there is no ui but on the main thread?
> 
> Yes, I think that's probably the right behaviour here.

OK, I will create a PR for this change then
