### ISSUE TITLE
`sre_parse` and `sre_constants` modules are deprecated

### ISSUE THREAD

**Issue by jwodder** [enthought/traits#1739]
`traits` makes use of the `sre_parse` and `sre_constants` modules [here](https://github.com/enthought/traits/blob/6ebef9089467495cdb8ab24c4991374be1d582e2/traits/observation/_generated_parser.py#L258-L264); however, these modules are deprecated, and a deprecation warning is emitted when they are imported.  They should be replaced with something more up-to-date.

**Comment by mdickinson** [comment]
Thanks for the report. It looks as though regenerating the parse with the latest version of Lark should address this. (Upstream PR: https://github.com/lark-parser/lark/pull/1140)

**Comment by mdickinson** [comment]
The parser was updated in #1743; I've double checked that `python -Wd -c "import traits.api"` reproduces the `DeprecationWarning`s on my machine on Python 3.11, and that those warnings are now gone on main.
