### ISSUE TITLE
`assertTraitChanges` reports chained property events in reverse order

### ISSUE THREAD

**Issue by itziakos** [enthought/traits#212]
The following example demonstrates the problem. Please note that the calculation takes place correctly

```python
from traits.api import Int, HasStrictTraits, Property
from traits.testing.unittest_tools import unittest, UnittestTools


class MyClass(HasStrictTraits):

    value = Int
    
    new_value = Property(Int, depends_on='value')
    
    new_new_value = Property(Int, depends_on='new_value')
    
    def _get_new_value(self):
        print 'I was called first'
        return self.value + 10

    def _get_new_new_value(self):
        print 'I was called second' 
        return self.new_value + 10
        
    
class TestMyClass(unittest.TestCase, UnittestTools):

    
    def test_my_class(self):
    
        my_class = MyClass()
        
        traits = 'new_value,new_new_value'
        with self.assertTraitChanges(my_class, traits, count=2) as collected:
            my_class.value = 5
        names = [event[1] for event in collected.events]
        # this will fail with names having the reverse order.
        self.assertEqual(names, ['new_value', 'new_new_value'])


if __name__ == '__main__':
    unittest.main()
```

**Comment by mdickinson** [comment]
For the record, here's the output with current Traits master, under Python 2.7:

```
I was called first
I was called second
I was called first
F
======================================================================
FAIL: test_my_class (__main__.TestMyClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "traits_bug_212.py", line 34, in test_my_class
    self.assertEqual(names, ['new_value', 'new_new_value'])
AssertionError: Lists differ: ['new_new_value', 'new_value'] != ['new_value', 'new_new_value']

First differing element 0:
new_new_value
new_value

- ['new_new_value', 'new_value']
+ ['new_value', 'new_new_value']

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (failures=1)
```

**Comment by mdickinson** [comment]
@itziakos: Why do you consider this a bug?  I don't think we make guarantees about the orders of firing of Traits listeners.

Interestingly, if we add the following method, the order of the events depends on dictionary ordering:

```
    @on_trait_change('new_value,new_new_value')
    def _one_or_other_changed(self, obj, name, old, new):
        print obj, name, old, new
```

With the above, I see one or the other of the following results, depending on the hash seed used for dictionary ordering.  Result 1:

```
I was called first
I was called second
I was called first
<__main__.MyClass object at 0x109676d10> new_new_value None 25
<__main__.MyClass object at 0x109676d10> new_value None 15
```

Result 2:

```
I was called first
<__main__.MyClass object at 0x107363d10> new_value None 15
I was called second
I was called first
<__main__.MyClass object at 0x107363d10> new_new_value None 25
```

**Comment by mdickinson** [comment]
I suggest closing this as not-a-bug.

**Comment by itziakos** [comment]
>  Why do you consider this a bug? I don't think we make guarantees about the orders of firing of Traits listeners.

I am considering this a **bug** in the `assertTraitChanges` not in the trait listeners. I would expect that the assert method will report trait changes in the order they where fired by the traits listener machinery.  The solution would be to use the trait change recording mechanism.

**Comment by mdickinson** [comment]
> I am considering this a bug in the assertTraitChanges not in the trait listeners.

Yes, understood.  But there isn't really a well-defined concept of order for trait change firings in this case: it's even possible for listeners for `new_value` and `new_new_value` to be fired in an interleaved fashion.

**Comment by itziakos** [comment]
After an offline discussion, I agree with @mdickinson  that it is not a bug, but we need to provide some discussion in the `assertTraitChanges` methods.

**Comment by mdickinson** [comment]
See #231 for a doc fix.
