### ISSUE TITLE
pip install traits: tests fail on Python-3

### ISSUE THREAD

**Issue by Dedoig** [enthought/traits#242]
I get several of this kind of Python-2 vs. 3 print error with `pip install traits`:

```
....site-packages/traits/testing/dependencies/circular_test.py", line 10
        print "usage: %s [--chart] [-p] input" % sys.argv[0]
```

I'm installing this into an anaconda / Python3.4 setup.

**Comment by stefanoborini** [comment]
Cannot verify on either 3.4 or 3.5. Closing.
