### ISSUE TITLE
Range validation with numpy data as limits is incorrect.

### ISSUE THREAD

**Issue by stefanoborini** [enthought/traits#247]
The statement

    Range(-np.pi, np.pi)

introduces some trouble. numpy.pi is not considered a float, with the result that validation does not occur. I had to force it with 

    Range(-np.pi, np.pi, 0.0)

It's a corner case, but it can produce unexpected head scratching sessions.

**Comment by mdickinson** [comment]
@stefanoborini: Can you show a complete example?  I'm having trouble reproducing:

```
>>> import numpy as np
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = Range(-np.pi, np.pi)
...     bar = Range(-3.1415, 3.1415)
... 
>>> a = A()
>>> a.foo = -10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'foo' trait of an A instance must be -3.14159265359 <= a floating point number <= 3.14159265359, but a value of -10.0 <type 'float'> was specified.
>>> a.bar = -10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'bar' trait of an A instance must be -3.1415 <= a floating point number <= 3.1415, but a value of -10.0 <type 'float'> was specified.
```

**Comment by mdickinson** [comment]
And `np.float64` inherits from Python's `float`, so it would be a bit surprising if `np.float64` instances weren't considered floats.  Maybe we're doing a direct type check somewhere instead of using `isinstance`?

**Comment by mdickinson** [comment]
And in fact, `np.pi` is a Python float!

**Comment by mdickinson** [comment]
I'm going to close this issue; from offline discussion with @stefanoborini, it sounds as though the actual cause of the problems he was seeing must have been something different.

**Comment by stefanoborini** [comment]
Verified. Good for me! :+1:
