### ISSUE TITLE
huge memory consumption when using @on_trait_change decorator

### ISSUE THREAD

**Issue by BigSkylie** [enthought/traits#255]
Creating many instances of a class using a @on_trait_change decorator uses ridiculously much memory. A class with the same functionality but notifications implemented via the special naming convention use significantly less memory.

This issue is right now being discussend on stackoverflow, where you can also find a minimal working example:

http://stackoverflow.com/questions/31682666/memory-usage-on-trait-change-vs-foo-changed

**Comment by pberkes** [comment]
For reference, this is the code snippet in the stackoverflow question:
```
from traits.api import *

class Foo(HasTraits):
    a = List(Int)

    def _a_changed(self):
        pass

    def _a_items_changed(self):
        pass

class FooDecorator(HasTraits):
    a = List(Int)

    @on_trait_change('a[]')
    def bar(self):
        pass

if __name__ == '__main__':
    n = 100000
    c = FooDecorator
    a = [c() for i in range(n)]
```

I can confirm the behavior on OSX, using the latest traits from `master`.
There is also a huge difference in running times: 0.7s using `Foo` and 20s using `FooDecorator`.

**Comment by corranwebster** [comment]
For reference, I think this is just the overhead associated with the dynamic trait change handlers - for each instance and each on trait change, you get a fair few additional Python objects to handle the dynamic listening.

I have posted a more complete write-up on the above thread.

**Comment by BigSkylie** [comment]
[Follow up ticket](https://github.com/enthought/traits/issues/256)
