### ISSUE TITLE
wrong URL on PyPI

### ISSUE THREAD

**Issue by pierre-haessig** [enthought/traits#273]
The PyPI page https://pypi.python.org/pypi/traits provides a link to http://github.enthought.com/traits which leads to a "404 not found" error page. 

I guess a link to either https://github.com/enthought/traits or documentation at http://docs.enthought.com/traits/ would be a good replacement.

best,
Pierre

**Comment by badi** [comment]
I ran into this issue as well.

**Comment by souravsingh** [comment]
The issue is fixed.

**Comment by mdickinson** [comment]
@souravsingh: It is indeed. Thanks!
