### ISSUE TITLE
*_items events confusion for nested containers (List inside a Dict)

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#281]
[Reported in a comment in #278. I'm opening a separate issue: while it's not unrelated to #278, it may be possible to solve this independently of #278.]

The following code produces a traceback.

```
from traits.api import Dict, HasStrictTraits, List, Str

class Collection(HasStrictTraits):
    results = Dict(Str, List(Str))

collection = Collection(results={'foo': []})
collection.results['foo'].append('bar')
```

Traceback:

```
Traceback (most recent call last):
  File "traits_bug.py", line 7, in <module>
    collection.results['foo'].append('bar')
  File "/Users/mdickinson/Enthought/ETS/traits/traits/trait_handlers.py", line 2504, in append
    raise excp
traits.trait_errors.TraitError: Each element of the 'results_items' trait of a Collection instance must be a TraitDictEvent or None, but a value of <traits.trait_handlers.TraitListEvent object at 0x107e6d990> <class 'traits.trait_handlers.TraitListEvent'> was specified.
```

What's going on here is that the inner `List` trait results in creation of a `TraitListObject` with name `'results'` and instructions to fire events for list changes to `results_items`. So `results_items` ends up receiving `TraitListEvent` objects, when it's expecting `TraitDictEvent` objects.

It turns out that there's already a partial attempt to fix this, [here](https://github.com/enthought/traits/blob/0f20d41fd0ceba6205e90ed9960bbcf281ab965e/traits/trait_types.py#L2525-L2529). But the new handler is not poked back into `self.value_trait`, so the original handler (which generates items events) is used when creating the original dict, instead of the hacked handler. However, it's not 100% clear whether it's _safe_ to poke that new handler back into `self.value_trait`: we may end up modifying an object that's being used elsewhere.

This _does_ mean that having created an instance of `Collection`, it's safe to add lists as items post-creation, and then modify those lists.

```
>>> from traits.api import *
>>> class Collection(HasStrictTraits):
...     results = Dict(Int, List(Int))
... 
>>> c = Collection(results={1: [10, 11, 12]})
>>> c.results[2] = [20, 21, 22]
>>> c.results[2].append(23)  # works fine
>>> c.results[1].append(13)  # fails as before
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/traits/trait_handlers.py", line 2504, in append
traits.trait_errors.TraitError: Each element of the 'results_items' trait of a Collection instance must be a TraitDictEvent or None, but a value of <traits.trait_handlers.TraitListEvent object at 0x107e44850> <class 'traits.trait_handlers.TraitListEvent'> was specified.
```

**Comment by Nan2018** [comment]
This event confusion happens for any nested containers when the outer container and inner container are different types. For example
```
from traits.api import *

class Collection(HasStrictTraits):
    results = List(Set())

collection = Collection(results=[{1}])
collection.results[0].add(2) # fails
collection.results.append({1})
collection.results[-1].add(2) # fails
```

**Comment by k2bd** [comment]
The following also produces a similar error:

```
from traits.api import Either, Dict, HasTraits


class MyClass(HasTraits):
    maybe_dict = Either(None, Dict)


my_obj = MyClass(maybe_dict={1: 2, 3: 4})

del my_obj.maybe_dict[1]
```

**Comment by mdickinson** [comment]
This one is also high priority to fix, possibly as part of the notifiers rework.

**Comment by mdickinson** [comment]
Closing as a duplicate of #25. I'll add that one to the milestone instead.
