### ISSUE TITLE
TraitSetObject doesn't fire events on in-place operations

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#287]
As seen in this example:
```
from traits.api import HasTraits, Set

class Test(HasTraits):

     s = Set

t = Test()

def items_changed(event):
    print event.added

t.on_trait_change(items_changed, 's_items')

t.s |= {0, 1, 2}
t.s.update({4, 5, 6})

print t.s
```

Essential problem is that `TraitSetObject` doesn't override `__ior__` (or `__iand__` or `__isub__` or `__ixor__` for that matter) so that it fires the appropriate TraitSetEvent on the `..._items` trait.  The fix is straightforward (write these methods), and should be a Simple Matter of Coding.

**Comment by mdickinson** [comment]
Closed by #289.
