### ISSUE TITLE
Broken links in the docs intro page

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#291]
On the [intro page](http://docs.enthought.com/traits/traits_user_manual/intro.html), there seem to be two broken links (TraitsUI User Manual) pointing to a `github.enthought.com/...` site.

The issue seems to be that while the broken links were fixed in master [here (Dec 29 2014)](https://github.com/enthought/traits/blob/master/docs/source/traits_user_manual/intro.rst), the fix wasn't pushed to gh-pages [here(May 6 2014)](https://github.com/enthought/traits/blob/gh-pages/traits_user_manual/intro.html).

**Comment by stefanoborini** [comment]
Verified no longer to be there.
