### ISSUE TITLE
Drop support for Python 2.6 and Python 3.2 in Traits 5.0.0

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#303]
Let's explicitly drop support for Python 2.6 and Python 3.2 in Traits 5.0.0.

Some data points:
- current IPython requires Python 2.7 or Python >= 3.3, according to the [installation docs](https://ipython.readthedocs.io/en/stable/install/install.html).
- matplotlib [requires Python 2.7 or Python >= 3.4](http://matplotlib.org/users/installing.html#required-dependencies).
- Pandas [requires Python 2.7 or Python >= 3.4](http://pandas.pydata.org/pandas-docs/stable/install.html#python-version-support)

Subtasks:
- [ ] Document the Python version requirements clearly.
- [ ] Remove CI runs for Python 2.6, 3.2.
- [ ] Optionally, clean up some of the cruft that's only there to support Python 2.6. Most notably, the dependence on unittest2 and the need for `from traits.testing.unittest_tools import unittest` in tests.

**Comment by itziakos** [comment]
:+1:

**Comment by mdickinson** [comment]
Another data point: current Sphinx requires Python 2.7 or Python >= 3.4 (it uses `collections.OrderedDict`). See #344.

**Comment by mdickinson** [comment]
Done in #345.
