### ISSUE TITLE
Cython port roadmap

### ISSUE THREAD

**Issue by jvkersch** [enthought/traits#307]
https://github.com/enthought/traits/pull/298 passes the standard traits test suite but is quite a way from being ready for production. This ticket is to discuss concrete steps that we can take to improve the code, and to record issues that come up during the development.

Known issues:
- Unicode attribute support is probably patchy (see the discussion in https://github.com/enthought/traits/pull/298#issuecomment-224299326);
- There are several spots in the code marked as not implemented.

Roadmap:
- Enable Cython coverage (at least for testing), write tests to exercise untested code paths;
- Run the tests for some ETS projects (and other traits-using projects) using this branch.

@dpinte @pberkes @sjagoe Please feel free to add/amend.

**Comment by mdickinson** [comment]
If we can get the Cython port to the point where test runs for a selected few major applications pass (and those applications also run without new issues), that's good enough for me for it to go into Traits 5.0.0.

As @dpinte mentioned at some point, this is a great opportunity to improve the test suite: every time we do encounter a failure from one of those projects, we can add a suitable regression test.

**Comment by jvkersch** [comment]
This has been split up into several issues.
