### ISSUE TITLE
Deprecate Traits Category Classes

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#319]
A Traits `Category` class is a class which injects its traits and methods into its superclass at class definition time, essentially monkeypatching the base class with the subclass methods. See https://github.com/enthought/traits/blob/master/traits/category.py

This is a bad idea.

Monkeypatching  should be avoided unless absolutely needed, and this is a particularly fragile, hard-to-control way of performing monkeypatching, since it will typically occur when a module is imported as a side-effect.  It leads to code like this https://github.com/enthought/pyface/blob/830a9488463bd9863a4678f3f21fec5fa8a0b1ee/pyface/dock/dock_window_shell.py#L29 that imports a module solely to ensure that methods are monkeypatched onto a class.  It also produces code which is misleading, since it otherwise looks like regular subclassing when used.

Better ways to solve the sort of problem that Category is attempting to solve would include standard subclassing (possibly with ABCs), Traits adaptation, Envisage services or "toolkit/driver selection"-type approaches, or if monkeypatching is absolutely needed defining a patching function to make the appropriate changes (which can be completely arbitrary).

Traits `Category` classes are only used in the following places in the ETS codebase, as far as I can tell:
- The TraitsUI Wx toolkit uses it for theming support to inject backend specific code into the base theme classes.
- There is support for on-the-fly addition of Categories to classes in Envisage core.  This is less misleading, but relies on magic to detect HasTraits class definitions and perform the Category patching.

Concretely, we should:
- try to remove the usage in TraitsUI.
- add a deprecation warning that is fired when a Category is used.

**Comment by itziakos** [comment]
:+1:
