### ISSUE TITLE
Traits attributes don't show up in Jupyter console tab-completion

### ISSUE THREAD

**Issue by timdiller** [enthought/traits#320]
In IPython / Jupyter 4 consoles, attributes which are `Traits` do not show up in tab-completion.  Regular class- and instance-attributes do.

```
$  jupyter console
Jupyter Console 4.1.1

In [1]: from traits.api import HasTraits, Float

In [2]: class Foo(HasTraits):
   ...:     bar = Float
   ...:     baz = "qux"
   ...: 

In [3]: f = Foo()

In [4]: f.baa = "quux"

In [5]: f.b<tab>
f.baa         f.base_trait  f.baz         

In [5]: f.bar
Out[6]: 0.0
```

**Comment by mdickinson** [comment]
This isn't really all that surprising: it's a direct consequence of the way that traits is implemented. There's no entry for `bar` in the object's `__dict__` (or in its type's `__dict__`, for that matter) at the point where `f` is created, so there's no obvious way for a non-traits-aware Jupyter to discover those traits and do tab completion. I don't think it's reasonable to change the design of traits here (populating the `__dict__` at creation time or tab-completion time would involve evaluating all defaults, for example, which would be a huge breaking change to the behaviour). It may well be possible to augment or adapt Jupyter's tab completion to be Traits-aware; I don't know how configurable / pluggable that tab completion is.

Labelling as a potential enhancement.

```
In [1]: from traits.api import Float, HasTraits

In [2]: class Foo(HasTraits):
   ...:     bar = Float
   ...:     

In [3]: f = Foo()

In [4]: f.__dict__
Out[4]: {}

In [5]: f.bar # retrieving the value for the first time adds an entry to the `__dict__`
Out[5]: 0.0

In [6]: f.__dict__
Out[6]: {'bar': 0.0}

In [7]: f.b<TAB>  # tab completion now works.
f.bar         f.base_trait  
```

**Comment by mdickinson** [comment]
It looks as though overriding `__dir__` in `HasTraits` may be enough here. That doesn't seem like an unreasonable thing to do.
