### ISSUE TITLE
Bytes trait for Python 3

### ISSUE THREAD

**Issue by jwiggins** [enthought/traits#328]
So, I've been using traits on a project which uses Python 3. Everything seems to work as expected, _but_ I can't figure the correct trait to use for `bytes` objects. `Str`/`String`/`Unicode` all appear to only accept `string` objects. `CStr` allows assignment, but the coercion is really strange (`b'Hello' -> "b'Hello'"`).

The only workaround I've found so far is `Any`, and that just feels wrong.

**Comment by corranwebster** [comment]
Agreed that this should probably be introduced.  There should be `Bytes` and `CBytes`, and behaviour for Python 2 should be that they store `str`, not `unicode`.  A "slow" validator should be straightforward.  A "fast" validator at the C level may be a bit trickier.

**Comment by jvkersch** [comment]
If this is not already in a branch somewhere, I can pick this up in the near-ish future. I've spent quite some time looking at the C code, so the fast validator sounds like a good challenge.

**Comment by corranwebster** [comment]
I just implemented it, still needs some tests.

**Comment by corranwebster** [comment]
Also, what is appropriate editor behaviour for bytes?

I am tempted to suggest something like a value of `b'Test'` being displayed in the editor as `84 101 115 116` (possibly comma separated instead) or maybe `54 65 73 74` (hex) instead.

**Comment by jwiggins** [comment]
Wow, that was fast! :smiley:

@corranwebster: I was hoping that the editor for numpy arrays offered some guidance here, but it does not. So, I vote for your hex idea. `bytes` is for data, and hex seems like a good fit.

**Comment by mdickinson** [comment]
What happens if you assign the integer `999` to `CBytes` trait?

**Comment by corranwebster** [comment]
The answer is currently  whatever `bytes(999)` does on your version of Python, and I think that that's _probably_ good enough (its at least easy to reason about - although the behaviour for 999 is a little surprising :) ).

We already have a similar issue for `CStr` with `bytes` objects giving different behaviour between the two versions because of the difference in what `str(b'...')` does.

I'm open to ideas if anyone has any suggestions.

**Comment by corranwebster** [comment]
FWIW, traitlets' `CBytes` behaves the same way.
