### ISSUE TITLE
Python3 Incompatible sort in trait_handlers:TraitListObject

### ISSUE THREAD

**Issue by ericjmcd** [enthought/traits#331]
TraitListObject has a method "sort" that calls list.sort which is not compatible with Python3.
`list.sort( self, cmp = cmp, key = key, reverse = reverse )`

I believe simply removing the `cmp = cmp` portion makes it compatible but am not sure. Plus, the method has "cmp" as a kwd argument so there may be other issues elsewhere.

**Comment by corranwebster** [comment]
In current master, this looks like it should not happen: see https://github.com/enthought/traits/blob/master/traits/trait_handlers.py#L2603  The Python 3 version should not call list.sort with a cmp keyword.  This was changed in 2014, so the fix has been in the codebase for some time.

Can you please give more information about the version of Traits you are using, in particular if you are using the current master version?

**Comment by ericjmcd** [comment]
Sorry - still figuring out github branches vs tags.  It appears this is a bug in 4.5.0 (since Feb 2014!) but has been fixed in master.  I hope a new release is coming down the pike.
