### ISSUE TITLE
Remove Class trait, add Subclass as an alias for Type trait

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#351]
The `Class` trait is for old-style classes only, and so isn't even available for Python 3.  The `Class` trait should be removed completely from the trait types.

What people are likely to actually want is the `Type` trait, which is of a similar intent, but works correctly for new-style classes. To make it easier to find for users who are thinking about "classes" instead of "types", we should add `Subclass` as an alias for `Type`.

**Comment by notmatthancock** [comment]
I'm still relatively new to traits, and I just got bit by this. Not being familiar with old/new-style classes, the error was somewhat confusing, but it was easy enough to google and learn about old/new style classes. However, it was unclear how to proceed in place of using `Class`. I can't comment on whether `Class` should be removed, but I think at least, the `TraitError` raised by `Class` should suggest using `Type` instead.

**Comment by corranwebster** [comment]
The only thing left here is to add `Subclass` as an alias for `Type` in `TraitTypes` (and `traits.api`)
