### ISSUE TITLE
disable any File exists validation

### ISSUE THREAD

**Issue by satra** [enthought/traits#355]
is there a way to disable any validation for a trait globally?

```
class A(HasTraits):
    foo = File(exists=True)


a = A()
a.foo = 'foo'  
pickle a

# delete 'foo'
# file foo doesn't exist any more.

unpickle a 
a.foo should still equal 'foo' even though it doesn't exist.
```

is there something i can do to disable validation for all `File(exists=True)` validation? i'm unpickling a trait object and the file it refers to may not exist anymore.

**Comment by stefanoborini** [comment]
There is no such functionality. Your best strategy would be to have to remove the exists flag and perform this check somewhere else.
