### ISSUE TITLE
"self" trait type should have transient set True

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#367]
The `transient` metadata flag is used to indicate traits which shouldn't be serialised when pickling, etc.  It seems to me that the `self` trait type, which always holds a reference to the instance of the trait itself should not be serialized by default, similar to `Property` and other automatic trait types.

**Comment by mdickinson** [comment]
What's the issue with pickling? It seems to work for me:
```
>>> from traits.api import *
>>> class A(HasTraits):
...     me = self
... 
>>> a = A()
>>> a.me is a
True
>>> import pickle
>>> a_restored = pickle.loads(pickle.dumps(a))
>>> a_restored.me is a_restored
True
```

It also turns out that `self` doesn't necessarily mean `self`:

```
>>> b = A(me=a)
>>> b.me is b
False
>>> b.me is a
True
```

**Comment by corranwebster** [comment]
This is more a philosophical issue.  It _can_ be pickled, but based on the implied intent, probably _shouldn't_.

However, given the implementation allowing non-self values in a self trait... I will close.
