### ISSUE TITLE
Property trait interferes with cloning of instance trait

### ISSUE THREAD

**Issue by jvkersch** [enthought/traits#368]
When calling `clone_traits()` on a HasTraits class that has an instance trait and a property trait that refers to that trait, the property trait interferes somehow with the cloning of the original. The result is that the instance on the cloned object ends up being identical to the instance on the original object. See the code below for a minimal example.

Credit goes to @prashantmital for the discovery.

```python
from traits.api import HasTraits, Property, Instance
from collections import OrderedDict

class A(HasTraits):

    x = Instance(OrderedDict, args=())
    y = Property()

    def _get_y(self):
        return self.x

    def _set_y(self, val):
        self.x = val


a = A()
b = a.clone_traits()

print(id(a.x))
print(id(b.x))

b.x['foo'] = 'bar'
assert 'foo' not in a.x

```

**Comment by corranwebster** [comment]
From personal communication: there may be an issue here, but a work-around is that doing
```
b = a.clone_traits(copy='deep')
```
avoids the issue.

**Comment by jvkersch** [comment]
Interestingly, `copy='shallow'` also works :D

From looking at the source, what happens is that `clone_traits` will first copy the ordinary traits, and then the properties. When it copies the instance trait, it will make a deep copy regardless of the value of `copy`, but when the property `y` is copied with `copy='ref'` that will effectively reset `x`.

Not sure there's anything to be done here, so I'll close this.
