### ISSUE TITLE
Traitsui is needed when testing Editors

### ISSUE THREAD

**Issue by martinRenou** [enthought/traits#372]
A test for editors has been written in #371 but it cannot pass on travis because traitsui is missing. Traitsui should be added as requirements.

**Comment by corranwebster** [comment]
Yes, but only for the test runs, and if we do that we also want to do runs in the absence of TraitsUI.

An alternative: would it make sense to add the tests to TraitsUI, even though it is testing Traits?

**Comment by corranwebster** [comment]
This has been resolved in etstool.py and the test code - tests which require traitsui now have a standard decorator, and the standard test runners install pyqt and traitsui.
