### ISSUE TITLE
Setting This trait to None fails with TraitError

### ISSUE THREAD

**Issue by dsoft-tw** [enthought/traits#383]
Using the following code
```
from traits.api import This, HasTraits

class Entity(HasTraits):
  parent = This

    def __init__(self, parent=None):
        self.parent = parent

if __name__ == '__main__':
    new_entity = Entity()
```
results in the following error:

> Traceback (most recent call last):
>   File "C:/source/github_dsoft/SPySE/develop/src/spyse/test_traits_none.py", line 10, in <module>
>     new_entity = Entity()
>   File "C:/source/github_dsoft/SPySE/develop/src/spyse/test_traits_none.py", line 7, in __init__
>     self.parent = parent
>   File "C:\Program Files\Anaconda3\envs\spyse_36\lib\site-packages\traits\trait_handlers.py", line 172, in error
>     value )
> traits.trait_errors.TraitError: The 'parent' trait of an Entity instance must be an instance of the same type as the receiver or None, but a value of None <class 'NoneType'> was specified.

When I create my own **This** class (subclassing from **BaseType**) and comment out the _fast_validate_ line, it works as expected.

Using Anaconda 4.3, Python 3.6, Traits 4.6.0

**Comment by rkern** [comment]
This was fixed by #353.
