### ISSUE TITLE
Custom Trait Setting Issue

### ISSUE THREAD

**Issue by VenturaFranklin** [enthought/traits#385]
I am doing something wrong with my custom trait that notifications are not propagating.
See my example below:
```
from traits.api import BaseFloat, HasTraits, Float

class TempFloat(BaseFloat):
    default_value = 20.0
    info_text = 'A calculated temperature float'

    def set(self, obj, name, value):
        celsius = (value - 32) * (5/9)
        setattr(self, name, celsius)

    def get(self, obj, name):
        val = getattr(self, name)
        if val is None:
            val = self.default_value
        return val

class System(HasTraits):
    def __init__(self):
        self.add_trait('temp_custom', TempFloat())
        self.add_trait('temp_plain', Float())
        self.on_trait_change(self.temp_change, "temp_custom")
        self.on_trait_change(self.temp_change, "temp_plain")

    def temp_change(self):
        print("I CHANGED THE TEMP")

system = System()
print("Custom Temp")
print(system.temp_custom)
system.temp_custom = 10
print(system.temp_custom)

print("Plain Temp")
print(system.temp_plain)
system.temp_plain = 10
print(system.temp_plain)
```
Output is:

> Custom Temp
> 20.0
> -12.222222222222223
> Plain Temp
> 0.0
> I CHANGED THE TEMP
> 10.0

I would expect the print "I CHANGED THE TEMP" to occur in both changes of the temp, but I assume I'm missing something from my set function in my custom trait. Please let me know how to get the on_trait_change to register for my custom trait.
Thank you for your help,
Frank V.

**Comment by VenturaFranklin** [comment]
I'm using python 3.6, traits 4.7.0.dev59

**Comment by rkern** [comment]
If you implement `__init__()`, you must call `super().__init__()`. `HasTraits.__init__()` sets up the infrastructure for the dynamic `on_trait_change()` mechanism.

**Comment by VenturaFranklin** [comment]
@rkern You are right, I forgot that, however, I see the same issue.
I adjusted the `System.__init__` to have `super().__init__()`

```
class System(HasTraits):
    def __init__(self):
        super().__init__()
        self.add_trait('temp_custom', TempFloat())
        self.add_trait('temp_plain', Float())
        self.on_trait_change(self.temp_change, "temp_custom")
        self.on_trait_change(self.temp_change, "temp_plain")

    def temp_change(self):
        print("I CHANGED THE TEMP")
```

**Comment by VenturaFranklin** [comment]
I think this is related to another issue I noticed, where properties do not cause changes.
You must call self.set_value(obj, name, value) within the set function of a trait property.

Two fixes for my above issue:
When [Defining a Trait Property ](http://docs.enthought.com/traits/traits_user_manual/custom.html#defining-a-trait-property) 
Add a `set_value(obj, name, value)` to the set function of the property like this:
```
class TempFloat(BaseFloat):
    default_value = 20.0
    info_text = 'A calculated temperature float'
    
    def set(self, obj, name, value):
        celsius = (value - 32) * (5/9)
        setattr(self, name, celsius)
        self.set_value(obj, name, value)

    def get(self, obj, name):
        val = getattr(self, name)
        if val is None:
            val = self.default_value
        return val
```

Or change to [Defining a Trait Type](http://docs.enthought.com/traits/traits_user_manual/custom.html#defining-a-trait-type)
And only use the `validate` method like this:
```
class TempFloat(BaseFloat):
    default_value = 20.0
    info_text = 'A calculated temperature float'
    
    def validate(self, object, name, value):
        celsius = (value - 32) * (5/9)
        return celsius
```

Either of these changes __done independantly__ produce the desired output:
> Custom Temp
> 20.0
> -12.222222222222223
> I CHANGED THE TEMP
> -12.222222222222223
> Plain Temp
> 0.0
> I CHANGED THE TEMP
> 10.0

While my issue is solved, I want to know if trait properties are meant to issue a change notification on setting without calling `set_value(obj, name, value)`?

**Comment by rkern** [comment]
Ah, yes. When you override `.set()`, eventually you need to call `object.trait_property_changed(name, old, value)` to trigger notifications. `set_value()` does this (in addition to setting the cached value in `__dict__`, which is also a good and necessary thing). The two implementations of `.set()` in `traits/trait_types.py` do this explicitly (in their cases, they need to customize what gets put into the `__dict__`).

Calling `.set_value()` is the way to go.

**Comment by rkern** [comment]
Actually, for property-like traits, there may be reasons not to cache the value in `__dict__`. So if you don't want that, explicitly call `object.trait_property_changed(name, old, value)` and not `.set_value()`.

**Comment by jonathanrocher** [comment]
Ps @VenturaFranklin if you have questions to ask, instead of creating an issue, you could join and then hit the newly (re)created ETS mailing list: https://groups.google.com/d/forum/ets-users

**Comment by VenturaFranklin** [comment]
@rkern thanks for the info! And @jonathanrocher I  didn't know that existed, I joined the group, thanks!
