### ISSUE TITLE
Wxpython API has changed as of version 4.0

### ISSUE THREAD

**Issue by rpep** [enthought/traits#388]
Causes issues such as: 

```
  File "/usr/local/lib/python2.7/site-packages/traitsui/wx/constants.py", line 67, in <module>
    scrollbar_dx = wx.SystemSettings_GetMetric( wx.SYS_VSCROLL_X )
AttributeError: 'module' object has no attribute 'SystemSettings_GetMetric'
```

Details of the API changes are given here:
https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html

**Comment by mdickinson** [comment]
This looks like a Traits UI issue rather than a Traits one; I've opened enthought/traitsui#416. I'll close here.
