### ISSUE TITLE
HasStrictTraits error message and unicode attribute name

### ISSUE THREAD

**Issue by jonathanrocher** [enthought/traits#399]
**[EDIT]** I renamed attribute from `a` and `as` to `x` and `y` to avoid wondering if python keyword `as` is causing the issue. 

As seen using current master and 4.6.0, under python2.7, the following code below leads to a meaningful TraitsError error message for t2, namely:
```
Cannot set the undefined 'y' attribute of a 'Test' object.
```
but a misleading one for t3:
```
Traceback (most recent call last):
  File "test_unicode_traits.py", line 19, in <module>
    t3 = Test(**{u"y": 1})
TypeError: attribute name must be an instance of <type 'str'>. Got u'y' (unicode).
```
I would find desirable that the give the same error message.

Code to illustrate the issue:
```
from traits.api import HasStrictTraits, Int
class Test(HasStrictTraits):
    x = Int

# Successful despite the unicode-ness of the dict key:
t = Test(**{u"x": 1})

# Expected failure with meaningful error message:
try:
    t2 = Test(**{"y": 1})
except Exception as e:
    print(e)

# Expected failure with misleading message:
t3 = Test(**{u"y": 1})
```

**Comment by corranwebster** [comment]
Double check here: `as` is a keyword, so you normally can't set an attribute `foo.as`.  Is this a factor in the error?

**Comment by jonathanrocher** [comment]
Yes, since it's a `HasStrictTraits`, `as` is a typo in the attribute name, but for t3, instead of telling me that, like for t2, it tells me that the issue is the fact that the attribute name is of unicode type instead of str. That can lead people to chase the wrong issue. Makes sense?

**Comment by mdickinson** [comment]
> Is this a factor in the error?

No: I see the same results with `as` replaced with `bs` everywhere.
