### ISSUE TITLE
on_trait_change: trailing comma in an extended name causes surprises

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#406]
Decorating a `HasTraits` subclass method with `@on_trait_change('foo,bar,')` has the surprising side-effect of listening to everything. In most parts of Python, trailing commas are innocuous.

Example script:
```python
from traits.api import *

class A(HasTraits):
    foo = Int()
    bar = Int()
    baz = Int()

    @on_trait_change('foo,bar,')
    def _report_change(self, obj, name, old, new):
        print("{!r} trait changed from {!r} to {!r}".format(name, old, new))


a = A()
a.bar = 5  # expect a single notification; get two notifications
a.baz = 3  # expect no notification, but a notification occurs
```

On running this, I see the following output:
```
bash-4.4$ python bug.py 
'bar' trait changed from 0 to 5
'bar' trait changed from 0 to 5
'baz' trait changed from 0 to 3
```

With the trailing comma removed, I get:
```
bash-4.4$ python bug.py 
'bar' trait changed from 0 to 5
```

Labelling as a bug: even if this is working as intended behaviour (which seems possible), it's at least a usability bug, and I've seen it trip up newcomers on more than one occasion. I think we should fix this, even at the risk of possibly breaking existing code.

The fix I'd propose is making a trailing comma here an error: this would give a noisy early breakage for any projects that are intentionally or accidentally using this pattern, rather than the subtle late-discovered breakage that might occur if we simply allow the trailing comma but change the behaviour.

**Comment by itziakos** [comment]
> The fix I'd propose is making a trailing comma here an error

I am in favor of such a behaviour

**Comment by rkern** [comment]
Sounds good to me.
