### ISSUE TITLE
Make HasTraits._each_trait_method public

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#414]
A [recent fix](https://github.com/enthought/envisage/pull/121) in Envisage uses the private `HasTraits._each_trait_method` method. To avoid an overenthusiastic `HasTraits` refactoring accidentally breaking Envisage in the future, we should make `_each_trait_method` public and add some unit tests for it.

**Comment by rkern** [comment]
It should be refactored out to a utility function, as it does not actually refer to `self`, so it does not need to be a method on `HasTraits` (and so should not be raised to a public method in an already too-crowded public method namespace).

**Comment by mdickinson** [comment]
I'm going to close this issue. The functionality Envisage needs at this point (finding all methods decorated with `@contributes_to`, without going via something that invokes `__dir__`) has nothing particularly to do with Traits, so exposing it in Traits seems like the wrong solution. The non-hacky fix here is probably just to replicate the code from Traits in Envisage.
