### ISSUE TITLE
Strict traits complains about key being unicode when attribute is undefined

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traits#415]
When a `HasStrictTraits` subclass is initialized with a dictionary and one of the keys is not an attribute on the class, then the error message changes depending on whether the key type is string or unicode. Example:

```
from traits.api import HasStrictTraits, Str


class Thing(HasStrictTraits):
    item = Str


if __name__ == '__main__':
    good_kwargs_str = {'item': 'the item value'}
    good_kwargs_uni = {u'item': 'the item value'}

    bad_kwargs_str = {'attr_no_exist': 'the item value'}
    bad_kwargs_uni = {u'attr_no_exist': 'the item value'}

    # No errors
    thing = Thing(**good_kwargs_str)
    thing = Thing(**good_kwargs_uni)

    try:
        thing = Thing(**bad_kwargs_str)
    except Exception as e:
        print("Error when key is str: {}".format(e))

    try:
        thing = Thing(**bad_kwargs_uni)
    except Exception as e:
        print("Error when key is uni: {}".format(e))
```

This prints
> Error when key is str: Cannot set the undefined 'attr_no_exist' attribute of a 'Thing' object.
Error when key is uni: attribute name must be an instance of <type 'str'>. Got u'attr_no_exist' (unicode).

When the key type is string, the "correct" error message is printed, namely, we're trying to assign to undefined attribute on a strict traits class. When the key type is unicode, the error message tells us the problem that the key value is unicode, despite the initialization being happy with unicode key types provided the keys reference defined attributes.

**Comment by corranwebster** [comment]
Thanks for the report.  Do you see it under Python 2 or 3 (or both)?

**Comment by notmatthancock** [comment]
Whoops. Just Python 2: tested only on 2.7.15 and 3.6.0.

**Comment by mdickinson** [comment]
Same as #399?
