### ISSUE TITLE
Color docstrings refer to black as white

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traits#416]
In the [`Color` docstring](https://github.com/enthought/traits/blob/ad62b8099f651fb4f57864a6eb1df54effcf48ba/traits/traits.py#L1293) and [`RGBColor` docstring](https://github.com/enthought/traits/blob/ad62b8099f651fb4f57864a6eb1df54effcf48ba/traits/traits.py#L1317)  black is listed as the default (in hex and rgb, respectively), but referred to as the color white.

**Comment by mdickinson** [comment]
That's exciting. Do we know what the _actual_ default is? Is it black or white?

**Comment by notmatthancock** [comment]
with qt, black for both

**Comment by mdickinson** [comment]
Hmm; apparently for wxPython it really _is_ white:
```
>>> class A(HasTraits):
...     rgb = RGBColor()
...     col = Color()
... 
>>> a = A()
>>> a.rgb
'white'
>>> a.col
wx.Colour(255, 255, 255, 255)
```

**Comment by mdickinson** [comment]
> with qt, black for both

So that's not what I'm seeing. Can you show what you did?

Here's Python 2.7 + PyQt on mac:
```
Python 2.7.13 |Enthought, Inc. (x86_64)| (default, Mar  2 2017, 08:20:50) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from traits.api import *
>>> class A(HasTraits):
...     rgb = RGBColor()
...     col = Color()
... 
>>> a = A()
>>> a.rgb
'white'
>>> a.rgb_
(1.0, 1.0, 1.0)
>>> a.col
<PyQt4.QtGui.QColor object at 0x1195bc320>
>>> a.col.getRgb()
(255, 255, 255, 255)
```

**Comment by notmatthancock** [comment]
Apologizes, I was answering in a rush. My output is identical to yours above -- the default is indeed white.

Then, all that is mismatched in the docstrings are the values given for the color hex and the rgb tuple, which should be as the output you've listed.

**Comment by mdickinson** [comment]
Right, so quick fix is to fix those values; longer fix is to notice that the docstrings should be specifying what happens in Qt as well as in wx, and then to notice that these aren't the only two docstrings affected. Sigh.

I'll make the quick fix right now; don't have cycles for the longer fix at the moment.

**Comment by mdickinson** [comment]
> I'll make the quick fix right now

Done in #417. @notmatthancock if you have a couple of spare minutes to review, I'd appreciate it.
