### ISSUE TITLE
Should Range CTrait accept long high values? On Py2, Win.

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#421]
Currently, in a Windows Python 2.7.13 environment, the Range CTrait raises a `ValueError: The argument must be a tuple or callable.` when passed a long value as `high`.

```
In [1]: from traits.api import Range

In [2]: Range(low=0, high=2**32-1, mode='text')()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-b326bbd6c568> in <module>()
----> 1 Range(low=0, high=2**32-1, mode='text')()

C:\Users\IEUser\Github\traits\traits\trait_handlers.py in __call__(self, *args, **kw)
    571         """ Allows a derivative trait to be defined from this one.
    572         """
--> 573         return self.clone( *args, **kw ).as_ctrait()
    574
    575     def _is_valid_for ( self, object, name, value ):

C:\Users\IEUser\Github\traits\traits\trait_handlers.py in as_ctrait(self)
    634
    635             if validate is not None:
--> 636                 trait.set_validate( validate )
    637
    638             post_setattr = getattr( self, 'post_setattr', None )

ValueError: The argument must be a tuple or callable.
```

**Comment by rahulporuri** [comment]
Note the extra call to `Range(...)()`. This creates a clone of the current trait and calls `as_ctrait` on the cloned instance. See https://github.com/enthought/traits/blob/master/traits/trait_handlers.py#L570-L573 .

Note also that the same doesn't happen when `BaseRange` is used instead of `Range`. Note also that only setting `high` in `Range`, without setting `low` also works.

```
In [1]: from traits.api import BaseRange, Range

In [2]: BaseRange(low=0, high=2**32-1, mode='text')()
Out[2]: <traits.traits.CTrait at 0x52da780>
>>> Range(high=2**32-1)()
<traits.traits.CTrait object at 0x0000000003440EB8>
```

The error seems to be happening in the `_trait_set_validate` in `ctraits.c`. Specifically in case 3 - https://github.com/enthought/traits/blob/master/traits/ctraits.c#L4146-L4158 , where we call `PyInt_Check` on the item at index 2 in the `validate` tuple.

This is a Python 2 only check and this seems to be failing on windows because `PyInt_Check(<long int>)` returns False.

**Comment by mdickinson** [comment]
Simpler version: `Range(low=0, high=2**64-1)()` (which fails on macOS and Linux, too).

**Comment by mdickinson** [comment]
This is out of date: only applies to Python 2.
