### ISSUE TITLE
Documentation using default style for inline code snippets

### ISSUE THREAD

**Issue by jjenthought** [enthought/traits#422]
The current style setting for code uses the default style, which gives a font size noticeably smaller than regular text and no highlighting.
_____
<img width="846" alt="current_style" src="https://user-images.githubusercontent.com/39727845/49939561-1e9e9a80-fed5-11e8-9238-11817b3104ec.png">

This may be because our sphinx css file still uses a `tt` section, which was deprecated in HTML5.
Copying the settings from `tt` to a new `code` section makes things look a bit more like other projects documentation e.g. numpy, scipy. 
____
<img width="862" alt="alternative_style" src="https://user-images.githubusercontent.com/39727845/49939779-ab495880-fed5-11e8-8b61-89c9f9594cee.png">

Obviously this can be closed if it's a deliberate style choice!

**Comment by mdickinson** [comment]
That css file is apparently at least 8 years old. We _should_ be using the standard Enthought sphinx theme (https://github.com/enthought/enthought-sphinx-theme) for all this. The documentation configuration really needs revisiting / reworking.
