### ISSUE TITLE
Documentation configuration should be using Enthought sphinx theme

### ISSUE THREAD

**Issue by jjenthought** [enthought/traits#423]
As mentioned in #422, the documentation configuration would ideally be using the standard Enthought theme (https://github.com/enthought/enthought-sphinx-theme). This would make it more consistent with other projects, with the bonus of avoiding the compatibility problems which come from using an 8 year old css file (as we do currently)!

**Comment by rahulporuri** [comment]
closing as https://github.com/enthought/traits/pull/427 got merged.
