### ISSUE TITLE
Interface validation broken on Python 3

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#424]
On Python 2, the following statements work as expected. On Python 3, we get an assertion error.

```
from collections import OrderedDict
from traits.interface_checker import check_implements
from codetools.contexts.i_context import IContext

assert check_implements(OrderedDict, IContext) is True
```

This is because `check_implements` internally uses `_get_public_methods` on a non-`HasTraits` class object. See https://github.com/enthought/traits/blob/eecc23d698ad3d0d2f3ad2473f7e2c9d880267d9/traits/interface_checker.py#L160-L177 . 

In the specific example above, for example, `type(OrderedDict.__dict__['keys']) is types.FunctionType` is True on Python 2 but False on Python 3.

Note that the broken `check_implements` effects `validate_implements` function - https://github.com/enthought/traits/blob/eecc23d698ad3d0d2f3ad2473f7e2c9d880267d9/traits/trait_types.py#L2694-L2702

**Comment by rahulporuri** [comment]
one solution would be to replace the `type(...) is FunctionType` with a `callable(...)`.

**Comment by rahulporuri** [comment]
going further, the `_check_methods` method uses `inspect.getfullargspec`, which on Python 2 is actually `inspect.getargspec`. See https://github.com/enthought/traits/blob/eecc23d698ad3d0d2f3ad2473f7e2c9d880267d9/traits/interface_checker.py#L123-L145 

On Python 2 : 
```
In [1]: from collections import OrderedDict
In [2]: from inspect import getargspec
In [3]: getargspec(OrderedDict.__dict__['keys'])
Out[3]: ArgSpec(args=['self'], varargs=None, keywords=None, defaults=None)
```

On Python 3 :
```
In [1]: from collections import OrderedDict
In [2]: from inspect import getfullargspec
In [3]: getfullargspec(OrderedDict.__dict__['keys'])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/rporuri/.edm/envs/geo3/lib/python3.6/inspect.py in getfullargspec(func)
   1088                                        skip_bound_arg=False,
-> 1089                                        sigcls=Signature)
   1090     except Exception as ex:

/home/rporuri/.edm/envs/geo3/lib/python3.6/inspect.py in _signature_from_callable(obj, follow_wrapper_chains, skip_bound_arg, sigcls)
   2230         return _signature_from_builtin(sigcls, obj,
-> 2231                                        skip_bound_arg=skip_bound_arg)
   2232 

/home/rporuri/.edm/envs/geo3/lib/python3.6/inspect.py in _signature_from_builtin(cls, func, skip_bound_arg)
   2060     if not s:
-> 2061         raise ValueError("no signature found for builtin {!r}".format(func))
   2062 

ValueError: no signature found for builtin <method 'keys' of 'collections.OrderedDict' objects>

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-3-3ebd5efb6ffa> in <module>()
----> 1 getfullargspec(OrderedDict.__dict__['keys'])

/home/rporuri/.edm/envs/geo3/lib/python3.6/inspect.py in getfullargspec(func)
   1093         # else. So to be fully backwards compatible, we catch all
   1094         # possible exceptions here, and reraise a TypeError.
-> 1095         raise TypeError('unsupported callable') from ex
   1096 
   1097     args = []

TypeError: unsupported callable
```

The traits interface checker currently doesn't handle errors when calling `inspect.getfullargspec`

**Comment by mdickinson** [comment]
@rahulporuri So if I'm understanding this correctly, this issue isn't new, and isn't specific to Python 3. For example, on Python 2, the `assert` in the following fails:
```
from traits.api import Interface
from traits.interface_checker import check_implements

class IHasKeys(Interface):
    def keys(self):
        pass

assert check_implements(dict, IHasKeys)
```

**Comment by mdickinson** [comment]
> one solution would be to replace the `type(...) is FunctionType` with a `callable(...)`.

That matches what the `inspect` module does, so sounds like the right change to me. Alternatively, we could just use EAFP: pass it to `getfullargspec`, and if it doesn't raise, it's callable. But that doesn't fix the particular case that you're looking at, because `getfullargspec` _does_ raise for `OrderedDict.keys` (in spite of it being callable).

So our main problem is deciding how to deal with methods like `OrderedDict.keys`: those for which `callable` returns `True`, but `getfullargspec` fails. There are unfortunately a good few of these in the CPython core. We can fail, or we can issue a warning saying that we're unable to do the typecheck. Not sure I'd want to pass silently here.

TBH, I wouldn't recommend use of `check_implements` in new code, especially for non-HasTraits classes.

**Comment by rahulporuri** [comment]
> TBH, I wouldn't recommend use of `check_implements` in new code, especially for non-`HasTraits` classes.

Alas. We're using a `HasTraits` class and the call to `check_implements`/`validate_implements` is implicit during traits instantiation. Specifically when a subcontext is being set on the `DataContext` object.

> So our main problem is deciding how to deal with methods like OrderedDict.keys: those for which callable returns True, but getfullargspec fails. There are unfortunately a good few of these in the CPython core.

The reason why `OrderedDict` is specifically a Python 3 problem and not a Python 2 problem because in Python 3 it is a builtin. This is why checking a `dict` on 2/3 will fail. 

https://github.com/python/cpython/blob/7cd25434164882c2093ea41ccfc7b95a05cd5cbd/Lib/inspect.py#L2098-L2111 

> We can fail, or we can issue a warning saying that we're unable to do the typecheck. Not sure I'd want to pass silently here.

I'd prefer failing. Definitely not fail silently.

**Comment by mdickinson** [comment]
> The reason why `OrderedDict` is specifically a Python 3 problem and not a Python 2 problem because in Python 3 it is a builtin.

Yep, exactly; that's why this issue isn't really a Python 3 issue.

Though there's a bit more to it than being a builtin or not: if we replace the `FunctionType` check, then some builtins in Python 3 work quite happily under `getfullargspec`, while others don't. For example, try `int.from_bytes` or `math.sin` (which work), and compare with `OrderedDict.keys` (which doesn't).

**Comment by mdickinson** [comment]
> Alas. We're using a `HasTraits` class and the call to `check_implements`/`validate_implements` is implicit during traits instantiation. Specifically when a subcontext is being set on the `DataContext` object.

This part is no longer true on Traits master, since #630.

**Comment by mdickinson** [comment]
I think this is a non-issue now that we're no longer automatically doing interface checking anywhere in Traits. It only affect non-HasTraits classes, so to see this behaviour you'd have to deliberately invoke the interface checker on a non-HasTraits class, or mark such a class with a `@provides` decorator.

Closing.
