### ISSUE TITLE
ListStr doesn't accept Unicode strings

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#433]
This is not really a bug, but it's at least a surprise that may be worth documentation or deprecation.

On Python 2, `Str` accepts Unicode strings, and reproduces those Unicode strings at attribute get time. I'd expect a trait declaration `foo = ListStr()` to behave like `foo = List(Str())`, but it turns out that the former is implemented as `List(str)`, and therefore does _not_ accept Unicode strings:

```
>>> class A(HasTraits):
...     foo = ListStr()
...     bar = List(Str())
... 
>>> a = A()
>>> a.bar = [u"one string", u"two string"]
>>> a.foo = [u"red string", u"blue string"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/.edm/envs/testing2/lib/python2.7/site-packages/traits/trait_types.py", line 2337, in validate
    return TraitListObject( self, object, name, value )
  File "/Users/mdickinson/.edm/envs/testing2/lib/python2.7/site-packages/traits/trait_handlers.py", line 2313, in __init__
    raise excp
traits.trait_errors.TraitError: Each element of the 'foo' trait of an A instance must be a value of type 'str', but a value of u'red string' <type 'unicode'> was specified.
```

Possibly `ListStr` should be deprecated, with a recommendation to use `List(Str())` or `ListUnicode` instead?

**Comment by corranwebster** [comment]
This is now moot, as Python 2 support has been removed from master.

**Comment by mdickinson** [comment]
> Possibly `ListStr` should be deprecated,

... and we did this in #627, with a recommendation to use `List(Str)` instead.
