### ISSUE TITLE
Remove `_py2to3` module once other pieces of ETS are no longer using it.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#450]
The `traits._py2to3` module is a legacy of the pre-Traits 5.0 2to3-based code distribution. It's almost entirely redundant, and should be removed.

Unfortunately, despite being a private module, it's currently being used by Traits UI (see enthought/traitsui#496), and possibly by other ETS libraries. We should wait until there's a new release of Traits UI (and other relevant packages) before removing the code here.

**Comment by corranwebster** [comment]
Fixed by #639 and #644.
