### ISSUE TITLE
Pickling on Python 2 broken for many classes

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#452]
#373 broke pickling on Python 2

See particularly [this comment](https://github.com/enthought/codetools/pull/25#issuecomment-462571369) from @rkern in codetools issue #25:

> [enthought/traits#373](https://github.com/enthought/traits/pull/373) breaks pickling on Python 2 for many classes. Any `Instance` trait (of which `Supports` is a subclass) with a factory default (i.e. with `args=…` or `kw=…`) stores an instancemethod from `BaseInstance` on itself: https://github.com/enthought/traits/blob/master/traits/trait_types.py#L3139-L3143
> 
> This shows up in `MultiContext`, which declares a `subcontexts = List(Supports)` trait on the class, because when it attaches listeners to `subcontexts`, Traits copies over the `CTrait` from the class trait dict over to the instance trait dict in order to attach the instance-specific notification handlers.
> 
> This specific problem can mostly be gotten around if [enthought/traits#373](https://github.com/enthought/traits/pull/373) were to remove traits from the instance trait dict that look like they were so copied (e.g. check the identity of the `.handler`s on the `CTrait`s). The intent of [enthought/traits#373](https://github.com/enthought/traits/pull/373) was to only pick up those traits that were added with `add_trait()`, but `HasTraits._instance_traits()` returns a dict with both kinds.

**Comment by mdickinson** [comment]
I've just created a new "urgent" label just for this issue. We need to get this fixed.

**Comment by mdickinson** [comment]
Note that enthought/traitsui#514 is a slight variant of this that may not have the same underlying cause; in particular, it was observed on Python 3, not Python 2.

**Comment by corranwebster** [comment]
Based on the error, it seems like https://github.com/enthought/traitsui/issues/514 may be related to the fact that `Disallow` is a singleton via the `Disallow = Disallow()` pattern.

**Comment by mdickinson** [comment]
Here's a minimal reproducer. On Python 2.7, the script below fails with eecc23d698ad3d0d2f3ad2473f7e2c9d880267d9 (the merge commit for #373), and passes with 6208f6311a68ccdbc370eaf173a8c9fd315118b4 (the immediate parent of that commit on master).

```
import pickle

from traits.api import HasTraits, Instance


class Bar(HasTraits):
    foo = Instance(slice, (0, 10))


bar = Bar()
bar.on_trait_change(lambda: None, "foo")
print(pickle.dumps(bar))
```

**Comment by jjenthought** [comment]
This may not be anything new, but just in case..
Calling `__getstate__` adds an entry of the form 
`'__instance_traits__ ' : {'trait_name': <traits.traits.CTrait object at 0x134016e10>}` to the dict normally returned. I imagine this will go away if the underlying issues are fixed.
If we were intentionally adding this `__instance_traits__` item, it would be useful to have a note in the user manual similar to the one about the `__traits_version__` key which gets added to the getstate dictionary.

**Comment by mdickinson** [comment]
@jjenthought Right, #373 deliberately added the `__instance_traits__` entry to the `__getstate__` dictionary, to support pickling and unpickling of dynamically-added traits (i.e., those added using `my_has_traits_object.add_trait("new_trait", ...)`.) But we end up with things in `__instance_traits__` for other reasons, too, so we end up trying to pickling lots of things that we didn't originally intend to.

Probably the right fix is to keep track of the traits that were added using `add_trait` separately.

**Comment by bergtholdt** [comment]
I want to add another aspect of the maybe the same underlying issue:

```python
import numpy as np
from traits.api import (HasTraits, Int, Property, cached_property)

class A(HasTraits):
    a = Int(1)

    b = Property(depends_on=['a'])
    @cached_property
    def _get_b(self):
        return self.a + 1

    c = Property(depends_on=['b'])
    @cached_property
    def _get_c(self):
        return self.b + 1

obj = A()
import pickle
pickle.dumps(obj)
```
This code results in the error:

    AttributeError: Can't pickle local object 'cached_property.<locals>.decorator'

`b` and `c` are both Properties and have been handled as *transient* traits in 4.6 and not pickled. However in 5.0 `b` is added as an instance traits:

```python
obj._instance_traits()
Out[6]: 
{'a': <traits.traits.CTrait at 0x24d986e6438>,
 'b': <traits.traits.CTrait at 0x24d986e64e0>}
```

probably since it's part of a `depends_on`. One could fix the example by having `c` depend on `a`, but that would not fix the underlying issue of why `b` ends up as a instance trait. I don't know if it is necessary for it to be one so the `depends_on` mechanism would work. One other fix could be to filter out any transients traits from the instance_traits prior to pickling in the __getstate__ method. Again, I don't know the implications of that.

**Comment by mdickinson** [comment]
Honestly, I think the solution at this point is to revert #373, until we can find time to do it properly. The number of unintended side-effects at this point is too large. Pickling dynamically-added traits is a much harder problem than pickling regular traits, because for regular class-level traits all you need to serialise is the trait value, while for instance-level traits you need to serialise the `CTrait` itself (for future validation, etc.), and at the moment there are just too many things that aren't pickleable.

Possibly we should revisit only after Python 2 support has been dropped entirely.

**Comment by mdickinson** [comment]
#373 reverted in #452.
