### ISSUE TITLE
Traits, PEP 526 and PEP 557 Design Discussion

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#475]
Variable annotations and data classes seem to have natural synergies with Traits, so it would make sense to have a plan for Traits to perhaps move in that direction (particularly once we are comfortable with dropping Python 2 support).

Topics we should consider:

- are there ways to have Traits integrate with the tooling ecosystem around the `typing` module (eg. static type checking Traits with MyPy)?
- do we want to use type annotation syntax in trait definitions?
- do we want to make Traits more like `dataclasses` plus the observer pattern?
- if we do support type annotation syntax, do we want to migrate the codebase to it?  If so, what tooling do we need to support that?

See #460 for some preliminary discussion and something that we _don't_ want to do.

**Comment by corranwebster** [comment]
Thinking a bit about this and playing with some experiments.  It would be nice to be able to say:
```
class Foo(HasTraits):
    x: int = 10
```
and have that be equivalent to
```
class Foo(HasTraits):
    x = Int(10)
```
These are unambiguously analogous, but the former has the advantage of being able to hook into the developing type annotation ecosystem (Mypy, etc.). It would be moderately straightforward for Traits to recognise these and map the constructs of the `typing` module to equivalent Traits.  Even a subset of `typing` which covers the basic types and containers would be useful, even if it did not handle the more esoteric types.

Where things get awkward are with the extended features that Traits provide, such as metadata, bounds for ranges, computed defaults, custom Trait types, etc.  Run-time validation is strictly stronger than anything that can be expressed compile time.

Following the example of dataclasses, we could do something like:
```
class Foo(HasTraits):
    x: int = trait(10, transient=True)
```
or even adapt dataclass `field` and it's API (although not its implementation).  However digging in to things, this requires some "white lies" in the type annotations, claiming  that `trait(default: T, ...) -> T` when in fact it returns some sort of `Trait` class instance which needs to be `cast` appropriately.  It implies that whatever is doing this needs to be a function.

Finally, the current style of
```
class Foo(HasTraits):
    x: Int(10, transient=True)
```
can be made to work with mypy if whatever `Int(...)` produces advertises the descriptor protocol with appropriate type signatures–even if they are just stubs or if we do metaclass/decorator/`__subclass_init__` processing to replace it with something else.

**Comment by mdickinson** [comment]
Closing this: we've (at least partially) implementing typing stubs for Traits, and I don't think we want to go further in that direction right now.
