### ISSUE TITLE
setup.py attempts to import from traits._version

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#478]
We should exec the file instead of trying to import it.

Code link: https://github.com/enthought/traits/blob/d5d4aaf38d574813a27a8714a8f33d1f0853f894/setup.py#L80-L81

Related: enthought/traitsui#549

**Comment by rahulporuri** [comment]
I don't know what the right way to fix this issue is. I've seen a few different solutions, one of which is to use `runpy.run_path`. Is that the recommended approach?

**Comment by mdickinson** [comment]
I'd just read the file contents manually and then `exec` them in a controlled namespace.

**Comment by mdickinson** [comment]
Here's some example code stolen from another project:
```python
def read_version_info(version_file):
    """
    Read version number and git revision from the version file.

    Parameters
    ----------
    version_file : str
        Path to the file containing the version information.

    Returns
    -------
    full_version : str
        Full version string
    git_revision : str
        Git hash corresponding to this version.
    """
    filename, _ = os.path.split(version_file)
    with io.open(version_file, "r", encoding="utf-8") as f:
        code = compile(f.read(), filename, "exec")


    context = {}
    exec(code, context)


    return context["full_version"], context["git_revision"]
```

**Comment by mdickinson** [comment]
.. but `runpy.run_path` could work, too.

**Comment by mdickinson** [comment]
> .. but `runpy.run_path` could work, too.

And now having actually looked properly at what `runpy.run_path` does, I agree that this is the best solution.
