### ISSUE TITLE
Install enthought sphinx theme via edm

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#480]
Currently, when setting up the environment, in order to build docs, we install `enthought-sphinx-theme` from source i.e. github using pip. Now that the package is available via EDM, we should update the `install` command to use the edm package.

**Comment by mdickinson** [comment]
I think we should also drop the existing fallback code for the case where the EST isn't installed, and require that the sphinx theme be available in order to build the docs. Now that it's available on all of PyPI / EDM / GitHub, that doesn't seem like a big hardship.
