### ISSUE TITLE
Document use of post_init kwarg to on_trait_change

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#483]
The [Trait Notification](https://docs.enthought.com/traits/traits_user_manual/notification.html) section of the traits docs does not contain any mention of the `post_init` kwarg to `on_trait_change`.

**Comment by kitchoi** [comment]
The notification documentation is now on `observe` and it does mention `post_init`.
The documentation on `on_trait_change` has been moved to the appendix, but before that, a mention of `post_init` is added via https://github.com/enthought/traits/pull/1019

Closing?

**Comment by mdickinson** [comment]
> Closing?

SGTM
