### ISSUE TITLE
Unable to delegate to a method on a HasStrictTraits class 

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#484]
```
In [1]: from traits.api import Any, DelegatesTo, HasTraits, HasStrictTraits, Int

In [2]: class A(HasStrictTraits):
   ...:     an_int = Int
   ...:     def a_method(self):
   ...:         pass
   ...:     

In [3]: class A2(HasTraits):
   ...:     an_int = Int
   ...:     def a_method(self):
   ...:         pass
   ...:     

In [4]: class B(HasStrictTraits):
   ...:     a = Any
   ...:     an_int = DelegatesTo('a')
   ...:     a_method = DelegatesTo('a')
   ...:     

In [5]: a = A(an_int=1)

In [6]: a2 = A2(an_int=1)

In [7]: b = B(a=a)

In [8]: b2 = B(a=a2)

In [9]: b.an_int
Out[9]: 1

In [10]: b.a_method
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-b691afc8bb92> in <module>()
----> 1 b.a_method

AttributeError: 'A' object has no attribute 'a_method'

In [11]: b2.an_int
Out[11]: 1

In [12]: b2.a_method
Out[12]: <bound method A2.a_method of <__main__.A2 object at 0x7f6ef40db8f0>>
```

**Comment by rahulporuri** [comment]
I'm not sure if delegating methods is allowed in the first place as all examples regarding the use of `DelegatesTo` mention attributes, not methods.

**Comment by rkern** [comment]
`DelegatesTo` is not for methods, no. Only traits.

It happens to appear to work for `A2(HasTraits)` because the `DelegatesTo` causes an implicit `a_method = Python()` trait to be added to `A2`, which then gets resolved by the normal Python attribute mechanisms (i.e. failing to find anything in `__dict__`, then looking up instancemethods, etc.). But this is not an intended use of `DelegatesTo`.

**Comment by rahulporuri** [comment]
thanks for the explanation @rkern !

**Comment by rkern** [comment]
The right way to do this is just through normal Python mechanisms: define `a_method()` on `B` such that it  calls `self.a.a_method()`.
