### ISSUE TITLE
OddInt example failed due to validation done by fast_validate

### ISSUE THREAD

**Issue by sallenEnth** [enthought/traits#486]
The class OddInt in examples/tutorials/traits_4.0/trait_types/trait_types.py
fail to correctly validate a value. It is due to the fact that Int are validated with fast_validate rather than validate. You need to specialize method fast_valdiate for OddInt.

**Comment by mdickinson** [comment]
Inheriting from `BaseInt` instead of from `Int` should fix this.

**Comment by mdickinson** [comment]
Let's test and fix (if necessary) before 6.1.

**Comment by sallenEnth** [comment]
What I tried was to change the name of the method `validate` to `fast_validate` in the class `OddInt`. It solved the issue. But I am not sure that this is the best solution. I think it was Robert Kern who suggested to replace the class from which `OddInt` inherit from `Int` to `BaseInt`.
