### ISSUE TITLE
Refactor import checks - move into helper module

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#496]
We have tests which:

- check for existence of unittest.mock, and fall back to 3rd party mock if necessary
- check for existence of NumPy, in order to allow skipping of NumPy-related tests if NumPy is not present
- check for existence of Sphinx, in order to allow skipping of documentation-related tests if Sphinx is not present.

This all leads to repeated and ugly boilerplate in the imports sections. It would be nice to move some of this boilerplate into a helper module.

**Comment by corranwebster** [comment]
@mdickinson is this closed by #521?

**Comment by mdickinson** [comment]
Yes.
