### ISSUE TITLE
Tutorial runner code is duplicated in TraitsUI and Traits

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#505]
The infrastructure code in https://github.com/enthought/traits/tree/master/examples/tutorials in Traits and in TraitsUI is more-or-less the same (in particular `tutor.py`).  The code here likely has the same issue that was fixed in [traitsui #603](https://github.com/enthought/traitsui/pull/603), but more to the point we shouldn't be duplicating large sections of code across multiple projects like this.

A short-term potential fix might be to move the bulk of the `tutor.py` into `traitsui/extras` (where the "demo" app for traitsui is also located) and have the examples directories have simple main methods that import and invoke the main class with appropriate configuration.

An even better fix would be to have a single `tutor` entrypoint together with plugin system to contribute tutorials from different packages (this might be a good concrete example to live in Envisage?)

**Comment by mdickinson** [comment]
Specific tasks:

- [ ] See if we can replace our `tutor.py` with the version from TraitsUI.
- [ ] Filter examples: some should be removed; some should be in TraitsUI; some should stay.
- [ ] Test examples manually
- [ ] Framework for testing

**Comment by mdickinson** [comment]
Aim to get at least the first step in 6.1.0, the rest may come later.
