### ISSUE TITLE
Remove the `Category` class

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#506]
Traits 6.0.0 (or the first major version of Traits that drops Python 2 support) should remove the Category class and its uses.

Notes:

- this shouldn't happen before the beginning of 2020
- TraitsUI currently uses `Category` in the WX themes. Given that the wxPython backend won't work out of the box on Python 3, dropping categories for the next Python-3-only version of Traits won't add any additional breakage to wx.

**Comment by corranwebster** [comment]
See also #319

**Comment by mdickinson** [comment]
#510 deprecates the Category class.

**Comment by corranwebster** [comment]
Categories are now removed from TraitsUI master.  I think it is safe to include the removal in the next minor release, since they are (hopefully) an internal implementation detail.
