### ISSUE TITLE
on_trait_change swallowing arbitrary exception maybe unexpected

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#523]
If I want to validate a value being assigned to a trait, the first thing that comes to my mind would be to attach a trait change listener... except that does not work.

```
class Foo(HasTraits):

    bar = Unicode()

    @on_trait_change("bar")
    def _check_bar(self, value):
        self._check_value(value)

    def _check_value(self, value):
        if value == "meh":
            raise TraitError("I don't like your value.")


print("----")
print("Running Foo(bar='meh')")
Foo(bar="meh")

print("----")
print("Done.")

```

gives this, note that "Done" is printed.
```
----
Running Foo(bar='meh')
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <__main__.Foo object at 0x11724a360>, trait: bar, old value: , new value: meh
Traceback (most recent call last):
  File "/Users/kchoi/.edm/envs/resist-py36/lib/python3.6/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/Users/kchoi/.edm/envs/resist-py36/lib/python3.6/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "model.py", line 11, in _check_bar
    self._check_value(value)
  File "model.py", line 15, in _check_value
    raise TraitError("I don't like your value.")
traits.trait_errors.TraitError: I don't like your value.
----
Done.
```

This is because any exception occurs in trait change listener is swallowed (unless `push_exception_handler` is called or unless the exception is `TraitNotificationError` is raised, `TraitNotificationError` is the wrong thing to raise).

Instead, one has to workaround by either
(1) using a shadow trait and a property to do this kind of validation:
```

class Foo(HasTraits):

    spam = Property(Unicode)

    _spam = Unicode()

    def _check_value(self, value):
        if value == "meh":
            raise TraitError("I don't like your value.")

    def _set_spam(self, value):
        self._check_value(value)
        self._spam = value

    def _get_spam(self):
        return self._spam

```
or
(2) Define a custom trait

Both of which are a bit of an overkill.

This behaviour of exception being swallowed is probably widely used in GUI application.  However, that logic belongs to UI domain.

Maybe a backward compatible change is to add another argument to `on_trait_change` to allow exception to be propagated?

**Comment by corranwebster** [comment]
What is the desired behaviour on validation failure?

If it is to stop the process/crash the app, raising `SystemExit` (or similar) may be better than raising `TraitError`. (No idea if that will _work_, but it's worth a shot).

If the desire is to prevent the invalid value being set (and possibly consumed by other listeners) then you can't do it in a trait change handler - they are called _after_ the change has happened and possibly after other trait change handlers have already run.  In that case (1) or (2) seem like better approaches.

If the desire is to be notified that there is a problem, but continue running, then logging may be better than raising.

I can see the general desire to avoid silently swallowed exceptions, as they do mask bugs.

**Comment by kitchoi** [comment]
Thanks!

> If the desire is to prevent the invalid value being set (and possibly consumed by other listeners) then you can't do it in a trait change handler - they are called after the change has happened and possibly after other trait change handlers have already run. In that case (1) or (2) seem like better approaches.

You are right that I probably shouldn't use `on_trait_change` for validation even if it does not shallow the exception.  There can be multiple `on_trait_change` listeners for the same trait and they can be fired at any order (right?).  One can't prevent some other listener to have processed an invalid value, let alone the fact that the listener is called *after* the change has happened.

**Comment by kitchoi** [comment]
I think I have come to understand why these exceptions from notifiers are not propagated: the notifiers don't know each other, they can be contributed by multiple sources and they all need to be called even if any of them should fail.  We could collect all the failures after executing all of the notifiers and then propagate the collection of exceptions. However if a problematic notifiers were contributed by packages out of the developer's control, it will be a huge huddle to development. For testing, one could still use `push_exception_handler` to capture exceptions.
With that, I am closing this issue.

**Comment by mdickinson** [comment]
Yes, agreed: an exception from a notifier basically has nowhere to go: there's no code that can sensibly be catching that exception and doing anything with it (other than just logging it / printing it). And notifiers should be independent of one another.

One could imagine a framework where exception handlers can be chained (a bit like twisted does), but I don't think we want to go there right now.
