### ISSUE TITLE
Trait alias

### ISSUE THREAD

**Issue by AntoineD** [enthought/traits#535]
Hello,

I would like to use an existing trait by another name in a derived class: is it possible to declare a trait in a derived class as an alias of another trait from the base class?

Cheers,
Antoine.

**Comment by corranwebster** [comment]
There isn't a built-in way of doing it, but it is straightforward to use a `Property`, something like the following example form Chaco:

https://github.com/enthought/chaco/blob/b89b2e5c0935d79eef9e2928d32356c4043dc624/chaco/base_candle_plot.py#L16-L18

If you want to get trait notification to work as expected, you might need to add a `depends_on=name` to the `Property`'s arguments.

**Comment by corranwebster** [comment]
Also, I'd add for @mdickinson's benefit that this is a useful pattern, and something like this probably makes sense to add to core Traits.

**Comment by AntoineD** [comment]
Thanks a lot @corranwebster!
