### ISSUE TITLE
Sync trait event is broken when setting an empty slice on a list.

### ISSUE THREAD

**Issue by tmreay** [enthought/traits#540]
Encountering a trait error when setting an empty slice (or a slice without a first index).

Code to reproduce:
```python
from traits.api import *


class Foo(HasStrictTraits):
    data = List(Int)


foo = Foo(data=[-1, -2, -3])
bar = Foo(data=[])
foo.sync_trait('data', bar, mutual=True)
print(foo.data, bar.data)
bar.data[:] = [1, 2, 3]
print(foo.data, bar.data)
```

The problem is in `HasTraits._sync_trait_items_modified`. When you have a slice like this, the `index` attribute of the trait list event is `None`, causing the logic used to form the slice to fail.

**Comment by mdickinson** [comment]
I think we should be fixing this at the level of the `TraitListEvent`. The `None` is accidental, and we should be converting it appropriately.

After this setup:

```
>>> from traits.api import *            
>>> class Foo(HasTraits): data = List(Int)
... 
>>> foo = Foo(data=[1, 2, 3])
>>> def handler(list_event):
...     print("List event: ", list_event.__dict__)
... 
>>> foo.on_trait_change(handler, "data_items")
```

It doesn't make a lot of sense that these two assignments generate different event indices:

```
>>> foo.data[0:2] = [4, 5]
List event:  {'index': 0, 'removed': [1, 2], 'added': [4, 5]}
>>> foo.data[:2] = [6, 7]
List event:  {'index': None, 'removed': [4, 5], 'added': [6, 7]}
```

**Comment by mdickinson** [comment]
Also:
```
>>> foo.data = [1, 2, 3]        
>>> foo.data[:-3:-1] = [4, 5]
List event:  {'index': slice(None, -3, -1), 'removed': [[3, 2]], 'added': [[4, 5]]}
>>> foo.data[3:-3:-1] = [6, 7]
List event:  {'index': slice(3, -3, -1), 'removed': [[4, 5]], 'added': [[6, 7]]}
```
But I think this one's okay: it's fine to have a `None` *in* the slice.

**Comment by mdickinson** [comment]
Looks like this is the offending line: https://github.com/enthought/traits/blob/6e3b839adf98bc847a3ed210989259ce1140bf23/traits/trait_handlers.py#L2540

**Comment by mdickinson** [comment]
@tmreay Do you have a bandwidth to work up an alternative fix that turns the line above into something that has the effect of `index = 0` if `key.start` is None? You could keep the existing test from #545, but we'd probably want a more direct test, too.

It looks to me as though `__delitem__` needs a corresponding fix (and tests).

If you don't have bandwidth, that's fine: let me know, and I'll work up a fix.
