### ISSUE TITLE
Extended Property depends_on References tutorial bus error

### ISSUE THREAD

**Issue by cfarrow** [enthought/traits#6]
The tutorial entitled Extended Property depends_on References causes a bus error when run from the tutor application.
This is running all of ETS from the master on OSX 10.6.

Start tutor.py under traits/examples/tutorials and click on the mentioned tutorial.

A bus error also occurs in a traitsui tutorial, as reported here: https://github.com/enthought/traitsui/issues/3

**Comment by mdickinson** [comment]
Closing this as out of date. There are many issues with the examples, but this isn't one of them.
