### ISSUE TITLE
Invert ViewElement / ViewElements dependency on TraitsUI

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#610]
There's some gnarly code in `has_traits` where `ViewElements` and `ViewElement` are defined to be dummy objects, and then the actual definitions from TraitsUI are injected by `traits.api`.

Here's the `has_traits` piece: https://github.com/enthought/traits/blob/c9e34fc3947b96db149807a5eb18c394b6cbe192/traits/has_traits.py#L100-L115

and the corresponding `api` piece:
https://github.com/enthought/traits/blob/c9e34fc3947b96db149807a5eb18c394b6cbe192/traits/api.py#L228-L251

To remove this particular dependence of Traits on TraitsUI, I propose a different structure:

1. The `ViewElements` definition (currently in TraitsUI) should move to Traits.
2. A new `IViewElement` interface is added to Traits, and uses of `ViewElement` in Traits are replaced with uses of `IViewElement`. This interface represents the minimum that Traits needs to know about `ViewElements` in order to work with them at `configure_traits` and `edit_traits` level.
3. The `ViewElement` class in TraitsUI is registered with the `IViewElement` interface.

**Comment by mdickinson** [comment]
Actually, `ViewElement` is sufficiently simple that I don't think we need an interface here. So we just move `ViewElements` and `ViewElement` to Traits from TraitsUI.

**Comment by mdickinson** [comment]
Complications:

- `ViewElements.filter_by` uses the `View` class
- If `ViewElements` is moved to Traits from TraitsUI, the current `HasTraits` setup means that instances of `ViewElements` will be created before `ViewElements` is overwritten with the `TraitsUI` version.

**Comment by corranwebster** [comment]
The core problem here seems to be that these are needed by the core metaclass mechanisms in Traits.  The problems being addressed in the metaclass are:

1. Identifying things which look like they are "UI stuff" and tucking them away.
2. Handling MRO issues for looking them up.
3. Handling `Include` (which seems like it could be done elsewhere).

I think (1) is the only really essential thing, everything else can be done later at need.

**Comment by corranwebster** [comment]
Summarizing the situation at the moment after #614 and #617 plus [traitsui/#690](https://github.com/enthought/traitsui/pull/690) we are now in a stable state where either Traits or TraitsUI can be released without breaking the other.  We need at least one release of each before we can remove the scaffolding, which in this case would be:

- making TraitsUI dependent on the new release of Traits and removing the try... import from the `ViewElement` code
- removing the remaining import of traitsui from traits.api

**Comment by ievacerny** [comment]
> * removing the remaining import of traitsui from traits.api

Done in #1033

**Comment by mdickinson** [comment]
This issue can now be closed: `traits.api` no longer imports from `traitsui.api`.

**Comment by mdickinson** [comment]
Sorry, there's still an action here, but it's for TraitsUI. I'll open an issue there, if there isn't already one.

**Comment by mdickinson** [comment]
> I'll open an issue there, if there isn't already one.

I went one better and opened a PR: enthought/traitsui#1324
