### ISSUE TITLE
Example usage of the "_trait_notification_handler" in ctraits.c

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#618]
The `_trait_notification_handler` seems to be a debugging utility which isn't used anywhere in traits at the moment. Like `Undefined` and `Uninitialized`, `ctraits.c` expects to be provided a notification handler object (this is my understanding).

It would be nice to have an examples of how it can/should be used.

https://github.com/enthought/traits/blob/85ce258cda472de83c65da76522ccbc54cc32038/traits/ctraits.c#L5212-L5233

Note : I'm not sure how it's meant to be used and i'm not even sure if it works as expected/originally intended. The code was originally added in the commit - https://github.com/enthought/traits/commit/c5232d213bb139363716b40607514f7687dab49a

**Comment by mdickinson** [comment]
Get rid of it. It's unused, untested and undocumented. That qualifies it as legacy code.

**Comment by mdickinson** [comment]
Turns out it *is* used in `etsdevtools`. But etsdevtools is also legacy code.

https://github.com/enthought/etsdevtools/blob/bfbdf5926ed319e2edc4f5c910c21d21cbf515c1/etsdevtools/developer/tools/event_monitor.py#L183-L190
