### ISSUE TITLE
File and Directory traits (and BaseFile) should accept os.PathLike

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#642]
Once Python 2 support is removed, it would be nice to accept any object which implements the [`PathLike` interface](https://docs.python.org/3/library/os.html#os.PathLike), such as `pathlib.Path`.

For backwards compatibility these should be converted to strings via a call to `os.fspath` as part of the `validate` method (probably in `BaseFile` and the corresponding c-level fast validators).  We may want to do a similar conversion for default values.

**Comment by mdickinson** [comment]
Done in #736
