### ISSUE TITLE
Combine changelogs

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#650]
We have two changelog documents: one in the docs directory (going as far as Traits 3.5), and one at the root level of the repository (starting with Traits 4.3.0). It would be good to combine them into a single document, *and* make that document available as part of the generated documentation.

**Comment by mdickinson** [comment]
> _and_ make that document available as part of the generated documentation.

TraitsUI already does this; we can steal the mechanism from there.

**Comment by shoeb-github** [comment]
I will start working on this.

**Comment by mdickinson** [comment]
@shoeb-github Thanks. It's probably worth addressing this in two separate PRs: one for the simple job of combining the changelogs, and the other for the more involved job of including the changelog in the built documentation.
