### ISSUE TITLE
cTrait property method is awkward

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#673]
The cTrait `property` method has an awkward API.  If you want to turn a trait into a property, then you need to call it with 6 arguments (`getter`, `n_getter_args`, `setter`, `n_setter_args`, `validator`, `n_validator_args`).  If you want to get the information out of the trait, you call `property` with no arguments and it returns either the functions (but not the number of arguments) or `None` if the trait is not a property.

In particular the 6-argument version is nasty for a public API call.

Proposal 1: rename `cTrait.property` to `cTrait._property` and add a `CTrait.property` that does the argument counting before calling `cTrait._property`.

Proposal 2: make `property` a property on `CTrait` which wraps a `_property` property on `cTrait`.

These API changes are backwards incompatible, but are relatively safe as only usage in ETS is in Traits.

**Comment by mdickinson** [comment]
PR #825 (which should land in Traits 6.1.0) should eventually fix this issue.

**Comment by mdickinson** [comment]
Fixed by #967.
