### ISSUE TITLE
No longer special-case `TraitPrefixList`

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#676]
The `TraitPrefixList` handler can be replaced by a subclass of the `BaseStr` `TraitType` which uses the validator from `TraitPrefixList`.  It does not need any sort of special-case validating inside the ctraits.c code and so that code can then safely be removed (the c-level validator just calls back out to Python).

`TraitPrefixMap` can be handled in a similar way, but with additional logic to handle the mapped trait.

Outline of steps needed:

- [x] Introduce `PrefixList` trait type to replace `TraitPrefixList`
- [x] Introduce `PrefixMap` trait type to replace `TraitPrefixMap`
- [x] Replace uses of `TraitPrefixList` and `TraitPrefixMap` elsewhere in ETS
- [x] Wait until there are *releases* of all relevant ETS packages, so that the latest ETS releases no longer use `TraitPrefixList` or `TraitPrefixMap`
- [x] Deprecate `TraitPrefixList` and `TraitPrefixMap` in a Traits release.
- [ ] Remove `TraitPrefixList` and `TraitPrefixMap`, along with the fast validator, in a later Traits release.

**Comment by mdickinson** [comment]
We should keep this open for (a) replacement of `TraitPrefixMap`, and (b) eventual removal of the `ValidateTrait.prefix_map` validator.

**Comment by mdickinson** [comment]
@midhun-pm One next step for this would be to identify uses of `TraitPrefixList` elsewhere in ETS and make PRs to replace those uses with uses of the new `PrefixList` trait type. Once that's done, and once we also have the prefix map replacement, we can start thinking about deprecating `TraitPrefixList` and `TraitPrefixMap`.

**Comment by mdickinson** [comment]
I see uses of `TraitPrefixList` in Enable, Mayavi and TraitsUI, and `TraitPrefixMap` in apptools, Enable, and Mayavi.

**Comment by mdickinson** [comment]
(I edited the issue description to enumerate the steps needed to complete the issue.)

**Comment by larsoner** [comment]
Dealing with this deprecation was a bit tricky for me over in Mayavi, but I think it's taken care of (in addition to other bugs) in https://github.com/enthought/mayavi/pull/931/files

**Comment by mdickinson** [comment]
Thanks, @larsoner. I think we went a bit fast with this one, deprecating `TraitPrefixList` and `TraitPrefixMap` before the rest of ETS had had a chance to move to the replacement classes. (On the other hand, without the deprecation warnings, it's hard to motivate people to make the change.)

@prabhuramachandran would be the ideal person to review enthought/mayavi#931, but if he's not available we should be able to find someone from rest of the ETS team to take a look.

**Comment by prabhuramachandran** [comment]
@mdickinson -- I am hoping to do it (for sure) by this weekend.

**Comment by mdickinson** [comment]
Adding this issue to the 7.0.0 milestone: ideally, we should be aiming to remove `TraitPrefixList` and `TraitPrefixMap` in 7.0, but only if other ETS libraries have had a good chance to catch up.

**Comment by mdickinson** [comment]
Update: `TraitPrefixList` and `TraitPrefixMap` are no longer used elsewhere in ETS, and the latest releases of Enable and Mayavi no longer include references to TraitPrefixList or TraitPrefixMap.
