### ISSUE TITLE
TraitListObject should grow copy and clear methods

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#679]
This would allow some unification of paths between List and Set/Dict in a few places.

**Comment by mdickinson** [comment]
And `clear` too, while we're at it, to complete the list API. I think it's reasonable to consider the absence of `clear` to be a bug, since (presumably) it means we don't get the appropriate events when someone uses `clear`.

**Comment by mdickinson** [comment]
I've adjusted the title to include `clear`; it doesn't seem worth two separate issues, when both of these will likely be solved in a single PR.

**Comment by mdickinson** [comment]
This should go into the 6.0 release.

**Comment by mdickinson** [comment]
Just a historical note: during implementation we realised that implementing `list.copy` wasn't necessary; inheriting the superclass behaviour is just fine. So #732 only implemented `list.clear`.
