### ISSUE TITLE
Proposal : Expose int constants in the traits.ctraits module

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traits#686]
At the moment, we are defining a few constants in two places - e.g. `TRAIT_DICT_OBJECT_DEFAULT_VALUE` is defined in in `traits.ctraits` and in `traits.trait_handlers`.

Instead, we can use `PyModule_AddIntConstant` or `PyModuleAddIntMacro` to expose the variables defined in the `traits.ctraits` module - which can then be imported by others.

Ref : https://docs.python.org/3.6/c-api/module.html#support-functions

Note : There are a few constants that need to be defined (and used) in `traits.ctraits` e.g. trait kind value and the various type checks

**Comment by mdickinson** [comment]
That's reasonable. We should keep them private for now, though (possibly renaming to add a leading underscore).

Suggest opening a separate issue for introducing new constants; that's a different level of work.
