### ISSUE TITLE
Deprecate non-essential TraitHandler subclasses for 6.0 release?

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#697]
Here's the complete list of `TraitHandler` subclasses in current master.
```
>>> from traits.api import TraitHandler
>>> for cls in TraitHandler.__subclasses__(): print(cls.__name__)
... 
TraitCoerceType
ThisClass
TraitClass
TraitFunction
TraitEnum
TraitPrefixList
TraitMap
TraitExpression
TraitCompound
TraitTuple
TraitCallable
TraitList
TraitDict
```
Some of these are still central to Traits itself, like `TraitCoerceType` and `TraitCompound`. Others, like `TraitList` and `TraitDict` aren't needed by either Traits or by new code, and are largely unused in projects - the major uses are in other ETS libraries (apptools, pyface, mayavi).

I'm considering deprecating the less essential classes in Traits 6.0.0. A deprecation warning could be issued at instantiation time.

--- 

Update: `TraitCallable` is gone in #698. `TraitExpression` is removed in #699. `TraitClass` is removed in #710.

**Comment by mdickinson** [comment]
And for some of these classes, we may be able to simply remove them. `TraitCallable` appears to fit into this category.

**Comment by mdickinson** [comment]
`TraitExpression` can also go. `TraitThis` is used only in `ListThis` (which is itself deprecated), and nowhere else in ETS; I think both `TraitThis` and `ListThis` could safely be removed.

Everything else is either used by the general `Trait` machinery, or is used elsewhere in ETS.

**Comment by mdickinson** [comment]
> TraitThis

Sorry; I meant `ThisClass`. And unfortunately, `TraitInstance` subclasses `ThisClass` (somewhat randomly), and `TraitInstance` _is_ used fundamentally by the Traits machinery.

**Comment by mdickinson** [comment]
`TraitClass` is removed in #711

**Comment by corranwebster** [comment]
`ListThis` was modified so that it doesn't use `ThisClass` in #730.  It should be fairly easy to make `TraitInstance` inherit directly from `TraitHandler` by copying any code that is used from `ThisClass` and then `ThisClass` can be deprecated.

**Comment by mdickinson** [comment]
After a slew of PRs, the current status, and likely the Traits 6.0 status is:

Subclasses still present:
```
TraitCoerceType
TraitInstance
TraitFunction
TraitEnum
TraitPrefixList
TraitMap
TraitCompound
```

Subclasses deprecated:
```
TraitTuple
TraitList
TraitDict
```
