### ISSUE TITLE
Use importlib.import_module instead of __import__

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#707]
There are a number of places where Traits performs dynamic imports of symbols (eg. in `Instance` traits, trait_documenter, etc.).  In most of these cases, code is using `__import__` rather than `importlib.import_module`.  From the current Python docs:

> Direct use of `__import__()` is also discouraged in favor of `importlib.import_module()`.

We should replace uses of `__import__`.

Additionally, there is a lot of almost-duplicated code that looks a lot like the `traits.util.import_symbol` code.  We should try to unify this as much as possible.

**Comment by mdickinson** [comment]
Tentatively assigning to the 6.0 milestone; at least the `__import__` replacement, if not the unification.

**Comment by corranwebster** [comment]
Fixed by #712
