### ISSUE TITLE
Fast validator for Callable trait

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#718]
The Callable trait is currently implemented with a pure Python validate method (using the `callable` check, together with optionally allowing None.  This is a fairly commonly used trait.

The Python C API provides the `PyCallable_check` function, so it would be straightforward to provide a C-level validator.

**Comment by mdickinson** [comment]
This looks like a good first issue for someone diving into the C source for the first time.

**Comment by mdickinson** [comment]
One question: do we also want to introduce `BaseCallable` for subclassing purposes?

**Comment by kitchoi** [comment]
Yea I saw this pattern for `Int`, `CInt`, `Float` and `CFloat` etc.  That seem to be for differentiating traits that do not support coercions and traits that do.  Not sure if `Callable` has a similar use case...

**Comment by mdickinson** [comment]
> That seem to be for differentiating traits that do not support coercions and traits that do.

That's a separate thing: note that we have `BaseInt`, `BaseCInt`, `Int`, `CInt`, etc.

The point of `BaseCallable` would be to allow easy subclassing of something with `Callable`-like behaviour. Subclassing `Callable` directly is awkward because of the fast validation.

**Comment by kitchoi** [comment]
I see. Thanks. I don't see why not.

**Comment by kitchoi** [comment]
> I don't see why not.

I meant I don't see why not have a `BaseCallable` and then `Callable` subclasses it to provide the fast validator.

**Comment by mdickinson** [comment]
Opened #774 to track this. Re-closing here.
