### ISSUE TITLE
Deprecate Color, RGBColor and Font traits

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#728]
These really belong in Pyface or TraitsUI and are only in Traits for historical reasons.

The current definitions should be duplicated (probably) in `traitsui.toolkit_traits` and the actual trait implementations moved into the appropriate TraitsUI backends.

The functions should be modified to indicate that they are deprecated when called, and downstream libraries should replace them with `from traitsui.api import ...`.

**Comment by corranwebster** [comment]
TraitsUI PR: https://github.com/enthought/traitsui/pull/727

**Comment by mdickinson** [comment]
From offline discussion: we shouldn't deprecate until there's a way for users to respond to the deprecation warning, which means waiting for the next release of TraitsUI. Changing the milestone to 6.1.0.
