### ISSUE TITLE
TraitListObject misformats items_changed events on delete with extended slice

### ISSUE THREAD

**Issue by k2bd** [enthought/traits#742]
`TraitListObject.__delitem__` handles slices with steps !=1 specially:
https://github.com/enthought/traits/blob/d8d851e72ae9d32920eb9216a583484dda0dc4e1/traits/trait_list_object.py#L188-L190

This produces e.g. `[[9, 5]]` instead of `[9, 5]` for the `removed` part of the event on these lines:
https://github.com/enthought/traits/blob/d8d851e72ae9d32920eb9216a583484dda0dc4e1/traits/tests/test_traits.py#L1114-L1115

This doesn't match the behaviour found when e.g. list items are changed:
https://github.com/enthought/traits/blob/d8d851e72ae9d32920eb9216a583484dda0dc4e1/traits/tests/test_traits.py#L1104-L1105

Discussed offline, the current behaviour is intentional to reproduce legacy results

**Comment by mdickinson** [comment]
If we're going to change this, 6.0 might be a good release to do it in. It's technically a backwards-compatibility break, but it's one that's unlikely to affect much real code (deleting slices with a step != 1 is rare).

Note that this is not just about `__delitem__`, but about slice assignment, too:

```
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = List(Int)
...     def _foo_items_changed(self, list_event):
...         print(f"Event: index={list_event.index}, added={list_event.added}, removed={list_event.removed}")
... 
>>> a = A()
>>> a.foo 
[]
>>> a.foo.extend([1, 2, 3])
Event: index=0, added=[1, 2, 3], removed=[]
>>> a.foo[::2] = [4, 5]
Event: index=slice(None, None, 2), added=[[4, 5]], removed=[[1, 3]]
>>> del a.foo[::]
Event: index=0, added=[], removed=[4, 2, 5]
```

I'm +1 on changing this for 6.0.

There are some other oddities/inconsistencies, too: note the difference between `added` and `removed` in the following:
```
>>> del a.foo[::-1]
Event: index=slice(None, None, -1), added=[], removed=[[]]
```
