### ISSUE TITLE
TraitType subclasses for TraitMap, TraitPrefix and TraitPrefixMap

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#757]
`TraitMap` and `TraitPrefixMap` in particular get a lot of use, and there is no equivalent `TraitType`.  Versions of these which are based on `TraitType` will be needed before `Trait` and  `TraitHandler` can be retired.

**Comment by kitchoi** [comment]
Is deprecating `TraitMap` and `TraitPrefixMap` within the scope of this issue?

**Comment by mdickinson** [comment]
No. Let's do that separately, and keep this PR focused.

**Comment by mdickinson** [comment]
> this PR focused.

Gah. Issue. Not PR.

**Comment by kitchoi** [comment]
Okay!
I will open an issue for the deprecation.
(Note to self: Action to a deprecation means marking something as deprecated, which is not the same as removing a deprecated object)

**Comment by kitchoi** [comment]
Opened #941
