### ISSUE TITLE
Decide what to do with the examples directory

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#764]
The contents of the examples directory are out of date, are messy (currently excluded from style checks), and some examples belong in TraitsUI rather than Traits, or possibly in the ets-examples repo.

Related: #126, #756.

**Comment by corranwebster** [comment]
Also related #505

**Comment by mdickinson** [comment]
@corranwebster Ah, thanks; I think that makes this issue a duplicate (since there's nothing other than the tutorial in the examples directory). Closing here.
