### ISSUE TITLE
Create Union TraitType to replace Either

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#766]
Doesn't need to replicate the API of Either, but needs to catch the basic idea of accepting one of a collection of different TraitTypes

**Comment by rkern** [comment]
Can you state (or link to) the case that `Either` needs a replacement?

**Comment by corranwebster** [comment]
This is coming from offline discussion with @mdickinson.

`Either` is a thin wrapper around the `_TraitMaker` class, which is complex, creates `TraitHandler`s  rather than `TraitType`s - it's almost equivalent to `Trait`, with some differences in handling of default values, as best I can tell.  As a result, constructs like `Either([10, 11, 12], None, {'a': 1,'b': 2}, 4, 5, 6)` work, but behaviour is far from trivial to deduce and but are almost never what are actually used.

In almost all cases `Either` is actually used to provide a trait that allows a value to take one of a list of `TraitType`s or `TraitType` instances, sometimes with `None` to allow `None` as an option in addition to the trait types.  In these cases, code would be clearer and less error prone if the arguments were restricted to a list of traits with `allow_none` and `default` keywords (or some variation on this.  Because we don't want to break existing code, the proposal is to call this new trait type `Union` (which matches common concepts in type theory) and let downstream code migrate as needed.

This issue does not explicitly advocate for deprecating `Either` but I think it would be a good idea.  Pretty much all real-world use-cases can be replaced with something like `Union` and/or `Enum`.  For anything more complex, `Trait` would seem the right way to specify things.
