### ISSUE TITLE
DateTimeEditor tests should have conditional skip

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#797]
Two issues related to the `DateTimeEditor` tests:

- The tests are currently unconditionally skipped. Instead, they should check whether the `DateTimeEditor` is available, and only skip when it's not available.

- After I unskip, if I run against TraitsUI master, I get a test failure:

```
======================================================================
FAIL: test_editor_caching (traits.tests.test_editor_factories.TestDateTimeEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/traits/traits/tests/test_editor_factories.py", line 55, in test_editor_caching
    self.assertIs(editor_1, editor_2)
AssertionError: <traitsui.editors.datetime_editor.DateTimeEditor object at 0x12841d540> is not <traitsui.editors.datetime_editor.DateTimeEditor object at 0x1285f5cc0>
```

@midhun-pm Would you be able to look into this?

**Comment by midhun-pm** [comment]
The test fails if enabled because editor caching is not present, I'm not sure whether to not have this test removed or cache the editor in a global variable @corranwebster , had mentioned that caching may have to be removed if DateTimeEditor grows in options  https://github.com/enthought/traits/pull/737#discussion_r367346915 , any suggestions?

**Comment by mdickinson** [comment]
Is it the intention to have caching for the `DateTimeEditor`. If it is, then we need to update the code and the test can be left as is. If not, the test should be removed.

If we're not going to cache, then the global definition
```
DateTimeEditor = None
```
at the top of the `editor_factories.py` module should also be removed.

**Comment by mdickinson** [comment]
From @corranwebster's comment, it looks as though the decision was not to cache for now, which sounds fine to me. So let's remove the test, as well as the module-level `DateTimeEditor = None`.
