### ISSUE TITLE
File filters appear to be incompatible between Wx and PySide

### ISSUE THREAD

**Issue by Sharpie** [enthought/traits#8]
Using traits 4.0.0, the following filter works when the `wx` backend is in use:

```
File(filter = ["Any file (*.*)|*.*"])
```

However, when the Qt4 API is in use (using PySide 1.4.0), the following must be used:

```
File(filter = ["Any File (*.*)"])
```

**Comment by mdickinson** [comment]
Closing here; this is really a TraitsUI issue.
