### ISSUE TITLE
Indices not being built with documentation

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#809]
If you build the documentation such as via `etstool.py`:
```
python etstool.py install
python etstool.py docs
```
the generated documentation lacks indices.  If you go to the `Indices and Tables` links for either the User Guide or the API documentation, and then click on "Index" it tries to open a missing `genindex.html` file.

**Comment by mdickinson** [comment]
FWIW, the online 5.2.0 docs suffer from the same issue.
