### ISSUE TITLE
Allow Constant trait to have mutable values or restrict more types

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#819]
Currently the `Constant` trait rejects list and dict values because they are mutable, but does not reject sets or other mutable types.

We should be consistent: either prevent mutable values (eg. by checking for hashability, or using `collections.abc` mutable abcs) _or_ allow any value with the note that the values are shared at class level.

**Comment by mdickinson** [comment]
I vote for dropping the no-list-or-dict restriction. It's perfectly reasonable to have a list that's not expected to be mutated (`days_of_week = Constant(["Monday", "Tuesday", ...])`), and excluding lists encourages people to replace lists with tuples, where a list would have been more appropriate.

**Comment by midhun-pm** [comment]
I would expect `days_of_week.append("Someday")` to throw an error, but it will not, since the `Constant` trait currently only prevents new values being assigned to the trait.

**Comment by mdickinson** [comment]
Understood. The main problem is that it's just not realistic to prevent mutations to existing objects, so if we try to make that part of the`Constant` specification, we're inevitably going to do an incomplete job. It's easier and simpler (and clearer for people trying to understand what `Constant` does) if we simply say that it disallows assignments of new objects. In other words, it has exactly the same sort or immutability as a one-element Python `tuple` does: the object within the tuple can be mutated, but not replaced.
