### ISSUE TITLE
Split `cTrait.property` into two separate methods

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#825]
`cTrait.property` does double duty: when called with no arguments, it gets the current getter, setter and validator for a property trait. When called with three arguments, it sets those values.

It would be cleaner to have two separate methods for this.

**Comment by shoeb-github** [comment]
May want to consider the proposals in #673.

**Comment by midhun-pm** [comment]
@shoeb-github Thanks for linking the issue!

**Comment by midhun-pm** [comment]
Fixed in #967
