### ISSUE TITLE
Allow Enum traits to use Collections for valid values

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#835]
Currently Enum traits allow the valid values to be specified by `*args`, a tuple, list or `enum.Enum` (or in the case of dynamic values, something which is `Sequence`-ish, or `enum.Enum`).  Values like `ndarray`s and sets, which might make sense, are not supported.

The permitted signatures are:
```
Enum(default, value_2, value_3, ..., value_n)
Enum(default, values)  # default in values should be True but is not tested
Enum(values)
Enum(default, values="trait_name")
Enum(values="trait_name")
```
the way that cases 2 and 3 are distinguished from case 1 is by the count of arguments and the type of the last argument - it is explicitly checked to be one of tuple, list or enum.Enum

Thinking more generically, the set of valid values of an `Enum` trait needs to support:

- containment: is a value in the valid values or not?
- being finite and repeatably iterable (needed for `EnumEditor` values)
- some way to get a default value if it is not supplied by the user (particularly for dynamic values).

This corresponds more-or-less to the [`Collection` ABC](https://docs.python.org/3/library/collections.abc.html#collections.abc.Collection).  It provides:

- `__contains__`
- `len` and `__iter__`
- a default can be obtained by iterating and grabbing the first value returned

The biggest problem with using `Collection` in the place of the current set of permitted types is that strings are `Collection`s and that would break things like:
```
Enum("yes", "no")
```
which would get turned into something equivalent to:
```
Enum("yes", ("n", "o"))
```
This is not desirable.

So the proposal is the following:

- keep behaviour the same for `Enum(default, value_2, value_3, ..., value_n)`
- for `Enum(default, values)` and `Enum(values)` cases, test for the last value being a `Collection` which is not a `ByteString`.
- for `Enum(default, values=...)` or `Enum(values=...)` if `values` is a string, behave as now; otherwise treat it as an object which satisfies the `Collection` interface (even if it has not been registered as one).
- the only place where type testing is done is in the `__init__` to determine the signature, otherwise the interface is assumed, otherwise we use duck typing
- dynamic values should satisfy the `Collections` interface, but it won't be tested for.
- documentation will warn about using unordered collections like `set` where the `default` may well be a random element of the `set`.

There are corner-cases where this changes behaviour (eg. `Enum(1, {1, 2})` will behave differently), but they should be rare and can easily be fixed (eg. `Enum([1, {1, 2}])`).

An alternative would be to insist on `Sequence` rather than `Collection` in all of the above.

**Comment by mdickinson** [comment]
> * test for the last value being a `Collection` which is not a `ByteString`.

We'll also want to exclude the `str` type somehow. (That's probably _more_ important than excluding bytestrings.)
