### ISSUE TITLE
Should `File` and `Directory` traits allow bytestrings?

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#873]
The `File` and `Directory` trait types currently inherit from `BaseStr`, and so expect a (Unicode) string. However, the `os.PathLike` interface available from Python 3.6 onwards allows `__fspath__` to return either a bytestring or a (Unicode) string. I believe there are good reasons for this: on some filesystems, paths and filenames are more naturally regarded as bytestrings than text strings.

It's possible that we should be allowing both bytestrings and text strings here.

It would be worth investigating the CPython decisions that led to `os.PathLike` being allowed to return bytes, and the applicability and appropriateness of paths as bytestrings.

If we were to change this, we'd also want to drop the inheritance of `BaseFile` and `BaseDirectory` from `BaseStr`. (In my mind, that inheritance is already questionable, given that we're overriding almost all of what's in `BaseStr`.)

**Comment by corranwebster** [comment]
I think the answer is that it might be a good idea to accept `bytes` but the `validate` method should convert to a `str` via [fsdecode](https://docs.python.org/3/library/os.html#os.fsdecode).  I think that means that we don't need to drop `BaseStr` as a base class to support this (the object stored _is_ a string, the behaviour is not too different from `CBaseStr`), although it might not be a bad idea anyway.

Or we can just move towards a `Path` trait as the preferred solution.

**Comment by mdickinson** [comment]
I'm inclined to say that we shouldn't act on this until we have evidence of a system someone cares about returning bytestrings from `__fspath__`.

**Comment by mdickinson** [comment]
... and I've just checked that `Path.__fspath__` *always* returns a `str`, so the corner cases would involve 3rd-party path representations other than `Path.__fspath__`.

Let's close this. It's likely not an issue in practice, and right now the result of getting `bytes` back from `__fspath___` is, I think, the best one possible: we get an immediate `TypeError`, turning into a Traits bug report, and giving the opportunity to better understand just how important this use-case is.

**Comment by mdickinson** [comment]
> Or we can just move towards a `Path` trait as the preferred solution.

Yep, I wouldn't be opposed to this.
