### ISSUE TITLE
Decide if we want C level fast validation for `Directory` trait.

### ISSUE THREAD

**Issue by shoeb-github** [enthought/traits#877]
PR #867 adds `os.PathLike` support for `Directory` trait with the validation done in Python. There is no C level fast validation because directory existence checks may not be significantly faster in C than in Python. Also, the `PyOS_FSPath` utility is not available in Python 3.5 which means it is not straightforward to do `os.PathLike` C validation in Python 3.5 anyway.

xref: #851, #873, #876

**Comment by mdickinson** [comment]
I suspect we don't want or need a fast validator.

But one thing we should do is perform timings with and without fast validation, to see what the impact of fast validation is. If there's no significant impact even on a microbenchmark, it's not worth having. If there _is_ significant impact on a microbenchmark, we still need to decide whether it'll make a difference in anything real.

The annoying part of this is that we'll still want to keep `BaseDirectory` _and_ `Directory`, even though at that point they'll be identical: with the current Traits naming scheme, users would expect to subclass from `BaseDirectory`, but use `Directory` in actual Trait definitions. But I don't see any reason why we couldn't make them direct aliases: `BaseDirectory = Directory`.

Topic for another day: can we make the regular TraitTypes easier to subclass and remove the need for the `Base*` variants altogether? All we need is some mechanism to override existing fast validation.

**Comment by mdickinson** [comment]
> Also, the `PyOS_FSPath` utility is not available in Python 3.5 which means it is not straightforward to do `os.PathLike` C validation in Python 3.5 anyway.

Right, but we don't need to: for Python 3.5, we'll continue to only accept plain old strings. That does mean that the C code would need to distinguish between 3.5 and >= 3.6, but that shouldn't be hard.

**Comment by mdickinson** [comment]
Closing this; it's not worth it until/unless we have evidence that the lack of a fast validator is an actual bottleneck.

(See also #870).
