### ISSUE TITLE
Flake8 copyright header plugin does not handle #!

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#884]
Code with an executable escape at the start does not validate correctly.  Eg.
```
#! /usr/bin/env python

# (C) Copyright 2005-2020 Enthought, Inc., Austin, TX
# All rights reserved.
#
# This software is provided without warranty under the terms of the BSD
# license included in LICENSE.txt and may be redistributed only under
# the conditions described in the aforementioned license. The license
# is also available online at http://www.enthought.com/licenses/BSD.txt
#
# Thanks for using Enthought open source!
```
gives an error  `H103 Wrong copyright header found`.

This will presumably happen with text encoding headers as well.

A potential fix is to use `search()` rather than `match()` on line 177; alternatively since we know the location of the first copyright statement we could use `match()` but excise the first few lines.

**Comment by mdickinson** [comment]
Urrgh. I don't _want_ to handle that line in anything in Traits. If the change is made outside Traits, fine with me, but nothing inside Traits should want or need a shebang line.

**Comment by mdickinson** [comment]
General question: what examples do we have of things that need a shebang line? (And what does Windows do with those things?)

**Comment by mdickinson** [comment]
> This will presumably happen with text encoding headers as well.

Those are also unnecessary and undesirable within the Traits codebase: now that we're on Python 3, we can safely rely on all source files being UTF-8 encoded. (The original copyright_header checker *did* have support for coding cookies, but I stripped it out.)

**Comment by mdickinson** [comment]
@corranwebster I'd like to close here: I don't think there's anything to be done for Traits itself. I'm open to adding support for coding cookies and shebang lines in a version of the header checker that lives outside this repo (though I'd like to understand the need for that support first).

**Comment by corranwebster** [comment]
This came from wanting to re-use in another project which did have scripts with a shebang and I hacked a solution there.  I mainly raised it here as it looked to me as if you might have _meant_ to have it cover those situations given that the initial search for copyright headers allows for the possibility that they might not occur at the very beginning.

Feel free to close.

**Comment by mdickinson** [comment]
Hmm; I see. It's true that the logic and the message could use some improvement here: I _do_ want to check that the copyright header is at the top of the file, but if it isn't, then "Incorrect copyright header" seems like the wrong message.

**Comment by mdickinson** [comment]
So this needs a fix. Which in turn means I actually need tests for the copyright header checker. Darn.

**Comment by mdickinson** [comment]
Closing as out-of-date: we'll transition to the flake8-ets package soon.
