### ISSUE TITLE
Breakage in Traits 6.0.0 from default value imports

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#890]
One Traits-using project has this line at the top of a module:
```python
from traits.trait_handlers import CONSTANT_DEFAULT_VALUE
```

This breaks with Traits 6.0.0rc0, where what's needed is:
```python
from traits.api import DefaultValue
```

... and then uses of `CONSTANT_DEFAULT_VALUE` can be replaced with `DefaultValue.constant`. For a forwards-compatible fix, projects can rewrite their code right now as:

```python
try:
    from traits.api import DefaultValue
    CONSTANT_DEFAULT_VALUE = DefaultValue.constant
except ImportError:
    # Backward compatibility with Traits < 6.0.0
    from traits.trait_handlers import CONSTANT_DEFAULT_VALUE
```

and then clean up the code later when compatibility with Traits < 6.0 is no longer required.

The question is whether we should fix this in Traits for Traits 6.0.0.

On one hand, the fix is easy: we add the constants back and mark them as deprecated. On the other hand, if we do that then we risk projects not making the replacement, and we'll hit exactly the same issue next time around when we try to remove them (e.g., for Traits 7.0.0). It's not easy to deprecate the constants in such a way that use of them gives a `DeprecationWarning`, so projects will have no trigger for making the change.

One other aspect: the named constants for the default value handling were only introduced fairly recently, so there's unlikely to be old code out there that's using them, and in general I don't expect similar widespread breakage.

On balance I'm inclined *not* to re-add the constants in Traits. Other opinions?

**Comment by corranwebster** [comment]
I agree with not adding in the constants.

**Comment by mdickinson** [comment]
Traits 6.0.0 is released, without the constants. Closing.
