### ISSUE TITLE
Trait listener special cases are not easily discoverable in the docs

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traits#893]
I am using traits 5.2.0. Here's an example:
```python
from traits.api import Dict, HasTraits, Instance, Int, on_trait_change, Str

class A(HasTraits):
    x = Int()

class B(HasTraits):
    d = Dict(key_trait=Str(), value_trait=Instance(A))

    @on_trait_change('d.x')
    def _say_hi(self, new):
        print('hi', new)

if __name__ == '__main__':
    b = B()
    b.d = {'one': A()}
```
This produces:
> traits.trait_errors.TraitError: on_trait_change handler signature is incompatible with a change to an intermediate trait

However, if the listener signature is changed to say, `on_trait_change('d:x')` or `on_trait_change('d')` then things work as expected.

**Comment by rkern** [comment]
Since `'d.x'` fires whenever `b.d` is assigned or `b.d.x` is assigned, then the 1-argument form (just the new value, which can either be `d` or `x`, depending) is ambiguous. For such listeners, use the full `object, name, old, new` form.

This is documented: https://docs.enthought.com/traits/traits_user_manual/notification.html#dynamic-handler-special-cases

**Comment by notmatthancock** [comment]
Thanks. It would be helpful if the paragraph above in the examples section alluded to this. Specifically, I'm referring to:
> For a pattern that references multiple objects, any of the intermediate (non-final) links can be traits of type Instance, List, or Dict. In the case of List or Dict traits, the subsequent portion of the pattern is applied to each item in the list or value in the dictionary. For example, if self.children is a list, a handler set for 'children.name' listens for changes to the name trait for each item in the self.children list.

Perhaps a note at the end linking to the special cases section?

**Comment by rkern** [comment]
Write up the language you think would have been helpful in a PR.
