### ISSUE TITLE
Documentation front matter is outdated

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#902]
The documentation front matter in `front.rst` needs to be updated: it still refers to the old Enthought address (515 Congress).

**Comment by mdickinson** [comment]
We should fix this for Traits 6.1.0.

**Comment by corranwebster** [comment]
What I did for TraitsUI was merge this into the index.rst, putting the license in a "License" section after the table of contents.

This might make the PDF build less pretty, but I think that's OK.
