### ISSUE TITLE
Envisage test suite segfault with Traits master

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#906]
It looks as though PR #885 broke something fundamental: the Envisage test suite is now segfaulting for me on Traits master, and git bisect leads to the #885 merge commit.

**Comment by mdickinson** [comment]
Okay, looks like a missing `Py_INCREF` here: https://github.com/enthought/traits/blob/9a8a9b1060dfbc115d0b67a350fb63fe1a7d96da/traits/ctraits.c#L4097

Easy to fix, but needs a regression test.

**Comment by midhun-pm** [comment]
@mdickinson Thank you for finding the bug and fix.
I've made the fix (PR: #907) , but am unable to reproduce the segfault, I get a different error when running the envisage test suite with Traits master. 

The way I test is by first running `python etstool.py install` for `envisage`, then removing `traits-6.0.0` with `pip` and installing Traits-master by running `setup.py`  in the corresponding envisage environment. 

After which, I run the test suite and get the following error:
`  File "/home/midhun/Documents/Enthought/envisage/envisage/service_registry.py", line 268, in _resolve_factory
    obj = obj(**properties)
TypeError: __call__() missing 4 required positional arguments: 'object', 'trait_name', 'old', and 'new'`

**Comment by mdickinson** [comment]
This was fixed in #907.
