### ISSUE TITLE
Fix documentation title version dependence

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#908]
The documentation title depends on the major version, which is a recipe for embarrassingly outdated documentation titles. (See #903, #905). We should either do away with the version number in the title (I think it may have mattered substantially for Traits 3 versus Traits 4, but doesn't so much any more), or generate it dynamically.

**Comment by corranwebster** [comment]
I think 2->3 was the big jump, but yes, either have a more detailed version number, or remove entirely.

**Comment by mdickinson** [comment]
> have a more detailed version number

Good point: major-number-only is almost certainly not the right thing, even if we want a version number. If we do keep the version number, I'd suggest major.minor. (Bugfixes shouldn't generally have an effect on documentation, and we don't always regenerate docs for each bugfix release.)

**Comment by mdickinson** [comment]
Adding this to the to-do list for the 6.1.0 release.
