### ISSUE TITLE
Refactor call_notifiers in ctraits.c

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#914]
There are a number of potential improvements in `call_notifiers`.

- [x] use PyTuple_pack to create the tuple
- [ ] unify the two loops over `tnotifiers` and `onotifiers`
- [ ] test for no notify flag before doing anything
- [ ] possibly combine the two lists of notifiers into one new list rather than copying both independently

**Comment by mdickinson** [comment]
First part is done in #915 (since I already had the code changes). I'm not planning to work on either of the other two parts in the immediate future.

**Comment by mdickinson** [comment]
@kitchoi Can we close this issue? It looks to me as though your work in #918 completed this.

**Comment by kitchoi** [comment]
Yes thank you for reminding me! Closing.
