### ISSUE TITLE
Consider ditching coverage

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#919]
The codecov.io comments aren't currently being useful: they tend to report coverage diffs in unrelated files. It may make sense to ditch the coverage reports.

See for example #917, which reports coverage changes in unrelated files.

Core Python is currently having a similar discussion. See https://bugs.python.org/issue39704

**Comment by kitchoi** [comment]
This is still an issue as of today...e.g. https://github.com/enthought/traits/pull/1102#issuecomment-630682999

I think I have been ignoring codecov :/
