### ISSUE TITLE
Mark TraitMap and TraitPrefixMap as deprecated

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#941]
`TraitMap` is superseded by `Map` and `TraitPrefixMap` is superseded by `PrefixMap` (see #886)

This issue is for marking these two classes as deprecated (not removing them, yet).

Motivated by being able to retire `Trait` and `TraitHandler`.
See #697 for previous effort to retiring `TraitHandler`.

**Comment by kitchoi** [comment]
To clarify: I think we prefer wrapping `__init__` with the `deprecated` decorator so that users can respond to the deprecation warning emitted, i.e. we don't not just mention the deprecation in the docstring/comment.

**Comment by mdickinson** [comment]
> I think we prefer wrapping `__init__` with the `deprecated` decorator so that users can respond to the deprecation warning emitted

Agreed. One place where we held off on that for Traits 6.0 is with deprecation of the `Unicode` trait type, because I'm expecting that it's currently fairly widespread in existing code. We may want to turn on explicit deprecation warnings for 6.1 for `Unicode`, `Long` and related classes.

**Comment by kitchoi** [comment]
I also found this PR: https://github.com/enthought/traits/pull/770/files
Looks like we can just repeat pretty much the same changes for `TraitMap` and `TraitPrefixMap`.
