### ISSUE TITLE
TypeError Test Failure for 6.0.0

### ISSUE THREAD

**Issue by TheChymera** [enthought/traits#943]
After the current version bump to `=traits-6.0.0` on Gentoo Linux, a test fails with

```
TypeError: getattr(): attribute name must be string
```

Here is the full [build.log](https://github.com/enthought/traits/files/4352150/build.log). Can you help me out?

**Comment by corranwebster** [comment]
Traits is no longer using `nose` for its CI; you might try changing the build script to run using `python -m unittest discover` instead.  The `etstool.py` script invocation of testing (https://github.com/enthought/traits/blob/master/etstool.py#L249) may help as a guide.

**Comment by mdickinson** [comment]
The error appears to come from `nose` identifying the `find_test_pickles` helper function as a test. We could rename the function to avoid the false positive.

**Comment by mdickinson** [comment]
Fix in #944. But as @corranwebster says, it would make sense to update your test script to use `unittest` if possible.
