### ISSUE TITLE
Dynamic default ignored when invalid

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#971]
From [comment by @kitchoi](https://github.com/enthought/traits/pull/968#discussion_r400307761) in #968.

After:
```
from traits.api import Enum, HasTraits, List, Str

class CompetingDefault(HasTraits):
    states = List(Str)

    state = Enum("TX", values="states")

    def _state_default(self):
        return "NY"
```

the default provided by `_state_default` takes precedence, as expected:
```
>>> CompetingDefault(states=["MA", "PA", "NY"]).state
'NY'
```

but if that default fails validation, we fall back to the first listed state as the default:
```
>>> CompetingDefault(states=["MA", "PA"]).state
'MA'
```

I'd expect to get a `TraitError` from the failed validation in that second case.

**Comment by mdickinson** [comment]
This isn't a bug: it's deliberate behaviour on the part of `Enum`. It's a by-product of the "feature" that ensures that a dynamic enumeration always produces a valid value at get time, even in the face of a changing underlying collection:

```
>>> c = CompetingDefault(states=["FL", "MA", "NJ"])
>>> c.state = "NJ"
>>> c.state
'NJ'
>>> c.states.remove("NJ")
>>> c.state
'FL'
>>> c.states.append("NJ")
>>> c.state
'NJ'
```

This is similar to the way that the dynamic `Range` behaves if you change the `low` or `high` bounds so that the current value becomes invalid. It's problematic in a number of respects, especially that we don't get any notification for the change in `c`, but it's not actually a bug, and changing this would likely break code.

**Comment by kitchoi** [comment]
> It's problematic in a number of respects, especially that we don't get any notification for the change in c.state

Indeed... it is #529.
