### ISSUE TITLE
Document meaning and use of TraitList notification arguments

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#997]
`TraitList` calls its notifiers with a triple `(index, removed, added)`.

On current master, we have per-method descriptions of the contents of this triple in the docstrings. Those descriptions are removed in #989. I don't think the individual docstrings are the right place for the descriptions, but this does need to be documented _somewhere_, ideally both at docstring level _and_ user documentation level.

**Comment by mdickinson** [comment]
Note that there are also some unclear choices to be made, and we might want to revisit some of the existing behaviour. For example, `extend` provides a slice for the index, but it's not clear to me why that's better than the `TraitListObject` behaviour of giving a single integer index.

**Comment by mdickinson** [comment]
Another note: the documentation should be aimed at *consumers*, which in this case means the notifiers: those consumers in general won't want or need to know which particular operation generated the notification (e.g., append versus extend versus insert); they just need to know how to interpret the notification. It's not 100% clear to me right now that there's sufficient information in the arguments to be able to reverse engineer the previous state of the list (should that be necessary).

**Comment by mdickinson** [comment]
Here's an attempted articulation of the current `TraitList` behaviour, which (in contrast to the `TraitListObject` behaviour) is fairly clean:

- for operations which add, remove, or replace a single item, the `index` should be a plain integer. So that covers `append`, `insert`, `pop`, `remove`, `__delitem__` with an integer index, and `__setitem__` with an integer index.
- for all operations with the potential to add / remove / replace several items, the index will always be a slice. So that's `__iadd__`, `__imul__`, `clear`, `extend`, `reverse`, `sort`, `__delitem__` with a slice index, and `__setitem__` with a slice index.
- whether we get an integer or a slice for `index` should depend purely on the _type_ of the operation performed (with setitem-with-index and setitem-with-slice regarded as distinct operations, and similarly for delitem).
- it should be clarified in the docs that `added` and `removed` are _always_ lists of elements, so that a notifier can safely iterate over `added` and/or `removed` without the inconvenience of checking the type of the index

For the plain integer index case, interpretation and reconstruction is straightforward: `added` and `removed` can contain at most a single list element each (and at least one of them will be nonempty).

For the slice index case, it's messier. A clear description of the semantics would really involve *two* slices: one describing the removed items and one describing the added items. (This is one of the reasons that I think a rich object in place of the `(index, removed, added)` could make sense: that rich object could grow helper methods that help notifiers obtain whatever information they need.)

**Comment by mdickinson** [comment]
Having thought about this some more, I think we're doing this wrong, and the old meanings were better:

- For notifications that provide a slice, we're using the end-point of the slice inconsistently: sometimes it indicates the added items (e.g., for `extend`) and sometimes it indicates the removed items (e.g., for `__setitem__` with a slice).
- As a special case of the above, we have cases where essentially the _same_ operation expressed in different ways gives different slices: e.g., `l.extend([1, 2])` gives a different slice from `l[len(l):] = [1, 2]`.

So I think it's going to be unclear to notifiers how to interpret the information, when they need it.

For the majority of operations (everything that doesn't use _extended_ slicing), the operation can be expressed as removing some elements and adding some new ones at a particular well-defined insertion point, and that insertion point makes sense both with respect to the new list and the old one. So I think using a single index (which is what `TraitListObject` does) for these cases is the cleanest thing to do.

For __delitem__ and __setitem__ with an extended slice, we have no choice but to use a slice as an index. But that's no so bad, because in the __setitem__ case in particular the number of items added must exactly match the number of items removed, so there's less ambiguity.

**Comment by mdickinson** [comment]
And a question for `__delitem__`: if we know (a) the slice used to delete items, (b) the items removed, and (c) the contents of the new list, can we reliably reconstruct what the operation did?

**Comment by mdickinson** [comment]
> And a question for `__delitem__` with extended slicing [...]

Answer: yes, we can always reconstruct: we know the original length of the list, so from that and the slice we know exactly which positions items were removed from. Here's code to do that reconstruction:
```
def reconstruct(x, s, removed):
    """ Recreate a list x following a `del x[s]` operation. """
    l = len(removed) + len(x)

    step = 1 if s.step is None else s.step
    if s.start is None:
        start = l - 1 if step < 0 else 0
    elif s.start < 0:
        start = max(s.start + l, -(step < 0))
    else:
        start = min(s.start, l - (step < 0))
    pairs = zip(range(start, start + step * len(removed), step), removed)
    for i, item in reversed(list(pairs)) if step < 0 else pairs:
        x.insert(i, item)


# Testing

from itertools import product, starmap

slice_values = list(range(-30, 31)) + [None]
for n in range(10):
    x = list(range(n))
    for s in starmap(slice, product(slice_values, repeat=3)):
        if s.step == 0:
            continue
        x_copy = x.copy()
        del x_copy[s]
        reconstruct(x_copy, s, x[s])
        assert x_copy == x
```

**Comment by corranwebster** [comment]
Currently we have the following in the docs:
```

For these handlers the *new* parameter is a :index:`TraitListEvent`,
:index:`TraitSetEvent` or :index:`TraitDictEvent` object whose attributes
indicate the nature of the change and, because they are Event handlers, the
*old* parameter is Undefined.

All of these event objects have **added** and **removed** attributes that
hold a list, set or dictionary of the items that were added and removed,
respectively.

The TraitListEvent has an additional **index** attribute that holds either
the index of the first item changed, or for changes involving slices with
steps other than 1, **index** holds the _slice_ that was changed.

The TraitDictEvent has an additional **changed** attribute which holds the
keys that were modified and the _old_ values that those keys held.  The new
values can be queried from directly from the trait value, if needed).
```

I'll modify this depending on how it meshes with the reality of the head of the master branch.

**Comment by mdickinson** [comment]
Those docs for the `TraitListEvent` look pretty good to my eyes: I don't see anything that needs changing. We could say _something_ about the normalization of the slice (e.g., that all fields are non-None, that they all refer to points within or at the boundaries of the list, that the step is always positive), but I'm not sure it's worth it. On one hand, I don't want to make strong promises to the user about the exact form of the slice, in case we unnecessarily constrain ourselves with respect to future changes. On the other, some pieces of information are useful for the user to know, like that the start and stop won't be `None`, or negative, or greater than the length of the list, so that they don't feel that they need to do their own post-processing.

But as you say, this was more about documenting stuff at the `TraitList` level.

**Comment by mdickinson** [comment]
Thinking about this, one guarantee I _would_ be comfortable making is that in the case of a slice, `range(slice.start, slice.stop, slice.step)` always reliably recovers the positions that changed. That's likely to be the primary thing that a client of this interface cares about.
